### ISSUE TITLE
reenable unit tests on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#103]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Need to enable following unit tests on Windows since NodeXXX funcs would still run on Windows, should fix the test cases

```
~/go/src/github.com/kubernetes-csi/csi-driver-smb# grep skipIfTestingOnWindows ./* -R
./pkg/smb/nodeserver_test.go:   skipIfTestingOnWindows(t)
./pkg/smb/nodeserver_test.go:   skipIfTestingOnWindows(t)
./pkg/smb/nodeserver_test.go:   skipIfTestingOnWindows(t)
./pkg/smb/nodeserver_test.go:   skipIfTestingOnWindows(t)
./pkg/smb/smb_test.go:  skipIfTestingOnWindows(t)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
cc @mayankshah1607

**Comment by mayankshah1607** [comment]
I think we can close this one via https://github.com/kubernetes-csi/csi-driver-smb/pull/123
