### ISSUE TITLE
use golangci-lint-action

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#118]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

https://github.com/golangci/golangci-lint-action
should set up golangci-lint-action first and then if it's stable enough, retire original `hack/verify-golint.sh`

cc @mayankshah1607

**Describe alternatives you've considered**

**Additional context**

**Comment by boddumanohar** [comment]
I would like to take this task up.

**Comment by boddumanohar** [comment]
I am sorry, Mayank has been 'cced. I didn't see that.

**Comment by mayankshah1607** [comment]
>I am sorry, Mayank has been 'cced. I didn't see that.
No problem, @boddumanohar ! :)
