### ISSUE TITLE
improve unit test coverage

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#12]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

current code coverage:
https://coveralls.io/github/kubernetes-csi/csi-driver-smb?branch=master
![image](https://user-images.githubusercontent.com/4178417/81561621-0979b400-93c6-11ea-8e48-d7b86c0280ae.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
it's now:
![image](https://user-images.githubusercontent.com/4178417/82744779-cbaa6180-9daf-11ea-81b5-0f583586abb9.png)

**Comment by andyzhangx** [comment]
@animeshk08
can you work on this? thanks

**Comment by animeshk08** [comment]
Sure! Thanks!

**Comment by andyzhangx** [comment]
@animeshk08 could you also improve ut coverage of this project? thanks.

**Comment by animeshk08** [comment]
Test coverage is now 89%

![csi-smb-coverage](https://user-images.githubusercontent.com/32506591/86997889-cf157300-c1cc-11ea-967a-fbbef0eae929.png)
