### ISSUE TITLE
dynamic provisioning fully support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#120]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

PR(https://github.com/kubernetes-csi/csi-driver-smb/pull/61) added storage class support, while it's just an empty implementation, need to add fully dynamic provisioning support:
  - CreateVolume
    - Should create a new directory under smb server
  - DeleteVolume
    - Should delete current directly under smb server 

To implement this feature, need to figure out whether there is a smb go-client

**Describe alternatives you've considered**

**Additional context**

**Comment by blurpy** [comment]
Are you going to support the other part of dynamic provisioning - self service using a claim?

We are looking at this driver, but none of our users have access to cluster scoped resources like storage classes and persistent volumes. They do however have access to persistent volume claims.

Ideally users would make a PVC with similar parameters as shown in the PV-example and a PV would be created automatically.

**Comment by andyzhangx** [comment]
> Are you going to support the other part of dynamic provisioning - self service using a claim?
> 
> We are looking at this driver, but none of our users have access to cluster scoped resources like storage classes and persistent volumes. They do however have access to persistent volume claims.
> 
> Ideally users would make a PVC with similar parameters as shown in the PV-example and a PV would be created automatically.

@blurpy if there is already smb storage class or smb PV, they can use this example: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md

**Comment by blurpy** [comment]
That's the example I was talking about, but we don't really want to manually create a PV or storage class for them every time someone needs to mount a samba volume in a pod. It's a large network with hundreds of shares everywhere, so self service would be much preferred.

**Comment by andyzhangx** [comment]
> That's the example I was talking about, but we don't really want to manually create a PV or storage class for them every time someone needs to mount a samba volume in a pod. It's a large network with hundreds of shares everywhere, so self service would be much preferred.

@blurpy if you only have one SMB server, admin could set up a smb storage class and user only needs to create a PVC, and when PVC is provisioned, this driver will create a standalone dir under smb server, is that what you want?

**Comment by blurpy** [comment]
We don't look for a way of provisioning a "new" volume using SMB, we look for a way of mounting an existing shared network folder in a pod, so apps can be migrated from legacy infrastructure. The pod needs access to the same data.

There are many servers exposing SMB shares, and those of us who manage k8s don't want to be middlemen, and rather let users do this in their own namespace. Maybe this driver is not made for this use case?

**Comment by andyzhangx** [comment]
then why not create a common PVC and that PVC could be shared between multiple pods. Current scenario is:
 - admin create [smb storage class](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/storageclass-smb.yaml) with SMB server config
 - User create a PVC based on storage class and pod could access SMB server, `createSubDir` parameter could decide whether create new folder inside that SMB server

**Comment by andyzhangx** [comment]
With smb storage class, user only needs to create PVC, the PV will be created automatically

**Comment by blurpy** [comment]
From what I can understand from the documentation the storage class defines the share to connect to, so we would have to create a new storage class every time someone needs to mount a different share. Or can we configure a generic storage class and let the user specify url, username and password in the PVC somehow?

Note that we are not looking for a way to create a subdir on a share, we just want to let users mount any share they want inside a pod without involving cluster admins.

**Comment by andyzhangx** [comment]
> From what I can understand from the documentation the storage class defines the share to connect to, so we would have to create a new storage class every time someone needs to mount a different share. Or can we configure a generic storage class and let the user specify url, username and password in the PVC somehow?
> 
> Note that we are not looking for a way to create a subdir on a share, we just want to let users mount any share they want inside a pod without involving cluster admins.

PVC is quite a generic config in k8s, there is no self-defined parameter support in PVC

**Comment by andyzhangx** [comment]
I think you are asking for this inline volume feature, it's not supported yet: 
https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html#which-feature-should-my-driver-support

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
spec:
  containers:
    ...
  volumes:
      - name: vol
        csi:
          driver: inline.storage.kubernetes.io
          volumeAttributes:
              foo: bar
```

https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html#which-feature-should-my-driver-support

**Comment by blurpy** [comment]
OK, thanks for the link. Guess we have to find a different way of accessing these shares for now.

**Comment by andyzhangx** [comment]
> OK, thanks for the link. Guess we have to find a different way of accessing these shares for now.

@blurpy filed an issue here: https://github.com/kubernetes-csi/csi-driver-smb/issues/198, I could get someone work on this, the above example is for single pod, does it work in your scenario?

**Comment by andyzhangx** [comment]
refer to https://github.com/kubernetes-csi/csi-driver-nfs/pull/53, should support: 
 - create subDir in CreateVolume
 - delete subDir in DeleteVolume
