### ISSUE TITLE
Volume cannot be accessed when csi-smb-node-xxxxx pod on the same node as the node of the pod which is using PV is restarted.

### ISSUE THREAD

**Issue by githubformichael** [kubernetes-csi/csi-driver-smb#130]
**What happened**:
SMB CSI volume becomes UN-Accessible when csi-smb-node is restarted.

**What you expected to happen**:
SMB CSI volume  should still be accessible when csi-smb-node pods are restarted.

**How to reproduce it**:

1. Create a pod(smb-app-00001) which uses SMB CSI volume
2. get the node name(node-0001) on which the pod(smb-app-00001) is running
3. get the csi-smb-node's pod name(such as csi-smb-node-xxxxx) on the node (node-0001) and restart the pod(csi-smb-node-xxxxx) or restart all the pods of daemonset csi-smb-node.
4. check the SMB CSI volume inside the pod(smb-app-00001) again, you will find the volume is not accessible now.
    Error message: "ls: /mnt/smb: Resource temporarily unavailable. command terminated with exit code 1"
    or " Host is down"

**Anything else we need to know?**:
This is a critical issue, please fix it as soon as possible!

**Environment**:
- CSI Driver version:  v0.3.0
- Kubernetes version (use `kubectl version`):  
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.6.0
VERSION_ID=2135.6.0
BUILD_ID=2019-07-30-0722
PRETTY_NAME="Container Linux by CoreOS 2135.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
Linux xxxxx 4.19.56-coreos-r1 #1 SMP Tue Jul 30 06:40:10 -00 2019 x86_64 Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz GenuineIntel GNU/Linux
- Install tools:
- Others:

**Comment by boddumanohar** [comment]
related to #64 ?

**Comment by andyzhangx** [comment]
@githubformichael could you try the fix in PR: https://github.com/kubernetes-csi/csi-driver-smb/pull/131? thanks.

**Comment by githubformichael** [comment]
okay. thanks!

**Comment by andyzhangx** [comment]
I have release https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v0.4.0, pls try that version, thanks.

**Comment by githubformichael** [comment]
@andyzhangx , Thank you for your hard work!
I have checked with v0.4.0 source codes and found that the issue has been fixed!
Thank you again!
