### ISSUE TITLE
domain setting issue on Windows

### ISSUE THREAD

**Issue by mkoziel2000** [kubernetes-csi/csi-driver-smb#137]
**What happened**:
When using the CSI SMB driver in combination with csi-proxy.exe on windows nodes running windows containers, I noticed that if I create a kubernetes secret that included a "domain" key, whatever value I placed into that key was getting overriden with the word "AZURE".  I don't know difinitively whether it was in the csi-proxy or the CSI SMB driver.  Either way, this behavior breaks the ability to do on-prem Persistent volumes against windows fileshares managed by a local AD domain.

What made this problem harder to figure out was that everything was working as expected when the driver was used on a Linux worker node.

I had to recompile the csi-proxy with additional logging of the username and domain field in order to figure out this bug so it wasn't immediately obvious as to what was the root cause.

If there is a configuration setting something that overrides the credential secret with a hard coded value for the domain, I could not find it and it should be part of the documentation.

The workaround right now is to not specify the "domain" key at all when defining the kubernetes secret for the credential and instead append the domain with the username in an email format (e.g. "myusername@mydomain.com").

**What you expected to happen**:
I expected that the domain key in the credential secret would be honored and would result in a username that included the proper domain prefix so that it could perform proper NTLM authentication against a local AD directory.

**How to reproduce it**:
Followed the kubernetes documentation for installing the csi smb driver along with installing the latest csi-proxy.exe on the windows nodes.  Created a kubernetes secret that defined username, password, and domain as keys.

**Anything else we need to know?**:
My Kubernetes ecosystem is on-premise.  All nodes are VMs.  The cluster has both linux and windows nodes.  The windows nodes leverage gMSA and are setup to run windows containers.

**Environment**:
- CSI Driver version: 0.4.0
- Kubernetes version (use `kubectl version`):  1.19.3
- OS (e.g. from /etc/os-release): Ubuntu 20, Windows 2019
- Kernel (e.g. `uname -a`): Linux master1 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could you set the domain name into username field, e.g. `domain\username`, the default domain name is `AZURE`

https://github.com/kubernetes-csi/csi-driver-smb/blob/e9c2dd3a6ad5d62670177a16cad9b37f4bdabf98/pkg/smb/nodeserver.go#L179-L181

**Comment by mkoziel2000** [comment]
That all works and is the workaround I'm using today.  I think at the very least, the documentation should reflect this caveat for windows OSs to not use the domain field for the domain...its hard enough getting windows nodes to act properly in a kubernetes cluster, this logic folklore just adds to the difficulty.

**Comment by andyzhangx** [comment]
> That all works and is the workaround I'm using today. I think at the very least, the documentation should reflect this caveat for windows OSs to not use the domain field for the domain...its hard enough getting windows nodes to act properly in a kubernetes cluster, this logic folklore just adds to the difficulty.

@mkoziel2000 finally I spent some time and figured out your point, here is the fixed PR: https://github.com/kubernetes-csi/csi-driver-smb/pull/168, currently we have two places to set domain:
 - `Domain\username`
 - domain field in secret
The above PR would fix the domain issue on Windows.
