### ISSUE TITLE
[ARM64]Can't Mount SMB Volumes, Exec format error

### ISSUE THREAD

**Issue by kferrone** [kubernetes-csi/csi-driver-smb#151]
I am finally able to run the entire project on a k3s RaspberryPi cluster. But now that I have created a StorageClass and a PVC using it, I get the following error when a Pod tries to mount it:
```
MountVolume.MountDevice failed for volume "pvc-8b5c7a54-6dd8-4e84-9d2d-e604c1a8a6da" : rpc error: code = Internal desc = volume(pvc-8b5c7a54-6dd8-4e84-9d2d-e604c1a8a6da) mount "//kraken.burbs/volumes" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8b5c7a54-6dd8-4e84-9d2d-e604c1a8a6da/globalmount" failed with mount failed: fork/exec /bin/mount: exec format error Mounting command: mount Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=1000,gid=1000,<masked> //kraken.burbs/volumes /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8b5c7a54-6dd8-4e84-9d2d-e604c1a8a6da/globalmount Output:
```

The storage class, PVC, and PV all got created without any issue and the PV and PVC both say bound.

The error above seems to be coming from the smb-csi image in the `smb` container. 

Am I missing something? Do I need to install anything on the host of of the nodes?

**Comment by kferrone** [comment]
I was able to use the manual `mount -t cifs ...` command that the smb container is using and it worked on the host os.

**Comment by andyzhangx** [comment]
it's on ARM64 arch, right? Here is the Dockerfile:

https://github.com/kubernetes-csi/csi-driver-smb/blob/4f01661f9aac5211567699d667fb8ee6928cc6b1/pkg/smbplugin/Dockerfile#L21-L23

What's your agent node os type? I think we may change base image to have a try.

**Comment by kferrone** [comment]
Yes it is ARM64 architecture. The base OS is Ubuntu 20.04.

I found here the same builder-image but for Arm64. https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/debian-base-arm64?gcrImageListsize=30

**Comment by andyzhangx** [comment]
PR(https://github.com/kubernetes-csi/csi-driver-smb/pull/154) should fix the issue:
could you try:
```console
kubectl apply -f https://raw.githubusercontent.com/andyzhangx/csi-driver-smb/pull-always/deploy/csi-smb-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/andyzhangx/csi-driver-smb/pull-always/deploy/csi-smb-node.yaml
```

**Comment by kferrone** [comment]
Oh my yes that did work! You just made my week on a Monday 🤩
I can officially say the smb-csi driver works on ARM.
Thanks a ton and have a good day sir! 
Keep up the great work
