### ISSUE TITLE
publish container linux and windows images in quay.io

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#16]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently docker files are under here:
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smbplugin/Dockerfile
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/pkg/smbplugin/Windows.Dockerfile

could refer to:
https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/release-tools/travis.yml

do you know how to do that? thanks
@wozniakjan

cc @jingxu97 @msau42 

**Describe alternatives you've considered**

**Additional context**

**Comment by wozniakjan** [comment]
hi @andyzhangx, the csi-release-tools repo contains very useful documentation on how to get started - https://github.com/kubernetes-csi/csi-release-tools/.

I am not entirely sure the tooling supports windows images too, tagging @pohly as he is much more knowledgeable point of contact with regards to the csi-release-tools.

**Comment by msau42** [comment]
We're trying to move our image publishing to the k8s-infra and @jingxu97 is working on getting Windows image building working there.

**Comment by andyzhangx** [comment]
@jingxu97 do you know how can I publish the repo image to quay, it should support both windows and linux image. I am thinking whether it's appropriate to host the images on `mcr.microsoft.com` which I am quite familiar with.

**Comment by xing-yang** [comment]
@andyzhangx we are moving away from quay and publish images to the community infra.  See issue opened here: https://github.com/kubernetes-csi/csi-release-tools/issues/86

@pohly is in the process of making this change for all kubernetes-csi repos.

See this one for example: https://github.com/kubernetes-csi/csi-proxy/pull/54
