### ISSUE TITLE
samba server not support domain name

### ISSUE THREAD

**Issue by junneyang** [kubernetes-csi/csi-driver-smb#160]
when i use 
`source: \\sfs-nas1.cn-south-1c.xxx.com\share-2d58d4ca   `
is does not work, but when i use 
`source: \\10.12.13.5\share-2d58d4ca `
it works

thanks for your help!

**Comment by andyzhangx** [comment]
could you provide more detailed info? e.g. linux or windows, k8s version, it looks like domain name could not be resolved in your env.

**Comment by junneyang** [comment]
> could you provide more detailed info? e.g. linux or windows, k8s version, it looks like domain name could not be resolved in your env.

windows: 2019
k8s: v1.17.2

when i run command in the pod:
`net use X: \\sfs-nas1.cn-south-1c.xxx.com\share-2d58d4ca`     
it could be mount success

**Comment by junneyang** [comment]
![image](https://user-images.githubusercontent.com/6802322/99372439-20600c80-28fb-11eb-8f52-26115c31ed93.png)

**Comment by andyzhangx** [comment]
that could be a limitation of windows csi-proxy since that component could not resolve domain name, will follow up with that later, use public ip always work now.

**Comment by junneyang** [comment]
> that could be a limitation of windows csi-proxy since that component could not resolve domain name, will follow up with that later, use public ip always work now.

very thanks for your help
would it be supported in the future?
