### ISSUE TITLE
Mount failed on EKS with "permission denied" when username is in format "DOMAIN\USER"

### ISSUE THREAD

**Issue by VasylSamoilov** [kubernetes-csi/csi-driver-smb#162]
I try to use csi smb client on AWS EKS v1.17. Worker nodes are linux, provisioned by AWS. I tried all possible options, tried to run daemonset in privileged mode, container in privileged mode and installing helm chart and manually, as PV and as storage class. Outcome is always the same: Mount error: permission denied.
If I launch container with ubuntu I can connect to share with smbclient, so connectivity is ok and login/password is valid.

`MountVolume.MountDevice failed for volume "pvc-4b279c86-e427-4c8c-8cd2-6b5e8f5ef119" : rpc error: code = Internal desc = volume(pvc-4b279c86-e427-4c8c-8cd2-6b5e8f5ef119) mount "//server/SHARE" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4b279c86-e427-4c8c-8cd2-6b5e8f5ef119/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o <masked> //server/SHARE /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4b279c86-e427-4c8c-8cd2-6b5e8f5ef119/globalmount
Output: mount error(13): Permission denied
`

**Comment by andyzhangx** [comment]
there is an smb server set up example here: https://github.com/kubernetes-csi/csi-driver-smb/tree/master/deploy/example/smb-provisioner, does that work? 

Also could you run `# k exec -it csi-smb-node-4qhfz -n kube-system -c smb sh` to ssh to the driver container, and then try `mount -t cifs //smb-server/share /tmp/test -o vers=3.0,username=username,password=test,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
`

I think that would narrow down the issue a lot.

**Comment by VasylSamoilov** [comment]
$ kubectl exec -ti csi-smb-node-4fblr -n kube-system -c smb /bin/sh

Real server:

# mount -t cifs //server/SHARE /tmp/test -o vers=3.0,username="Domain\USER_name",password="Pass1234",dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
Couldn't chdir to /tmp/test: No such file or directory
# mkdir /tmp/test
# mount -t cifs //server/SHARE /tmp/test -o vers=3.0,username="Domain\USER_name",password="Pass1234",dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

Test server inside cluster:

#mount -t cifs //10.183.147.123/share /tmp/test -o vers=3.0,username="Test",password="test",dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
sucess!

Maybe the problem is with user name in format "Domain\USER_name" ? I was not able to create server with such user, script fails on start. Client may also have a problem, I suppose.

**Comment by VasylSamoilov** [comment]
I do confirm that everything works fine when username don't include domain part.

**Comment by andyzhangx** [comment]
I think domain is only supported on Windows

**Comment by andyzhangx** [comment]
I got your point, if you want to set domain for Linux agent node, should be set by:
```
kubectl create secret generic smbcreds --from-literal username=USERNAME --from-literal password="PASSWORD" --from-literal domain=DOMAIN-NAME
```
