### ISSUE TITLE
Add Helm Chart

### ISSUE THREAD

**Issue by JesperBerggren** [kubernetes-csi/csi-driver-smb#169]
**Is your feature request related to a problem?/Why is this needed**
The current installation and upgrade process is a bit too manual in my humble opinion. An installation script is not really the right approach to solving installation and maintenance of the driver in production environment.
A package manager solves that problem.

**Describe the solution you'd like in detail**
A Helm Chart, please, so we can maintain the driver as a package.

**Describe alternatives you've considered**
None.

**Additional context**

N/A

**Comment by andyzhangx** [comment]
helm chart is already supported: https://github.com/kubernetes-csi/csi-driver-smb/tree/master/charts

**Comment by JesperBerggren** [comment]
Oh, you're right.
Can I instead suggest that you add Helm under the installation methods described under "Install SMB CSI driver on a kubernetes cluster" on your main page: [https://github.com/kubernetes-csi/csi-driver-smb](https://github.com/kubernetes-csi/csi-driver-smb)

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-csi/csi-driver-smb/commit/1a5c9ad3019b064272be20ed86a8471a368dc323, thanks.
