### ISSUE TITLE
update base image with debian-base

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#19]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

update base image with debian-base which has less security vulnerability:
could refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/273

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
@animeshk08
can you work on this? thanks

**Comment by animeshk08** [comment]
Sure! Thanks!
