### ISSUE TITLE
K3s - In a docker-compose (path "/var/lib/kubelet/" is mounted on "/var/lib/kubelet" but it is not a shared mount)

### ISSUE THREAD

**Issue by doug62** [kubernetes-csi/csi-driver-smb#191]
After installing V6 via helm with default values.yml, On K3s running within a docker-compose  stack on a windows PC with Linux containers i receive the following:

CreateContainerError: failed to generate container "e0fedc59f3d3351eec4f6a3877102b93f3ba94ffe2412f18c79a21631187ea97" spec: failed to generate spec: path "/var/lib/kubelet/" is mounted on "/var/lib/kubelet" but it is not a shared mount

(Also had problems pulling latest helm, a bit new to this but received a semantic version error and I'm not sure all the helm files are there)

Thanks!

**Comment by andyzhangx** [comment]
not sure about how to make it work in docker-compose stack, and about helm chart version issue, the latest helm does not support `latest` tag now, I suggest use specific version

**Comment by andyzhangx** [comment]
about error `path "/var/lib/kubelet/" is mounted on "/var/lib/kubelet" but it is not a shared mount`, follow this link to workaround: https://github.com/kubernetes-retired/kubernetes-anywhere/issues/88#issuecomment-292407728

**Comment by gsxmax** [comment]
If you try the workaround,  but you are encountering the same error, please check "**findmnt -o TARGET,PROPAGATION /var/**", and "**findmnt -o TARGET,PROPAGATION /var/lib/kubelet/**". If the PROPAGATION is already shared, please follow this document and check your docker configuration. 
https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation

**Comment by doug62** [comment]
@andyzhangx - Thanks for the link those directions do in fact work on linux machines, but not on windows.

**Comment by andyzhangx** [comment]
> @gsxmax @andyzhangx - Thanks for the link those directions do in fact work on linux machines, but not on windows.

I dot not suggest run this driver on docker-compose on Windows
