### ISSUE TITLE
helm repo add mylocal-csi-driver <what github url do i put here?>

### ISSUE THREAD

**Issue by doug62** [kubernetes-csi/csi-driver-smb#196]
As a newbie user, I would like to be able add this github chart/source to my local installed charts so that I can install them locally without having to download them.

helm repo add mylocal-csi-driver <what github url do i put here?>

What is the URL? (thanks)

**Comment by andyzhangx** [comment]
```console
helm repo add csi-driver-smb https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
helm install csi-driver-smb csi-driver-smb/csi-driver-smb --namespace kube-system --version v0.6.0
```

**Comment by splitt3r** [comment]
@andyzhangx what about publishing to GitHub Pages and / or artifacthub.io? Sth. like https://artifacthub.io/packages/helm/mlohr/hcloud-csi-driver would be pretty awesome.

**Comment by andyzhangx** [comment]
updated doc here: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/charts/README.md#install-a-specific-version-of-helm-chart
