### ISSUE TITLE
implement Ephemeral Inline Volumes support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#198]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

refer to
https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html#which-feature-should-my-driver-support

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
cc @rajibmitra

**Comment by rajibmitra** [comment]
thank you @andyzhangx, looking at it.

**Comment by GuyPaddock** [comment]
/reopen

I believe something like this could solve some problems for us. We want pods to be able to connect to existing, pre-allocated storage accounts on a CIFS/SMB or NFS server without having to pre-declare a PV and manage a PVC for each one.

One question -- how would mount options like UID, GID, and authentication credentials be handled with an inline volume? I believe that the docs for inline say that mount options aren't supported.

**Comment by GuyPaddock** [comment]
@andyzhangx would _you_ consider re-opening?

**Comment by andyzhangx** [comment]
@GuyPaddock 
there are concerns from community that we don't want to support this feature, details: https://github.com/kubernetes-csi/csi-driver-nfs/issues/148
cc @jsafrane

**Comment by andyzhangx** [comment]
> /reopen
> 
> I believe something like this could solve some problems for us. We want pods to be able to connect to existing, pre-allocated storage accounts on a CIFS/SMB or NFS server without having to pre-declare a PV and manage a PVC for each one.
> 
> One question -- how would mount options like UID, GID, and authentication credentials be handled with an inline volume? I believe that the docs for inline say that mount options aren't supported.

@GuyPaddock I re-evaluated this inline volume requirement, this would requires that pod could read any secret in same namespace, there is security risk to support such functionality. It would be ok for NFS driver since nfs does not use password auth, thus does not require reading secret.

So we don't want to implement Ephemeral Inline Volumes support for this SMB driver, pls use PV/PVC way, it can also connect to existing, pre-allocated storage accounts.

> connect to existing, pre-allocated storage accounts on a CIFS/SMB or NFS server

BTW, are you referring Azure storage accounts?

**Comment by GuyPaddock** [comment]
@andyzhangx Thank you for the context! That makes sense. We were using Azure Files but are now moving to Qumulo.

**Comment by andyzhangx** [comment]
> Qumulo

@GuyPaddock do you have any suggestions why you are using Qumulo instead of Azure Files? thanks.

**Comment by GuyPaddock** [comment]
@andyzhangx Several reasons:
1. We needed more transparency around IOPS surges with real-time observability of storage consumption (Azure Files through Azure Monitor lags behind what's happening in production by several minutes).
2. Qumulo seems to handle small-file access with better performance than Azure Files.
3. Compared to Azure Files standard, Qumulo does not charge per-transaction.
4. Compared to Azure Files Premium, IOPS and throughput are not tied to quotas so we do not have to over-provision a share just for higher performance.

**Comment by kxs-jnadeau** [comment]
@andyzhangx : "So we don't want to implement Ephemeral Inline Volumes support for this SMB driver, pls use PV/PVC way, it can also connect to existing, pre-allocated storage accounts."_

I think there is a valid use case to support inline volumes just like how it is supported today with the Azure file CSI driver.    I.e. say someone uses Azure Netapp files for static volumes allocated to VMs (so not dynamic via Astra/Trident) and we want a K8s POD to share the same mount as the VM.   This driver would be handy to mount such static volume.

**Comment by kfox1111** [comment]
I think this is still a valid use case. The same functionality was implemented optionally with the nfs csi driver.

**Comment by raafatseif** [comment]
Hi @andyzhangx! Regarding reading secrets for username and password, would it  deviate a lot from the current implementation? I know it currently reads from the secret provided in the storage class or PV. Would it be possible to use the same implementation only difference would be providing the secret through the pod inline?

```
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "default"
```

**Comment by kfox1111** [comment]
csi.storage.k8s.io/node-stage-secret-namespace should be ignored in inline mode. only the pods namespace should be honored.

**Comment by raafatseif** [comment]
Gotcha, I think that might actually simplify things. Was just looking at the implementation from azurefile inline volume [example](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/nginx-pod-azurefile-inline-volume.yaml).

**Comment by kfox1111** [comment]
Still useful
