### ISSUE TITLE
Add support for SMB Direct connect to Windows Cluster in IB or ROCE network (Mellanox)

### ISSUE THREAD

**Issue by slavonnet** [kubernetes-csi/csi-driver-smb#214]
Subject

Latency over x1000 difference

**Comment by andyzhangx** [comment]
do you have more details on this?

**Comment by andyzhangx** [comment]
@slavonnet is it resolved?

**Comment by slavonnet** [comment]
I will try this
https://github.com/Mellanox/ib-kubernetes
but but IB will be great use for multicast updates, direct sccess and l;ow latancy. Not  onlu for storahe and network. for inhouse (and ROCE).

**Comment by slavonnet** [comment]
Also linux kernel now have suppoer got SMB direct access and rdma but  only in kernel side. Samba in dev now. Looks like SMD3 ok, direct ok, rdma ok, multichennel in basic stage, support one host and  need tune  parames (rdd, qieies) for win side. Its like rss more ehwn 40g and switch to 1g.

Amd ,must critical/. Application Mode down support (need for VM, DB) collect to server share. Win cluster not want use lin s,b as share for recources.

I thhink faster NBMEt comme in.. Niw ins not work, crashes etc. 
No any real work brudght between Linx and Wim

1 iscsi - win wo rdma/. Need iscsi initiator wiyj RDMA suppoer.
2 iser - win not work
3/ nfs - win no rdma
4. smb - ,need ,multichannel and app offloading mode
5. nvmtT - criticaly unstable. All reboot and crash but allready have initiatr for win
7. Foe, EIBOE - win and linux normal work only with IPoIB. All Infiniband great features only in linux world.
