### ISSUE TITLE
Liveness probe memory leak

### ISSUE THREAD

**Issue by juliohm1978** [kubernetes-csi/csi-driver-smb#226]
**What happened**:

After upgrading to v0.6.0, we are seeing regular pod restarts, some of them being **_OOMKilled_**.

Looking at the pod metrics, we can see that the liveness probe in the node pod seems to be leaking memory over time.

![image](https://user-images.githubusercontent.com/4145456/107362729-e779a300-6ab7-11eb-8ca6-3e652cf6006c.png)

**Environment**:
- CSI Driver version: v0.6.0
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release): ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): `Linux jhempc 5.10.13-arch1-2 #1 SMP PREEMPT Sat, 06 Feb 2021 11:07:29 +0000 x86_64 GNU/Linux`
- Install tools: Kubespray

**Comment by juliohm1978** [comment]
Could this be related?

https://github.com/kubernetes-csi/livenessprobe/issues/102

**Comment by juliohm1978** [comment]
A memory leak appears to have been fixed in the liveness probe image 2.2.0.

https://github.com/kubernetes-csi/livenessprobe/pull/94

https://github.com/kubernetes-csi/livenessprobe/blob/master/CHANGELOG/CHANGELOG-2.2.md

**Comment by andyzhangx** [comment]
the master branch is already using v2.2.0:
https://github.com/kubernetes-csi/csi-driver-smb/blob/2d3ef8a858e5e9c0aeae0257de237ad817a9f600/deploy/csi-smb-controller.yaml#L46-L47

**Comment by juliohm1978** [comment]
Just changed my values.yaml and redeployed. Will be back to confirm if this fixes it.
