### ISSUE TITLE
support without credential case

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#23]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

refer to https://github.com/microsoft/K8s-Storage-Plugins/issues/17

**Describe alternatives you've considered**

**Additional context**

**Comment by boddumanohar** [comment]
@andyzhangx I just tried to create a samba server without authentication and ran e2e tests on it and it worked just fine. 
```
-          args: ["-u", "$(USERNAME);$(PASSWORD)", "-s", "share;/smbshare/;yes;no;no;all;none", "-p"]
+          args: ["-s", "share;/smbshare/;yes;no;no;all;none", "-p"]
```
Can you please describe the scope of this issue? Happy to work if anything else is pending.

Thanks,
Manohar.
