### ISSUE TITLE
OpenShift pods not getting updated with the updated mount path.

### ISSUE THREAD

**Issue by arvind-sarik** [kubernetes-csi/csi-driver-smb#232]
**What happened**:
  We have installed csi smb driver in openshift cluster in order to make use of windows cifs shares. PV/PVC have been created in OpenShift cluster with the cifs-csi-pv template. We are destroying pv/pvc in the openshift namespace and recreating pv/pvc .We have source property files from where the mount path in pv get updated. It worked properly for the first time but when we updated the source property file with new mount path for the existing pv, it is not updating in the target pod.  We have verified pv/pvc are getting updated in the openshift namespace with the updated mount path but not getting updated in the target location(pod). The target pod always shows the mount path which was used from the source property file for the first time.

**What you expected to happen**:
We are expecting the updated path in the source property file need to be updated in the target location (pod)
Example:
dev. properties:(bitbucket)
mountpath=//hostname/test/test1 (worked for the first time when we created pv/pvc and deployed)
mountpath=//hostname/test/test2(Not updating this path in the target location(OpenShift pod). Instead it's always showing the previous mountpath i.e //hostname/test/test1 )

**How to reproduce it**:
We have openshift cluster 4.5 and installed csi smb driver to use windows cifs shares. We have environment specific property files in the bitbucket. 

**Anything else we need to know?**:
We do see below errors in the csi-smb pods:

E0222 17:16:13.863295       1 utils.go:123] GRPC error: rpc error: code = Internal desc = failed to stat file /var/lib/kubelet/pods/249d4ef9-42f0-48b2-a519-feca9cfeb0c2/volumes/kubernetes.io~csi/namespace-mount*/mount: stat /var/lib/kubelet/pods/249d4ef9-42f0-48b2-a519-feca9cfeb0c2/volumes/kubernetes.io~csi/namespace-mount*/mount: interrupted system call

E0219 19:05:30.501860       1 utils.go:123] GRPC error: rpc error: code = Aborted desc = An operation with the given Volume ID mount-*-Handle already exists (We have updated pv/pvc template to have unique id) but still it didn't work.

We don't see any issues while unmounting/mounting the pv/pvc in the Openshift cluster.

**Environment**:
- CSI Driver version:
  mcr.microsoft.com/k8s/csi/smb-csi:latest  
- Kubernetes version (use `kubectl version`):
   OPENSHIFT_VERSION="4.5"
- OS (e.g. from /etc/os-release):
  NAME="Red Hat Enterprise Linux CoreOS"
  VERSION="45.82.202011131531-0"
  VERSION_ID="4.5"
  OPENSHIFT_VERSION="4.5"
  RHEL_VERSION="8.2"

- Kernel (e.g. `uname -a`):
  Linux compute-4 4.18.0-193.29.1.el8_2.x86_64 #1 SMP Thu Oct 22 10:09:53 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
why would you need to update `source` value of pv?  is it possible to create another PV, and then delete PVC, bould new PVC to new PV?

**Comment by arvind-sarik** [comment]
Initially we have the other source for the pv and then we had to update the source as it is updated in the windows cifs share. So we updated the mount path as per the windows cifs share and tried to delete pv/pvc and recreated. We did not see the updated path in the target pod location even though the pv has been updated in the opensfhit namespace.
And we did try delete pv and created new pv/pvc and bound to the pod but still it holds the initial mount path that was set.
We believe there could be a bug in the csi driver so wanted to check on it here.

**Comment by andyzhangx** [comment]
could you provide detailed steps, and pv/pvc configs?

**Comment by arvind-sarik** [comment]
We have a deployment script from where we call pv/pvc template and it creates the pv/pvc as per this template. This script also binds the pvc to the openshift pods. Please find attached pv/pvc template.
The deployment script deletes and creates pv/pvc with every new deployment and it calls the property files where we have environment specific properties(such as dev.props, qa.props etc..)
So when we first add the mount shares in the property file with existing mount paths as per windows share we were able to get those paths in the target pods respectively. But we had some changes in the directory structure in windows share so we had to update the path in the mount share accordingly and did a new deploy. So with the new deployment as per the script it deletes the pv/pvc from the target namespace and recreates it. The updated path is getting updated in the pv in the target namespace but when pvc is bound to the target pod, it still shows the initial path which we set for the first time. The path in the target pod is not getting updated even though the pv is updated with new mount share in the namespace.

We have tested this manually as well by creating pv/pvc in the openshift namespace and bind the pvc to one of our applications. Please find the pv/pvc templates which does have the hard coded value instead variables. Attached are pv and pvc templates.
And for the deployment config yaml we have added below configuration to bind the pvc.

volumes:
  - name: mount-study-guide-content
    persistentVolumeClaim:
      claimName: trax-dev-mount-study-guide-content-pvc
volumeMounts:			
  - name: mount-study-guide-content
    mountPath: /home/jboss/mountStudyGuideContent

Apart from our deployment script, you can reproduce this issue by installing csi driver in openshift and create pv/pvc templates with valid share and then once pvc is bound to the pod. And then delete pv/pvc and try to update the valid path in the pv and recreate pv/pvc and bind it to the application deployment config and redeploy. This is where we are not getting the pod updated with new path. it alwars shows the path that was set for the first time. You can use the attached hard coded pv and pvc templates.

Please let me know if you need any other details.

[pvc-template.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/6037004/pvc-template.txt)
[pv-template.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/6037005/pv-template.txt)
[pv-pvc-template.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/6036918/pv-pvc-template.txt)

**Comment by arvind-sarik** [comment]
Could you please let me know if you have any info. on this.

**Comment by andyzhangx** [comment]
why would you update pv? is it possible to delete original pv/pvc and then create new pv with new property, I am not sure whether CSI driver could support such update scenario, it's never tested.
