### ISSUE TITLE
Cannot find the file specified

### ISSUE THREAD

**Issue by mkoziel2000** [kubernetes-csi/csi-driver-smb#233]
**What happened**:
Using the smb-csi:latest image, the kubelet on windows worker nodes throw a transport error stating that "\\\\.\\\\pipe\\\\csi-proxy-filesystem-v1beta1" cannot be found.  I've verified that csi-proxy.exe is running on the node and that the pipes are active.  When I switch to using smb-csi:v0.6.0, everything starts working again.

The specific error seen is:

E0223 13:46:51.250516    5608 csi_attacher.go:328] kubernetes.io/csi: attacher.MountDevice failed: rpc error: code = Internal desc = Could not mount target \\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\my-config-development2\\globalmount: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open \\\\.\\\\pipe\\\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified."
E0223 13:46:51.251515    5608 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/smb.csi.k8s.io^config-development podName: nodeName:}" failed. No retries permitted until 2021-02-23 13:46:51.751515 -0800 PST m=+824.802431501 (durationBeforeRetry 500ms). Error: "MountVolume.MountDevice failed for volume \"my-config-development2\" (UniqueName: \"kubernetes.io/csi/smb.csi.k8s.io^config-development\") pod \"my-svc-d9567d6d7-2d2ps\" (UID: \"2434d8b6-c399-4bb2-a7bc-55198dd8644e\") : rpc error: code = Internal desc = Could not mount target \\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\my-config-development2\\globalmount: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing open \\\\\\\\.\\\\\\\\pipe\\\\\\\\csi-proxy-filesystem-v1beta1: The system cannot find the file specified.\""

**What you expected to happen**:
It should be able to communicate with the named pipes

**How to reproduce it**:
Run a hybrid cluster and install the SMB CSI driver where smb-csi:latest is defined in the deployment.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: Latest
- Kubernetes version (use `kubectl version`): 1.19.3
- OS (e.g. from /etc/os-release): Windows Server 2019 (Nov/2020 CU)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@mkoziel2000 lastest image depends on csi-proxy v0.2.2, you could use following way to download v0.2.2 binary:
https://github.com/kubernetes-csi/csi-driver-smb/blob/72b5499eaf276b83c96c4b1325980c308f48d5fd/.github/workflows/windows.yaml#L27-L29

I will update the driver doc later.

**Comment by mkoziel2000** [comment]
adding a log message when it fails stating that it could be a missing or outdated version of csi-proxy might be a good addition to the code if there is going to be a version dependency between these two services.  I spend a good part of the day trying to figure this one out.  It was not trivial.  However, I do appreciate the response to validate the finding as being a problem.

Thanks.

**Comment by andyzhangx** [comment]
added doc about supported csi-proxy versions: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/README.md#container-images--kubernetes-compatibility
