### ISSUE TITLE
mount error(22): Invalid argument

### ISSUE THREAD

**Issue by tiwarishrijan** [kubernetes-csi/csi-driver-smb#248]
**What happened**:
`Warning  FailedMount  13s (x6 over 29s)  kubelet            MountVolume.MountDevice failed for volume "my-pv" : rpc error: code = Internal desc = volume(UB7GTX) mount "//10.xx.xx.xx/XXXXXXXXX" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/my-pv/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,vers=3.0,uid=1000,gid=1000,<masked> //10.xx.xx.xx/XXXXXXXXX /var/lib/kubelet/plugins/kubernetes.io/csi/pv/my-pv/globalmount
Output: mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)`

**Environment**:
- CSI Driver version:
Master
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from /etc/os-release):
AKS Pod

**Comment by andyzhangx** [comment]
it said `Invalid argument`, could you try mount manually on the node:

https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#troubleshooting-connection-failure-on-agent-node

**Comment by andyzhangx** [comment]
it turns out that password contains special chars which cifs mount could not recognize, close this issue.
