### ISSUE TITLE
smb-server.default.svc.cluster.local could not be recognized by New-SmbGlobalMapping command on Windows node

### ISSUE THREAD

**Issue by lizhuqi** [kubernetes-csi/csi-driver-smb#294]
**What happened**:
FailedMount  3s (x6 over 29s)  kubelet            MountVolume.MountDevice failed for volume "pvc-34f4bd50-0b59-4118-b814-13c3b024a478" : rpc error: code = Internal desc = volume(pvc-34f4bd50-0b59-4118-b814-13c3b024a478) mount "\\\\smb-server.default.svc.cluster.local\\share" on "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-34f4bd50-0b59-4118-b814-13c3b024a478\\globalmount" failed with smb mapping failed with error: rpc error: code = Unknown desc = NewSmbGlobalMapping failed. output: "New-SmbGlobalMapping : The network path was not found. \r\nAt line:1 char:190\r\n+ ... ser, $PWord;New-SmbGlobalMapping -RemotePath $Env:smbremotepath -Cred ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (MSFT_SmbGlobalMapping:ROOT/Microsoft/...mbGlobalMapping) [New-SmbGlobalMa \r\n   pping], CimException\r\n    + FullyQualifiedErrorId : Windows System Error 53,New-SmbGlobalMapping\r\n \r\n", err: exit status 1

**What you expected to happen**:
Mount succeed!

**How to reproduce it**:
1. Start a cluster with Windows nodes
2. Install CSI driver
3. Install a samba server 
4. Deploy a storage class
    kubectl apply -f https://gist.githubusercontent.com/lizhuqi/087c1cf8410f1a9ba681ee4be25118c9/raw/5d434991feef1b4da77aaa87501722b7c7e0e1fa/storageclass-smb-name.yaml
5. Deploy a stateful set
     kubectl apply -f https://gist.githubusercontent.com/lizhuqi/be85a31055e8f0dfc94e8c94c73b33dd/raw/ed56a5e0af452a2ca3dcda00b5ce261cc601b8cf/statefulset-win-name.yaml

**Anything else we need to know?**:
Using public IP or cluster IP or SMB server name in a AD domain works but smb-server.default.svc.cluster.local for the samba server doesn't work. I've confirmed DNS for the smb-server.default.svc.cluster.local works fine.

kubectl exec [POD_NAME] -- nslookup smb-server.default.svc.cluster.local
Server:         10.20.0.10
Address:        10.20.0.10#53

Name:   smb-server.default.svc.cluster.local
Address: 10.20.10.72

From the error, it seems that New-SmbGlobalMapping failed to recognize smb-server.default.svc.cluster.local.

**Environment**:
- CSI Driver version: latest
- Kubernetes version (use `kubectl version`): 1.20.6

**Comment by andyzhangx** [comment]
that's different thing, csi-proxy is running as a standalone process on Windows node, so the problem here is `smb-server.default.svc.cluster.local` on Windows node

**Comment by jsturtevant** [comment]
Are you using containerd?  this looks similiar to https://github.com/kubernetes-sigs/windows-gmsa/issues/30.  

What version of Windows OS are you using?  And it sounds like you have AD configured with GMSA?

**Comment by andyzhangx** [comment]
> Are you using containerd? this looks similiar to [kubernetes-sigs/windows-gmsa#30](https://github.com/kubernetes-sigs/windows-gmsa/issues/30).
> 
> What version of Windows OS are you using? And it sounds like you have AD configured with GMSA?

@jsturtevant it's different issue, public domain name could be resolved, while k8s cluster domain name `*.default.svc.cluster.local` could not be resolved by csi-proxy.exe on windows node, I think that's expected. And usually it only affects testing since in most cases, user should use public domain name for smb server.

**Comment by lizhuqi** [comment]
> Are you using containerd? this looks similiar to [kubernetes-sigs/windows-gmsa#30](https://github.com/kubernetes-sigs/windows-gmsa/issues/30).
> 
> What version of Windows OS are you using? And it sounds like you have AD configured with GMSA?

I am using docker. OS version is 10.0.17763.1757. I tested both, public domain name from a smb server  in AD works fine. server.default.svc.cluster.local from a Samba server running in linux node doesn't work

**Comment by lizhuqi** [comment]
> > Are you using containerd? this looks similiar to [kubernetes-sigs/windows-gmsa#30](https://github.com/kubernetes-sigs/windows-gmsa/issues/30).
> > What version of Windows OS are you using? And it sounds like you have AD configured with GMSA?
> 
> @jsturtevant it's different issue, public domain name could be resolved, while k8s cluster domain name `*.default.svc.cluster.local` could not be resolved by csi-proxy.exe on windows node, I think that's expected. And usually it only affects testing since in most cases, user should use public domain name for smb server.

I think some customer may want to use samba server to export the smb share without using AD. The error is thrown by New-SmbGlobalMapping. do you feel csi-proxy.exe shall resolve the name to IP before passing it to New-SmbGlobalMapping?

**Comment by andyzhangx** [comment]
> > > Are you using containerd? this looks similiar to [kubernetes-sigs/windows-gmsa#30](https://github.com/kubernetes-sigs/windows-gmsa/issues/30).
> > > What version of Windows OS are you using? And it sounds like you have AD configured with GMSA?
> > 
> > 
> > @jsturtevant it's different issue, public domain name could be resolved, while k8s cluster domain name `*.default.svc.cluster.local` could not be resolved by csi-proxy.exe on windows node, I think that's expected. And usually it only affects testing since in most cases, user should use public domain name for smb server.
> 
> I think some customer may want to use samba server to export the smb share without using AD. The error is thrown by New-SmbGlobalMapping. do you feel csi-proxy.exe shall resolve the name to IP before passing it to New-SmbGlobalMapping?

@lizhuqi one workaround is resolve to IP in our disk driver, and replace domain name with IP in `source`

**Comment by lizhuqi** [comment]
/assign

I will implement this workaround.

**Comment by omelius** [comment]
In my situation with sink (samba in kubernetes), service is resolved to cluster ip address however it also fails on windows nodes.

Log from csi-proxy pod on windows node:
```
I0313 18:59:51.774799   18360 server.go:56] calling NewSmbGlobalMapping with remote path "\\\\10.152.183.41\\pvc-portal-media"
I0313 18:59:52.941139   18360 server.go:98] Remote \\10.152.183.41\pvc-portal-media not mapped. Mapping now!
E0313 19:00:15.409361   18360 server.go:101] failed NewSmbGlobalMapping NewSmbGlobalMapping failed. output: "New-SmbGlobalMapping : The network path was not found. \r\nAt line:1 char:190\r\n+ ... ser, $PWord;New-SmbGlobalMapping -RemotePath $Env:smbremotepath -Cred ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (MSFT_SmbGlobalMapping:ROOT/Microsoft/...mbGlobalMapping) [New-SmbGlobalMa \r\n   pping], CimException\r\n    + FullyQualifiedErrorId : Windows System Error 53,New-SmbGlobalMapping\r\n \r\n", err: exit status 1
```

Event log Microsoft-Windows-SMBClient/Connectivity from windows node:
```
Set socket security failed.

Error: {Operation Failed}
The requested operation was unsuccessful.

Server name: 10.152.183.41
```
=========================================
```
Failed to establish a network connection.

Error: {Device Timeout}
The specified I/O operation on %hs was not completed before the time-out period expired.

Server name: 10.152.183.41
Server address: 10.152.183.41:445
Instance name: \Device\LanmanRedirector
Connection type: Wsk

Guidance:
This indicates a problem with the underlying network or transport, such as with TCP/IP, and not with SMB. A firewall that blocks TCP port 445, or TCP port 5445 when using an iWARP RDMA adapter, can also cause this issue.
```

**Comment by andyzhangx** [comment]
cluster ip address is a k8s concept, it could not be accessed by csi-proxy process on Windows node, pls use a public ip address or if you could set ip mapping on windows, that should also work @omelius
