### ISSUE TITLE
Unable to mount multiple shares in one pod

### ISSUE THREAD

**Issue by putz612** [kubernetes-csi/csi-driver-smb#30]
**What happened**:
When two shares are declared in a deployment the pod never comes ready.   Have one or the other volume works perfectly.  
**What you expected to happen**:
To be able to mount multiple share/volumes in a single pod
**How to reproduce it**:
Declare two PV/PVC per the documentation
Create a deployment mounting the PVC to separate volume mount points 
- /host/shareA mount to /a
-  /host/shareB mount to /b
Having one or the other declared will work but having two the container never mounts all the volumes.  Having a single SMB mount and a different volume (longhorn in my case) works.  

`Events:
  Type     Reason            Age    From                      Message
  ----     ------            ----   ----                      -------
  Warning  FailedScheduling  5m13s  default-scheduler         AssumePod failed: pod 95a37a18-771a-4479-859f-495f938ece39 is in the cache, so can't be assumed
  Normal   Scheduled         5m13s  default-scheduler         Successfully assigned beets/beets-5bbb955548-29kmd to rancher-worker2
  Warning  FailedMount       3m10s  kubelet, rancher-worker2  Unable to attach or mount volumes: unmounted volumes=[m], unattached volumes=[default-token-48qlb m a]: timed out waiting for the condition
  Warning  FailedMount       56s    kubelet, rancher-worker2  Unable to attach or mount volumes: unmounted volumes=[m], unattached volumes=[a default-token-48qlb m]: timed out waiting for the condition`

**Anything else we need to know?**:
Looking in the logs for the CSI SMB node it looks like it mounted just fine.

`GRPC request: volume_id:"arbitrary-volumeid" staging_target_path:"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-music/globalmount" target_path:"/var/lib/kubelet/pods/3222296d-cab7-468f-b92c-7c1309d49772/volumes/kubernetes.io~csi/pv-music/mount" volume_capability:<mount:<mount_flags:"dir_mode=0777" mount_flags:"file_mode=0777" mount_flags:"vers=2.0" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:"csi.storage.k8s.io/ephemeral" value:"false" > volume_context:<key:"csi.storage.k8s.io/pod.name" value:"beets-656454cffb-9ftf5" > volume_context:<key:"csi.storage.k8s.io/pod.namespace" value:"beets" > volume_context:<key:"csi.storage.k8s.io/pod.uid" value:"3222296d-cab7-468f-b92c-7c1309d49772" > volume_context:<key:"csi.storage.k8s.io/serviceAccount.name" value:"default" > volume_context:<key:"source" value:"//192.168.100.180/Music" >
NodePublishVolume called with request {arbitrary-volumeid map[] /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-music/globalmount /var/lib/kubelet/pods/3222296d-cab7-468f-b92c-7c1309d49772/volumes/kubernetes.io~csi/pv-music/mount mount:<mount_flags:"dir_mode=0777" mount_flags:"file_mode=0777" mount_flags:"vers=2.0" > access_mode:<mode:MULTI_NODE_MULTI_WRITER >  false map[] map[csi.storage.k8s.io/ephemeral:false csi.storage.k8s.io/pod.name:beets-656454cffb-9ftf5 csi.storage.k8s.io/pod.namespace:beets csi.storage.k8s.io/pod.uid:3222296d-cab7-468f-b92c-7c1309d49772 csi.storage.k8s.io/serviceAccount.name:default source://192.168.100.180/Music] {} [] 0}
NodePublishVolume: mounting /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-music/globalmount at /var/lib/kubelet/pods/3222296d-cab7-468f-b92c-7c1309d49772/volumes/kubernetes.io~csi/pv-music/mount with mountOptions: [bind]
NodePublishVolume: mount /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-music/globalmount at /var/lib/kubelet/pods/3222296d-cab7-468f-b92c-7c1309d49772/volumes/kubernetes.io~csi/pv-music/mount successfully`

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
Rancher v2.3.5
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3",
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5"
- OS (e.g. from /etc/os-release):
Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`):
5.4.0-37
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
that's probably due to same volumeid in your two PVs: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/pv-smb-csi.yaml#L19 

pls make sure your volume id is unique:
`volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster`

**Comment by putz612** [comment]
Yep, that works.  I missed that part when setting up.  Got too excited to have it working!

**Comment by dlaufer** [comment]
In my case, just deleting the pod and letting it recreate itself resolved this issue.
