### ISSUE TITLE
Periodic failure to mount

### ISSUE THREAD

**Issue by zenbones** [kubernetes-csi/csi-driver-smb#302]
EKS with Kubernetes 1.19
Samba share running in AWS on windows servers

The samba host has been running for a long time and is used by both EKS pods and EC2 installations. Works fine most of the time but 1 in 10 EKS pods fail consistently with errors like this...

```
Events:
  Type     Reason       Age                   From                                Message
  ----     ------       ----                  ----                                -------
  Normal   Scheduled    14m                   default-scheduler                   Successfully assigned prod/prod1-epicenter-platform-vtnxh to ip-10-0-2-94.ec2.internal
  Warning  FailedMount  12m                   kubelet, ip-10-0-2-94.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[case-insensitive-projects], unattached volumes=[case-sensitive-projects default-token-hnjds license config case-insensitive-projects]: timed out waiting for the condition
  Warning  FailedMount  8m5s                  kubelet, ip-10-0-2-94.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[case-insensitive-projects], unattached volumes=[case-insensitive-projects case-sensitive-projects default-token-hnjds license config]: timed out waiting for the condition
  Warning  FailedMount  5m48s                 kubelet, ip-10-0-2-94.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[case-insensitive-projects], unattached volumes=[license config case-insensitive-projects case-sensitive-projects default-token-hnjds]: timed out waiting for the condition
  Warning  FailedMount  2m11s (x13 over 14m)  kubelet, ip-10-0-2-94.ec2.internal  MountVolume.MountDevice failed for volume "prod1-smb-pv" : rpc error: code = Internal desc = volume(smb-volumeid) mount "//forio-files.forio.internal/epicenter-files" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=300,gid=300,vers=3.0,<masked> //forio-files.forio.internal/epicenter-files /var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  76s (x3 over 10m)  kubelet, ip-10-0-2-94.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[case-insensitive-projects], unattached volumes=[default-token-hnjds license config case-insensitive-projects case-sensitive-projects]: timed out waiting for the condition
```

And the pod never comes out of the waiting condition. The other pods started up in the same release, using the same helm installed cifs driver, are all fine.

**Comment by zenbones** [comment]
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-epicenter-insensitive-persistent-volume
  namespace: "{{ .Release.Namespace }}"
spec:
  storageClassName: {{ .Release.Name }}-smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      bucket: case-insensitive

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-smb-pv
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    bucket: case-insensitive
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: {{ .Release.Name }}-smb
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=300
    - gid=300
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//forio-files.forio.internal/epicenter-files"
    nodeStageSecretRef:
      name: {{ .Release.Name }}-smb-secret
      namespace: "{{ .Release.Namespace }}"
```

**Comment by andyzhangx** [comment]
what's the driver version are you using? Would you try latest GA v1.0.0 version?

**Comment by andyzhangx** [comment]
and pls also provide node driver logs on agent node(`ip-10-0-2-94.ec2.internal`), follow by: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by zenbones** [comment]
Well, started up our installation today and no error once again. That would be the 'periodic' nature of this problem. As soon as I can generate the error again I'll grab those logs and add them here.

**Comment by andyzhangx** [comment]
and once it repro, pls check whether `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount` is created on the agent node. It could be also smb server issue, e.g. there is a DFS file share issue which would also lead to this exact same error(`mount error(2): No such file or directory`), details: https://github.com/Azure/AKS/issues/2292

**Comment by zenbones** [comment]
Caught that issue in action again, same event log a already given. There are 2 controller pods and the logs are...

```
W0608 18:58:06.694385       1 main.go:59] nodeid is empty
I0608 18:58:06.694547       1 main.go:85] set up prometheus server on [::]:29644
I0608 18:58:06.694871       1 smb.go:63] 
DRIVER INFORMATION:
-------------------
Build Date: "2021-06-03T04:34:39Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.1.0
Git Commit: 195e922902f613dbd98f15ee8aa64a2a6e818784
Go Version: go1.16
Platform: linux/amd64

Streaming logs below:
I0608 18:58:06.694984       1 mount_linux.go:192] Detected OS without systemd
I0608 18:58:06.694996       1 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
I0608 18:58:06.695002       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
I0608 18:58:06.695005       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0608 18:58:06.695011       1 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
I0608 18:58:06.695015       1 driver.go:112] Enabling volume access mode: MULTI_NODE_SINGLE_WRITER
I0608 18:58:06.695019       1 driver.go:112] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0608 18:58:06.695024       1 driver.go:103] Enabling node service capability: GET_VOLUME_STATS
I0608 18:58:06.695029       1 driver.go:103] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0608 18:58:06.695184       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0608 18:58:06.795454       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0608 18:58:06.795476       1 utils.go:119] GRPC request: {}
I0608 18:58:06.796433       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.1.0"}
I0608 18:58:06.798448       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0608 18:58:06.798466       1 utils.go:119] GRPC request: {}
I0608 18:58:06.799818       1 utils.go:125] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I0608 18:58:06.801148       1 utils.go:118] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0608 18:58:06.801163       1 utils.go:119] GRPC request: {}
I0608 18:58:06.801691       1 utils.go:125] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I0608 18:58:07.599548       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0608 18:58:07.599568       1 utils.go:119] GRPC request: {}
I0608 18:58:07.600227       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.1.0"}
```

...and...

```
W0608 18:58:06.694211       1 main.go:59] nodeid is empty
I0608 18:58:06.694544       1 main.go:85] set up prometheus server on [::]:29644
I0608 18:58:06.694978       1 smb.go:63] 
DRIVER INFORMATION:
-------------------
Build Date: "2021-06-03T04:34:39Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.1.0
Git Commit: 195e922902f613dbd98f15ee8aa64a2a6e818784
Go Version: go1.16
Platform: linux/amd64

Streaming logs below:
I0608 18:58:06.695095       1 mount_linux.go:192] Detected OS without systemd
I0608 18:58:06.695111       1 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
I0608 18:58:06.695117       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
I0608 18:58:06.695122       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0608 18:58:06.695126       1 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
I0608 18:58:06.695130       1 driver.go:112] Enabling volume access mode: MULTI_NODE_SINGLE_WRITER
I0608 18:58:06.695134       1 driver.go:112] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0608 18:58:06.695139       1 driver.go:103] Enabling node service capability: GET_VOLUME_STATS
I0608 18:58:06.695144       1 driver.go:103] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0608 18:58:06.695293       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0608 18:58:06.795998       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0608 18:58:06.796016       1 utils.go:119] GRPC request: {}
I0608 18:58:06.798551       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.1.0"}
I0608 18:58:06.799460       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0608 18:58:06.799475       1 utils.go:119] GRPC request: {}
I0608 18:58:06.799991       1 utils.go:125] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I0608 18:58:06.801309       1 utils.go:118] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0608 18:58:06.801322       1 utils.go:119] GRPC request: {}
I0608 18:58:06.801720       1 utils.go:125] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I0608 18:58:07.599474       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0608 18:58:07.599492       1 utils.go:119] GRPC request: {}
I0608 18:58:07.601054       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.1.0"}
```

**Comment by zenbones** [comment]
I can't check whether the globalmount directory exists on the agent because neither 'ls' nor 'bash' are available on the pod via 'kubectl exec -it'. The driver was installed via helm chart...

https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts

So if it's the DFS file share issue the chart should probably be updated with the fixed version? And I'm running in EKS on AWS if that makes a difference?

I suspect a race condition due to the inconsistent nature of the problem, but it can't be that hard to produce if I'm getting t this often.

**Comment by andyzhangx** [comment]
for this issue, we only need agent node driver logs (not controller logs), and you could ssh to the node by kubectl-enter: https://github.com/andyzhangx/demo/tree/master/dev#kubectl-enter

**Comment by zenbones** [comment]
I'm on a windows machine so I'm not sure that kubectl-enter will do me any good. I will attempt to see if the globalmount directory exists the next time this problem occurs. When this happened the last time I noticed that it was the same IP address, ending in .94, as the last, even though the cluster had been shut down. That's unusual in AWS and made me wonder if it was a problem specific to a particular VM being handed to us. I deleted the node and tried again and everything worked well. I'm actually hoping to see the issue again soon in any case so I can provide further information for this ticket.

**Comment by zenbones** [comment]
Caught the error in action again...

[smblog.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/6645521/smblog.txt)

**Comment by zenbones** [comment]
I was also able to conform the existence of the globalmount dir...

```
kubectl exec -n kube-system -it csi-smb-node-k6h4p -c smb -- ls -la /var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount
total 0
drwxrwxrwx 2  300  300  0 Mar 29  2019 .
drwxr-x--- 3 root root 46 Jun 14 03:56 ..
drwxrwxrwx 2  300  300  0 Apr 30 18:31 projects
drwxrwxrwx 2  300  300  0 Jan 20  2015 shared-worker-libs
drwxrwxrwx 2  300  300  0 Sep 25  2020 temp
```

**Comment by zenbones** [comment]
I had a replication of the error and gathered the information you requested. Here's the log from the agent...

[smb.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/6651870/smb.txt)

And here's proof that the /var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount directory does not exist...

```
PS C:\Users\david\Documents\Nutshell\empyrean\aeon\pantheon\com\forio\epicenter-control\helm\infrastructure> kubectl exec -n kube-system -it csi-smb-node-9tqgt -c smb -- ls -la /var/lib/kubelet/plugins/kubernetes.io/csi/pv        total 0
drwxr-x--- 3 root root 26 Jun 15 00:05 .
drwxr-x--- 3 root root 16 Jun 14 23:50 ..
drwxr-x--- 3 root root 46 Jun 14 23:50 prod1-efs-pv
```

**Comment by andyzhangx** [comment]
do other PVs use same `smb-volumeid` in your cluster?

**Comment by zenbones** [comment]
Looking at the volume handle I clearly intended to make that more descriptively unique but never did, so I can see the question. However, as it turns out, we have only one smb pv in the cluster, and that volume handle, however generic, is unique and used nowhere else.

**Comment by zenbones** [comment]
Changing the version to 1.0 has so far been much more successful.

**Comment by zenbones** [comment]
Started failing again consistently, even at version 1.0, but emitting this command...

` kubectl exec -n kube-system -it csi-smb-node-<generated> -c smb -- mkdir -p /var/lib/kubelet/plugins/kubernetes.io/csi/pv/<smb pv name>/globalmount`

...fixed the problem, the next retry of the mount on the agent worked and everything else proceeded forward. For some reason that directory is not consistently created. Is there some way to investigate why?

**Comment by andyzhangx** [comment]
csi driver node logs should provide all details, follow: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

`/var/lib/kubelet/plugins/kubernetes.io/csi/pv/<smb pv name>/globalmount` should be created in `/NodeStageVolume` func in the logs, not sure why it was not created consistently

**Comment by zenbones** [comment]
That code looks pretty clear, but the fact that the directory does not exist is also clear. Either, this line in nodeserver.go silently fails...

		if err := os.MkdirAll(targetPath, 0750); err != nil {
			return nil, status.Error(codes.Internal, fmt.Sprintf("MkdirAll %s failed with error: %v", targetPath, err))

...or is never called, because the os denies the existence of the directory 25 lines later. I'd also admit the possibility of some asynchronous action but I'm checking minutes later and the directory still does not exist. And if that is a call to the os that can't just silently fail, the only way the code is never called is if...

	if runtime.GOOS == "windows" {

...returns true on an AWS linux ec2 instance, which seems unlikely. Would it be possible to insert a check for the existence of targetPath just before line 180 in nodeserver.go, and return an error if it does not exist? Would that do any good? I guess the mount throws that error anyway. HOw about a log statement declaring the os to be windows or not, just to confirm the code branch taken, because otherwise os.MkdirAll() is failing silently.

**Comment by zenbones** [comment]
Here's the error in action btw...

```
Build Date: "2021-07-01T01:26:26Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.2.0
Git Commit: 7dbdc2ebd65d688e950be62d0bcb68798ed863c9
Go Version: go1.16
Platform: linux/amd64

Streaming logs below:
I0701 07:43:52.457328       1 mount_linux.go:192] Detected OS without systemd
I0701 07:43:52.457343       1 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
I0701 07:43:52.457350       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
I0701 07:43:52.457354       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0701 07:43:52.457358       1 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
I0701 07:43:52.457362       1 driver.go:112] Enabling volume access mode: MULTI_NODE_SINGLE_WRITER
I0701 07:43:52.457366       1 driver.go:112] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0701 07:43:52.457371       1 driver.go:103] Enabling node service capability: GET_VOLUME_STATS
I0701 07:43:52.457374       1 driver.go:103] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0701 07:43:52.457553       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0701 07:43:52.644956       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0701 07:43:52.644983       1 utils.go:119] GRPC request: {}
I0701 07:43:52.647484       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.2.0"}
I0701 07:43:52.890776       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0701 07:43:52.890793       1 utils.go:119] GRPC request: {}
I0701 07:43:52.891442       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.2.0"}
I0701 07:43:53.117124       1 utils.go:118] GRPC call: /csi.v1.Node/NodeGetInfo
I0701 07:43:53.117146       1 utils.go:119] GRPC request: {}
I0701 07:43:53.117917       1 utils.go:125] GRPC response: {"node_id":"ip-10-0-2-13.ec2.internal"}
I0701 07:44:47.567688       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0701 07:44:47.567711       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","uid=300","gid=300","vers=1.0"]}},"access_mode":{"mode":5}},"volume_context":{"source":"//forio-files.forio.internal/epicenter-files"},"volume_id":"prod1-smb-pv"}
I0701 07:44:47.569116       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount) volumeID(prod1-smb-pv) context(map[source://forio-files.forio.internal/epicenter-files]) mountflags([dir_mode=0777 file_mode=0777 uid=300 gid=300 vers=1.0]) mountOptions([dir_mode=0777 file_mode=0777 uid=300 gid=300 vers=1.0])
I0701 07:44:47.569165       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,uid=300,gid=300,vers=1.0,<masked> //forio-files.forio.internal/epicenter-files /var/lib/kubelet/plugins/kubernetes.io/csi/pv/prod1-smb-pv/globalmount)
E0701 07:44:58.213801       1 mount_linux.go:179] Mount failed: exit status 32
```

**Comment by zenbones** [comment]
Upon seeing a mount failure I tried creating the directory again via kubectl exec and this time the procedure failed. The directory was created, but something in the mount procedure deletes the directory. I can create the dir, see that it's created, get a mount failure, and immediately after that the directory is gone. Either the go code is doing it or the os mount call is. Odd that this worked before and now doesn't. Possibly some race condition and I just got lucky earlier.

**Comment by andyzhangx** [comment]
this PR may solve the issue: https://github.com/kubernetes-csi/csi-driver-smb/pull/322

**Comment by zenbones** [comment]
Thank you for the note. I'm not sure I would have found that anytime soon, but I'm unsurprised that there was an issue in that section of the code. When does this hit the master branch image?

**Comment by andyzhangx** [comment]
> Thank you for the note. I'm not sure I would have found that anytime soon, but I'm unsurprised that there was an issue in that section of the code. When does this hit the master branch image?

@zenbones #322 is already in master branch image, I think you could have a try first.

**Comment by zenbones** [comment]
We install via helm chart. The latest version, at 1.2.0 gives...

Build Date: "2021-07-01T01:26:26Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.2.0
Git Commit: 7dbdc2ebd65d688e950be62d0bcb68798ed863c9
Go Version: go1.16
Platform: linux/amd64

...uses 'latest' tag, and still shows the issues. Not sure if 'latest' has the PR in it or not.

**Comment by andyzhangx** [comment]
follow this guide to set `imagePullPolicy: Always` with command `kubectl edit ds csi-smb-node -n kube-system`
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#update-driver-version-quickly-by-editing-driver-deployment-directly

and then you will get following build tag:
```
# k logs csi-smb-node-h6p4w -n kube-system -c smb
I0717 05:08:00.211743       1 main.go:85] set up prometheus server on [::]:29645
I0717 05:08:00.214180       1 smb.go:63]
DRIVER INFORMATION:
-------------------
Build Date: "2021-07-16T12:57:53Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.2.0
Git Commit: 657ab0cc668ca4aed5c974d107acf9b1ac628861
Go Version: go1.16
Platform: linux/amd64
```

**Comment by zenbones** [comment]
Did that and it seems that the behavior is now correct. Had a node fail a first attempt at the mount but it self corrected and all nodes are fine. First time that's happened in a long while so my initial guess is that you solved a bug and I have a solution. Very much appreciated.

I'd like to avoid hand editing the yaml each time I start a cluster. Do you know what app version this PR will be included into so I can look out for it and specify the correct chart version?

Thank you. A huge relief for us.

**Comment by andyzhangx** [comment]
I will publish a new release next week.

**Comment by andyzhangx** [comment]
v1.2.0 was published: https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.2.0
