### ISSUE TITLE
How many connection to the SMB server does driver create?

### ISSUE THREAD

**Issue by ieugen** [kubernetes-csi/csi-driver-smb#304]
Hi, 

Does the driver use one SMB connection / PV or 1 SMB connection per node ?

I am trying to figure out if this is suitable for use with Hetzner storage box. 
Storage box can offer SMB/CIFS interface but limits the number of connections to 10. 

Thanks,
Eugen

**Comment by andyzhangx** [comment]
it's one SMB connection / PV
