### ISSUE TITLE
documentation of provisioner-secrets-*

### ISSUE THREAD

**Issue by steveizzle** [kubernetes-csi/csi-driver-smb#311]
**Is your feature request related to a problem?/Why is this needed**
createSubDir paramter was removed, because it was described as redundant in the #295 .
I could find following information in the example: 

  \# if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  \# with PV name under source

But i could not find provisioner-secret in the documentation of the [driver-parameters](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md). Whats the difference to node-stage-secret for example. It is not clear on first view why this is necessary.

**Describe the solution you'd like in detail**
Description of provisioner-secret-* parameters in [driver-parameter ](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md)description

**Describe alternatives you've considered**
no alternative :)

**Additional context**

**Comment by andyzhangx** [comment]
thanks, I have updated the driver parameters: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md
