### ISSUE TITLE
Specific nodes have issues mounting PV volume ID already exists

### ISSUE THREAD

**Issue by bbgobie** [kubernetes-csi/csi-driver-smb#312]
We're having intermittent issues mounting volumes using the csi-driver-smb on AKS.
When the issue happens it seems a node suddenly can no longer complete the mount while pods on other nodes of the same deployment have no problem.
Pod events show messages like this for pods on affected nodes.
  Warning  FailedMount  12m (x46 over 18h)     kubelet  MountVolume.MountDevice failed for volume "pv-smb-csi-userstorage-core-prf-02" : rpc error: code = Aborted desc = An operation with the given Volume ID pv-smb-csi-userstorage-core-prf-02 already exists
We get similar messages on the smb-node pod
I0618 13:32:01.853268       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-userstorage-core-prf-02/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["vers=3.0","dir_mode=0777","file_mode=0777","uid=100","gid=101"]}},"access_mode":{"mode":5}},"volume_context":{"source":"***stripped***"},"volume_id":"pv-smb-csi-userstorage-core-prf-02"}
E0618 13:32:01.854950       1 utils.go:123] GRPC error: rpc error: code = Aborted desc = An operation with the given Volume ID pv-smb-csi-userstorage-core-prf-02 already exists
I0618 13:32:03.767862       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I see the globalmount folder is created on the node but the mount is not inside and the folder is just empty.
On a working node I see our mounted folder inside with systemd-network systemd-journal ownership/group.  This seems a bit weird and seems the opposite of an issue we've been looking at with the old smb-flexvolume driver which pushed us to the csi driver.
root@aks-mainprf02d-14050897-vmss000008:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-userstorage-core-prf-02/globalmount# ls -al
total 4
drwxrwxrwx 2 systemd-network systemd-journal    0 Apr 13 21:03 .
drwxr-x--- 3 root            root            4096 Jun 17 19:44 ..
drwxrwxrwx 2 systemd-network systemd-journal    0 Jun 17 20:24 userstorage
I've verified that all PV volume spec.csi.volumeHandle names are unique.

As per Andy I tried to delete the csi-smb-node, (required a --force --timeout=0)

`7m38s       Normal    Killing             pod/csi-smb-node-8lp8b               Stopping container liveness-probe
2m26s       Normal    Killing             pod/csi-smb-node-8lp8b               Stopping container smb
7m38s       Normal    Killing             pod/csi-smb-node-8lp8b               Stopping container node-driver-registrar
7m38s       Warning   FailedPreStopHook   pod/csi-smb-node-8lp8b               Exec lifecycle hook ([/bin/sh -c rm -rf /registration/smb.csi.k8s.io-reg.sock /csi/csi.sock]) for Container "node-driver-registrar" in Pod "csi-smb-node-8lp8b_kube-system(4b7a42a7-8409-4f72-a056-880029d5d217)" failed - error: command '/bin/sh -c rm -rf /registration/smb.csi.k8s.io-reg.sock /csi/csi.sock' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown\r\n"
5m23s       Warning   Unhealthy           pod/csi-smb-node-8lp8b               Liveness probe failed: Get http://10.78.37.210:29643/healthz: dial tcp 10.78.37.210:29643: connect: connection refused
97s         Warning   FailedKillPod       pod/csi-smb-node-8lp8b               error killing pod: failed to "KillContainer" for "smb" with KillContainerError: "rpc error: code = Unknown desc = operation timeout: context deadline exceeded"`

Restarting the csi-smb-node pod and a pod stuck mounting on the stuck node did not resolve the issue.

Beginning snipped of pod logs.  Seems to just keep repeating after that.
`I0619 12:59:21.307582       1 main.go:85] set up prometheus server on [::]:29645
I0619 12:59:21.307879       1 smb.go:63]
DRIVER INFORMATION:
-------------------
Build Date: "2021-06-03T03:47:37Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.0.0
Git Commit: 187b281e498784bdfa7bcd47bf8655ea58a9459d
Go Version: go1.16
Platform: linux/amd64

Streaming logs below:
I0619 12:59:21.308012       1 mount_linux.go:192] Detected OS without systemd
I0619 12:59:21.308033       1 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
I0619 12:59:21.308040       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
I0619 12:59:21.308044       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0619 12:59:21.308047       1 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
I0619 12:59:21.308051       1 driver.go:112] Enabling volume access mode: MULTI_NODE_SINGLE_WRITER
I0619 12:59:21.308056       1 driver.go:112] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0619 12:59:21.308062       1 driver.go:103] Enabling node service capability: GET_VOLUME_STATS
I0619 12:59:21.308068       1 driver.go:103] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0619 12:59:21.309628       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0619 12:59:21.874108       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0619 12:59:21.874131       1 utils.go:119] GRPC request: {}
I0619 12:59:21.877181       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.0.0"}
I0619 12:59:22.168704       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0619 12:59:22.168725       1 utils.go:119] GRPC request: {}
I0619 12:59:22.169403       1 utils.go:125] GRPC response: {"name":"smb.csi.k8s.io","vendor_version":"v1.0.0"}
I0619 12:59:22.803652       1 utils.go:118] GRPC call: /csi.v1.Node/NodeGetInfo
I0619 12:59:22.803682       1 utils.go:119] GRPC request: {}
I0619 12:59:22.804314       1 utils.go:125] GRPC response: {"node_id":"aks-kerbprf02d-14050897-vmss00000s"}
I0619 13:00:39.696465       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0619 13:00:39.696499       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-userstorage-core-prf-02/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["vers=3.0","dir_mode=0777","file_mode=0777","uid=100","gid=101"]}},"access_mode":{"mode":5}},"volume_context":{"source":"//<stripped>/pf02"},"volume_id":"pv-smb-csi-userstorage-core-prf-02"}
I0619 13:00:39.698679       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-userstorage-core-prf-02/globalmount) volumeID(pv-smb-csi-userstorage-core-prf-02) context(map[source://<stripped>/pf02]) mountflags([vers=3.0 dir_mode=0777 file_mode=0777 uid=100 gid=101]) mountOptions([vers=3.0 dir_mode=0777 file_mode=0777 uid=100 gid=101 domain=<stripped>])
I0619 13:00:39.698793       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o vers=3.0,dir_mode=0777,file_mode=0777,uid=100,gid=101,domain=<stripped>,<masked> //<stripped>/pf02 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-userstorage-core-prf-02/globalmount)
I0619 13:00:40.300807       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0619 13:00:40.300838       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-rstorage1-core-prf-02-1.0/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["vers=3.0","dir_mode=0777","file_mode=0777","uid=100","gid=101"]}},"access_mode":{"mode":5}},"volume_context":{"source":"//<stripped>/akstransientpf02"},"volume_id":"pv-smb-csi-rstorage1-core-prf-02-1.0"}
I0619 13:00:40.302326       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-rstorage1-core-prf-02-1.0/globalmount) volumeID(pv-smb-csi-rstorage1-core-prf-02-1.0) context(map[source://<stripped>/akstransientpf02]) mountflags([vers=3.0 dir_mode=0777 file_mode=0777 uid=100 gid=101]) mountOptions([vers=3.0 dir_mode=0777 file_mode=0777 uid=100 gid=101 domain=<stripped>])
I0619 13:00:40.302420       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o vers=3.0,dir_mode=0777,file_mode=0777,uid=100,gid=101,domain=<stripped>,<masked> //<stripped>/akstransientpf02 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-rstorage1-core-prf-02-1.0/globalmount)
I0619 13:00:40.703809       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0619 13:00:40.703845       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-help-core-prf-02-1/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["vers=3.0","dir_mode=0555","file_mode=0444","uid=100","gid=101"]}},"access_mode":{"mode":3}},"volume_context":{"source":"//<stripped>/helpfiles/US/ROOT/help"},"volume_id":"pv-smb-csi-help-core-prf-02-1"}
I0619 13:00:40.705533       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-help-core-prf-02-1/globalmount) volumeID(pv-smb-csi-help-core-prf-02-1) context(map[source://<stripped>/helpfiles/US/ROOT/help]) mountflags([vers=3.0 dir_mode=0555 file_mode=0444 uid=100 gid=101]) mountOptions([vers=3.0 dir_mode=0555 file_mode=0444 uid=100 gid=101 domain=<stripped>])
I0619 13:00:40.705581       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o vers=3.0,dir_mode=0555,file_mode=0444,uid=100,gid=101,domain=<stripped>,<masked> //<stripped>/helpfiles/US/ROOT/help /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-help-core-prf-02-1/globalmount) 
I0619 13:00:42.413145       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0619 13:00:42.413186       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-pccwebsite-core-prf-02-1/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["vers=3.0","dir_mode=0555","file_mode=0444","uid=100","gid=101"]}},"access_mode":{"mode":3}},"volume_context":{"source":"//<stripped>/helpfiles/US/ROOT/pccwebsite"},"volume_id":"pv-smb-csi-pccwebsite-core-prf-02-1"}
I0619 13:00:42.415964       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-pccwebsite-core-prf-02-1/globalmount) volumeID(pv-smb-csi-pccwebsite-core-prf-02-1) context(map[source://<stripped>/helpfiles/US/ROOT/pccwebsite]) mountflags([vers=3.0 dir_mode=0555 file_mode=0444 uid=100 gid=101]) mountOptions([vers=3.0 dir_mode=0555 file_mode=0444 uid=100 gid=101 domain=<stripped>])
I0619 13:00:42.416034       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o vers=3.0,dir_mode=0555,file_mode=0444,uid=100,gid=101,domain=<stripped>,<masked> //<stripped>/helpfiles/US/ROOT/pccwebsite /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-pccwebsite-core-prf-02-1/globalmount)`

**Comment by andyzhangx** [comment]
a normal `NodeStageVolume` logs is like this:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-smb/310/pull-csi-driver-smb-e2e/1405338824304758784/build-log.txt
```
[pod/csi-smb-node-5kb6c/smb] I0617 01:51:59.410094       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
[pod/csi-smb-node-5kb6c/smb] I0617 01:51:59.410111       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","uid=0","gid=0","mfsymlinks","cache=strict","nosharesock"]}},"access_mode":{"mode":1}},"volume_context":{"source":"//smb-server.default.svc.cluster.local/share/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4","storage.kubernetes.io/csiProvisionerIdentity":"1623894713967-8081-smb.csi.k8s.io"},"volume_id":"smb-server.default.svc.cluster.local/share#pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4"}
[pod/csi-smb-node-5kb6c/smb] I0617 01:51:59.411541       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4/globalmount) volumeID(smb-server.default.svc.cluster.local/share#pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4) context(map[source://smb-server.default.svc.cluster.local/share/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4 storage.kubernetes.io/csiProvisionerIdentity:1623894713967-8081-smb.csi.k8s.io]) mountflags([dir_mode=0777 file_mode=0777 uid=0 gid=0 mfsymlinks cache=strict nosharesock]) mountOptions([dir_mode=0777 file_mode=0777 uid=0 gid=0 mfsymlinks cache=strict nosharesock])
[pod/csi-smb-node-5kb6c/smb] I0617 01:51:59.411907       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,cache=strict,nosharesock,<masked> //smb-server.default.svc.cluster.local/share/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4/globalmount)
[pod/csi-smb-node-5kb6c/smb] I0617 01:51:59.912427       1 nodeserver.go:205] volume(smb-server.default.svc.cluster.local/share#pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4) mount "//smb-server.default.svc.cluster.local/share/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4/globalmount" succeeded
```

I can only find it's mounting, while it never returns like this:
```
[pod/csi-smb-node-5kb6c/smb] I0617 01:51:59.912427       1 nodeserver.go:205] volume(smb-server.default.svc.cluster.local/share#pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4) mount "//smb-server.default.svc.cluster.local/share/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ee5f06e1-f2ab-41e0-9efe-41db8f3b89a4/globalmount" succeeded
```

**Comment by andyzhangx** [comment]
what's your aks version and node vm size? looks like it's stuck there forever.

**Comment by bbgobie** [comment]
The node pool the logs were taken from are at 1.18.17
Node is sized at Standard_D8s_v3
The control plane is at 1.19.19

I was able to get a pod on the nodes in question to mount an Azure Files share.  So I'm not sure if there's some sort of config in our deployment or our Netapp that causes the issue.

The SMB share we're mounting is provided by a NetApp hosted in Azure, but I don't believe its the one from the Marketplace.  Would have to check with another team if you think it might be important.

**Comment by bbgobie** [comment]
I've scaled down all our deployments in the cluster with these troublesome mounts and it seems the csi-smb-node pods continue to log messages like this.  The pods on nodes without issue stop logging after the deployments are scaled down.

`I0622 15:01:32.579166       1 utils.go:118] GRPC call: /csi.v1.Node/NodeUnstageVolume
I0622 15:01:32.579188       1 utils.go:119] GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-userstorage-core-prf-02/globalmount","volume_id":"pv-smb-csi-userstorage-core-prf-02"}
E0622 15:01:32.579944       1 utils.go:123] GRPC error: rpc error: code = Aborted desc = An operation with the given Volume ID pv-smb-csi-userstorage-core-prf-02 already exists`

**Comment by bbgobie** [comment]
If we manually reboot a machine that has the mounting issues, it goes into a reboot loop.  It will reboot roughly every 35 mins.  A hard reboot.  That's a pretty long story but from all data we've gathered on that subject it seems the hypervisor triggers the reboot and the AKS node is unaware its going to happen.

**Comment by bbgobie** [comment]
Deleted last 2 comments because we had an error while testing today.  So any data from today is not valid.

**Comment by andyzhangx** [comment]
can you try `mount -t cifs -o vers=3.0,dir_mode=0777,file_mode=0777,uid=100,gid=101,domain=, ///akstransientpf02 xxx` on the node in problem to check why mount command stuck there forever?

**Comment by bbgobie** [comment]
Sorry, we don't have a reliable reproduction.  Some pods have just started failing.

Pod events show messages like this.

`   Warning  FailedMount       2m49s (x2 over 3m37s)  kubelet            MountVolume.MountDevice failed for volume "pv-smb-csi-mds3-core-dvsh-01-csi-1" : kubernetes.io/csi: attacher.MountDevice failed to create dir "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-mds3-core-dvsh-01-csi-1/globalmount":  mkdir /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-mds3-core-dvsh-01-csi-1/globalmount: file exists
  Warning  FailedMount       79s                    kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[smb-mds-volume smb-help-volume smb-pccwebsite-volume smb-mds3-volume], unattached volumes=[smb-mds-volume smb-userstorage-volume pcc-webwebappsrootweb-infclassesconfigweloggerproperties pcc-web-certscacerts deployment-configs mklinks-script default-token-vh4hb pcc-webwebappsrootweb-infschedulercontextxml default-configs smb-help-volume smb-pccwebsite-volume smb-mds3-volume]: timed out waiting for the condition`

The folder on the host node seems in a weird state
`root@aks-hydracsi-16862694-vmss000003:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-mds-core-dvsh-01-csi-1# ls -al
ls: cannot access 'globalmount': No such file or directory
total 12
drwxr-x--- 3 root root 4096 Jun 23 17:50 .
drwxr-x--- 7 root root 4096 Jun 23 17:50 ..
d????????? ? ?    ?       ?            ? globalmount
-rw-r--r-- 1 root root   83 Jun 24 13:21 vol_data.json`

Interestingly, I'm able to manually mount

`mount -t cifs //<share_path> -o vers=3.0,dir_mode=0777,file_mode=0777,uid=100,gid=101,credentials=/tmp/smb_creds /tmp/mike
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)`

Removing the dir_mode lets me mount it
`mount -t cifs //<share_path> -o vers=3.0,file_mode=0777,uid=100,gid=101,credentials=/tmp/smb_creds /tmp/mike`

**Comment by andyzhangx** [comment]
the dir `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-mds3-core-dvsh-01-csi-1/globalmount` should have been mounted before, and there is failure in unmount in driver, if you could remove `file_mode=0777` mount option in your storage class, does it work? This is interesting that removing `file_mode=0777` mount option would and then manually mount works,  I think there is some issue in your smb server side

**Comment by bbgobie** [comment]
Since the issue came up we haven't been able to duplicate it again. Closing for now

**Comment by bbgobie** [comment]
In todays case, mount command on this particular node hangs when connecting to our share.  We can see the mount commands in ps -aux.  Mount works from other nodes.  Hopefully this will be fixed by one of the kernel bugs identified.

**Comment by andyzhangx** [comment]
> In todays case, mount command on this particular node hangs when connecting to our share. We can see the mount commands in ps -aux. Mount works from other nodes. Hopefully this will be fixed by one of the kernel bugs identified.

there is already `wait.PollImmediate`, when mount hangs, it would be timeout after 2 minutes:
https://github.com/kubernetes-csi/csi-driver-smb/blob/29a07ac1edfaa180f5138fdf1f85fb0e162a0342/pkg/smb/nodeserver.go#L194-L198

**Comment by bbgobie** [comment]
Sorry, I didn't check to see how old those mount commands were.  Just that under normal circumstances when mounting is working we wouldn't see the command in ps. 
When I manually tried to mount the volume and it hung I just gave up after 10-15 seconds because that would be a very abnormal amount of time for us to mount a volume.

**Comment by bbgobie** [comment]
Just want to double check.
Does the plugin mount the share to  /var/lib/kubelet/plugins/kubernetes.io/csi/pv/<id>/globalmount only?
I see those mounts on the host vm, and also the same source mounted to 
/var/lib/kubelet/pods/<pod_id>/volumes/kubernetes.io~csi/<id>/mount

**Comment by bbgobie** [comment]
Just keeping this thread updated.  We have a nodepool with a bunch of Azure Linux Kernel 54.56 and am still running into issues mounting occasionally.  It seems as soon as a node has errors with a mount source, mounts to that source will no longer work on that node.

There seems to be a variety of errors that can come up.  Here's one which I think was the original reported.

`Warning  FailedMount       11m (x5 over 21m)    kubelet            MountVolume.MountDevice failed for volume "pv-smb-csi-pccwebsite-core-prf-01-1" : kubernetes.io/csi: attacher.MountDevice failed to create dir "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-pccwebsite-core-prf-01-1/globalmount":  mkdir /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-pccwebsite-core-prf-01-1/globalmount: file exists`
 
Folder on the host VM
`root@aks-kerbprf01d-14050897-vmss000001:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb-csi-mds3-core-prf-01-1# ls -al
ls: cannot access 'globalmount': No such file or directory
total 12
drwxr-x--- 3 root root 4096 Jul 14 18:27 .
drwxr-x--- 8 root root 4096 Jul 14 18:27 ..
d????????? ? ?    ?       ?            ? globalmount
-rw-r--r-- 1 root root   79 Jul 14 18:27 vol_data.json` 
  
Matching csi-smb-node error log
`E0715 12:40:42.164711       1 utils.go:123] GRPC error: rpc error: code = NotFound desc = path /var/lib/kubelet/pods/b5c548f2-6ca2-47b0-9857-26d2265e7a4a/volumes/kubernetes.io~csi/pv-smb-csi-pccwebsite-core-prf-01-1/mount does not exist`

**Comment by andyzhangx** [comment]
this PR may solve this issue: https://github.com/kubernetes-csi/csi-driver-smb/pull/322

**Comment by andyzhangx** [comment]
pls try latest release which has possible fix #322:
https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.2.0

**Comment by ahmetcetin** [comment]
hi @andyzhangx we have the same problem, randomly some pods cannot mount the volumes, after killing them they start to mount magically. it happens really randomly. we're using the latest version of the driver.

**Comment by andyzhangx** [comment]
> hi @andyzhangx we have the same problem, randomly some pods cannot mount the volumes, after killing them they start to mount magically. it happens really randomly. we're using the latest version of the driver.

@ahmetcetin could you paste the detailed mount error?

**Comment by ahmetcetin** [comment]
thank you for quick reply, at the moment it all pods worked again after removing them, but it happens quite frequently several times a day, as soon as I get the error again, I'll post the error here. when I check the pod events, it says it cannot mount the volume only. where can I get the detailed error message?

**Comment by andyzhangx** [comment]
> @andyzhangx thank you for quick reply, at the moment it all pods worked again after removing them, but it happens quite frequently several times a day, as soon as I get the error again, I'll post the error here. when I check the pod events, it says it cannot mount the volume only. where can I get the detailed error message?

@ahmetcetin follow guide here to get mount error logs: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by bbgobie** [comment]
@ahmetcetin After quite a bit of investigation, this turned out to be an issue with the Linux kernel. 
Some symptoms that could manifest.
1. Unable to manually mount shares
2. Shares that were already mounted on the vm were inaccessible.

I believe the fixes for us were:
1. Ensure you do not mount sub folders of 2 mounts on same vm.
  Eg. <some_share>/dev/data -> /usr/mnts/data and <some_share>/dev/ -> usr/mnts/dev

Also upgrading Linux kernels helped. AKS team was able to help identify some kernel patches that were included with AKS VM images.  Can't remember the exact versions, but make sure your nodes are up to date.

**Comment by andyzhangx** [comment]
thanks for the reply, close this issue
