### ISSUE TITLE
 Unable to attach or mount volumes using any version of csi-driver-smb

### ISSUE THREAD

**Issue by rmogalipuvvu** [kubernetes-csi/csi-driver-smb#316]
**What happened**:
Objective:
Trying to install csi-smb-driver in our aks cluster and and mount DFS folder to access pods from AKS pods.

Able to install and followed the instructions from here including troubleshooting however it ends up here with following error.

 Warning  FailedMount  14m (x36 over 6h26m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[smb], unattached volumes=
[default-token-hwdnr smb]: timed out waiting for the condition
  Warning  FailedMount  9m19s (x190 over 6h39m)  kubelet  MountVolume.MountDevice failed for volume "csi-pv" : rpc error: code = Internal  desc = volume(csi-pv-share) mount "/mycompany.net/company-dir/Data/Public/Test-Share" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/csi-pv/globalmount" failed with mount failed: exit status 32
Mounting command: mountMounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,vers=3.0,<masked>  /mycompany.net/company-dir/Data/Public/Test-Share /var/lib/kubelet/plugins/kubernetes.io/csi/pv/csi-pv/globalmount
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)  Warning  FailedMount  3m30s (x139 over 6h37m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[smb], unattached volumes=
[smb default-token-hwdnr]: timed out waiting for the condition

**What you expected to happen**:

**How to reproduce it**:
Am able to replicate with the latest example from here which is relatively newer.

**Anything else we need to know?**:

Tried multiple versions including the latest.

root@aks-system-17439133-vmss000001:/var/lib/kubelet/plugins# ls 
kubernetes.io  smb.csi.k8s.io

root@aks-system-17439133-vmss000001:/var/lib/kubelet/plugins# cd kubernetes.io/
root@aks-system-17439133-vmss000001:/var/lib/kubelet/plugins/kubernetes.io/csi# ls
pv
root@aks-system-17439133-vmss000001:/var/lib/kubelet/plugins/kubernetes.io/csi/p
v# ls -rtl
total 0

**Environment**:
- CSI Driver version:    image: mcr.microsoft.com/k8s/csi/smb-csi:latest
- Kubernetes version (use `kubectl version`): 1.20.5
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:

** here is my pv which I modified from the one here **
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: smb.csi.k8s.io
    volumeAttributes:
      source: "//mycompany.net/company-dir/Data/Public/Test-Share"
    volumeHandle: csi-pv-share
    nodeStageSecretRef:
      name: csi-credentials-temp
      namespace: devops
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

**Comment by andyzhangx** [comment]
does manually mount on the agent node works? follow: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

could be related to this issue: https://github.com/Azure/AKS/issues/2292

**Comment by zenbones** [comment]
We may be seeing the same problem https://github.com/kubernetes-csi/csi-driver-smb/issues/302 on EKS in AWS with kubernetes 1.19. We get the same error in any case.

**Comment by felixmw** [comment]
Same here
