### ISSUE TITLE
support generic ephemeral volume

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

could refer to https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html#example-of-inline-csi-pod-spec

**Describe alternatives you've considered**

**Additional context**

The minimum supported k8s version is 1.15

**Comment by dr0pdb** [comment]
/assign

@andyzhangx There are two features: [CSI ephemeral volumes](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/596-csi-inline-volumes) and [generic ephemeral volumes](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1698-generic-ephemeral-volumes). Which one are we targeting?

**Comment by andyzhangx** [comment]
> /assign
> 
> @andyzhangx There are two features: [CSI ephemeral volumes](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/596-csi-inline-volumes) and [generic ephemeral volumes](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1698-generic-ephemeral-volumes). Which one are we targeting?

@dr0pdb I mean `generic ephemeral volume`, it's still alpha(disabled by default) in 1.20, let's wait for beta first:
https://github.com/kubernetes/kubernetes/blob/d63dc87ae8b6d568785bd4c532fb16d99a6b7338/pkg/features/kube_features.go#L791

/hold

**Comment by dr0pdb** [comment]
sure.

/unassign
