### ISSUE TITLE
SMB Mapping being leaked prevents users from mounting a PV/PVS mapping to the same share.

### ISSUE THREAD

**Issue by manueltellez** [kubernetes-csi/csi-driver-smb#326]
https://github.com/kubernetes-csi/csi-driver-smb/blob/21b99d5f8082a422fb3383baec86eb31e436d4d7/pkg/mounter/safe_mounter_windows.go#L103

After deleting a PV/PVC/Deployment and trying to recreate it the mapping will fail with "Generic error". Removing the smb global mapping manually resolves the issue.

**Comment by andyzhangx** [comment]
are you hitting this error mentioned here: https://github.com/kubernetes-csi/csi-driver-smb/tree/master/deploy/example/windows#note ?

**Comment by andyzhangx** [comment]
details: https://github.com/kubernetes-csi/csi-driver-smb/issues/219#issuecomment-780287789
