### ISSUE TITLE
MountDevice failed for volume: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by yrro** [kubernetes-csi/csi-driver-smb#329]
**What happened**:

I've created a PV to access an SMB share, and a PVC has attached to it. Pods that use the PVC are stuck in `ContainerCreating`. `FailedMount` events are generated, containing the message:

```
MountVolume.MountDevice failed for volume "smb-myvol" : rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```

**What you expected to happen**:

The mount to succeed, of course! 😉 Failing that - an intelligible event message indicating wh the mount failed.

My guess is that the CSI driver is trying to generate a message telling me why the mount failed, but that message is somehow malformed. But I can't see any log messages from the CSI driver components nor from the k8s controller side of things that correlate.

**How to reproduce it**:

This one is tricky. I've used the CSI driver to mount 3-4 SMB shares without incident. I'm only able to reproduce it with this one exact file share.

And, here's the kicker... I need to make this file share accessible to workloads in two different namespaces. So I've actually created two PVs referring to it, with different mount options & credentials; and then a PVC in each namespace, bound to the PV.

And one of the PVCs is able to mount perfectly fine, the other one fails with this error.

I'm unable to reproduce this with any other file shares. But I'll try anything you suggest.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v1.2.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5ab7b2b29e522ce9de5306e2c302b2b7aff6358c", GitTreeState:"clean", BuildDate:"2021-05-21T04:53:02Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d670f74", GitCommit:"d670f744c7507b1afebfa72ef3f79bf924ad5467", GitTreeState:"clean", BuildDate:"2021-05-21T13:35:23Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
```
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="46.82.202105291300-0"
VERSION_ID="4.6"
OPENSHIFT_VERSION="4.6"
RHEL_VERSION="8.2"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 46.82.202105291300-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.6"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.6"
OSTREE_VERSION='46.82.202105291300-0'
```
- Kernel (e.g. `uname -a`):
- `Linux mycluster-worker-h2wwg 4.18.0-193.51.1.el8_2.x86_64 #1 SMP Thu Apr 8 13:59:36 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `oc apply -f *.yaml`

**Comment by andyzhangx** [comment]
does your pv name contains invalid string?

**Comment by yrro** [comment]
I don't think so...

The PV name (anonymised somewhat) that causes this error is: `smb-filexxx23-sharename-k8snamespace`

The PV name that I'm able to mount without a problem is: `smb-filexxx23-sharename-blah` - so the names are very similar - just that one is a bit longer than the other.

I can provide exact details, YAML object dumps, etc via email if it's helpful.

**Comment by sacesare** [comment]
Sorry, in my case it was "Secret" encoding issue, I've used "data", instead of "stringData". After changing to "stringData" all work as expected.

**Comment by steveizzle** [comment]
Got exactly the same behavior with the same use case.. Could you solve it?

> I don't think so...
> 
> The PV name (anonymised somewhat) that causes this error is: `smb-filexxx23-sharename-k8snamespace`
> 
> The PV name that I'm able to mount without a problem is: `smb-filexxx23-sharename-blah` - so the names are very similar - just that one is a bit longer than the other.
> 
> I can provide exact details, YAML object dumps, etc via email if it's helpful.

**Comment by steveizzle** [comment]
> Got exactly the same behavior with the same use case.. Could you solve it?
> 
> > I don't think so...
> > The PV name (anonymised somewhat) that causes this error is: `smb-filexxx23-sharename-k8snamespace`
> > The PV name that I'm able to mount without a problem is: `smb-filexxx23-sharename-blah` - so the names are very similar - just that one is a bit longer than the other.
> > I can provide exact details, YAML object dumps, etc via email if it's helpful.

forget about that. was also caused by an error in creating the secret

**Comment by j-coll** [comment]
Same here...
As @yrro was pointing, shouldn't this be throwing a nicer/intelligible error message?
