### ISSUE TITLE
Fetch credentials/domain from `volumeContext` parameters for mounting volumes

### ISSUE THREAD

**Issue by nixpanic** [kubernetes-csi/csi-driver-smb#340]
**Is your feature request related to a problem?/Why is this needed**
Dynamic provisioning of SMB volumes would create dedicated credentials per volume. In Kubernetes the credentials are fetched from the Secret that is linked in the StorageClass, and these credentials are used for all volumes created by the StorageClass.

It would be great to have the ability to place credentials in the `volumeContext` like `source` as described here https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md#pvpvc-usage

**Describe the solution you'd like in detail**
For dynamic provisioning of SMB volumes with credentials (username/password/domain) per volume, the csi-driver-smb should be able to fetch credentials per volume as well.

**Describe alternatives you've considered**
container-storage-interface/spec#466 talks about having a _secrets_ like `volumeContext`. This however may not make much progress, and there are recommendations to place credentials (encrypted) in the `volumeContext`. Eventhough this is less secure, it might be sufficient for (Kubernetes) environments where a normal user can not access the PersistenVolume details.

**Additional context**
I'd like to use this feature in the work-slowly-in-progress [samba-in-kubernetes/csi-provisioner-smb](https://github.com/samba-in-kubernetes/csi-provisioner-smb) project.

**Comment by andyzhangx** [comment]
Hi @nixpanic 
credentials are already stored in `nodeStageSecretRef`:
https://github.com/kubernetes-csi/csi-driver-smb/blob/15c72c6c98087ed5b91b000e1db8caaca6acc290/deploy/example/pv-smb.yaml#L22-L24

follow guide here: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#option2-pvpvc-usage

`For dynamic provisioning of SMB volumes`, actually this driver would create sub dir under same smb server, they they are using same credentials in storage class. After `dynamic provisioning`, secret name should be passed to `nodeStageSecretRef` in PV. Is that what you want?

**Comment by nixpanic** [comment]
Thanks for the reply!

But no, this is not what I want:

> `For dynamic provisioning of SMB volumes`, actually this driver would create sub dir under same smb server, they they are using same credentials in storage class. After `dynamic provisioning`, secret name should be passed to `nodeStageSecretRef` in PV. Is that what you want?

We would like to implement a provisioner that creates a new Samba service and share per requested volume. This service should then only be accessible by providing credentials for the particular share. The difference is that in a multi-tenant environment, different tenants should not have shared credentials to access shares.

This [Samba Operator](https://github.com/samba-in-kubernetes/samba-operator) can be used by a provisioner to create a new Samba service easily. It supports different security contexts, and a tenant (or Namespace in Kubernetes) can have unique credentials.

**Comment by andyzhangx** [comment]
hi @nixpanic we cannot store credentials as plain text in PV config, that would be a security issue, credentials can only be stored as k8s secret.

**Comment by nixpanic** [comment]
> hi @nixpanic we cannot store credentials as plain text in PV config, that would be a security issue, credentials can only be stored as k8s secret.

Yes, that makes sense to me. However container-storage-interface/spec#466 suggests it as an alternative.

Unfortunately the `nodeStageSecretRef` for the credentials gets filled by Kubernetes and contains the values from the StorageClass. In the project that we're working on, this is not usable.

Would it be acceptable to add `credentialsSecretRef` (or some other name) as part of the `volumeAttributes` as documented in https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md#pvpvc-usage ? Referencing secrets in a CSI `volumeAttributes` is not very clean, but would work for Kubernetes deployments (will require csi-driver-smb to use the k8s API, or the API from other COs to get the credentials).

**Comment by andyzhangx** [comment]
@nixpanic if you define a PV by yourself, you could add any field under `volumeAttributes`, smb csi driver won't block that.

**Comment by nixpanic** [comment]
> @nixpanic if you define a PV by yourself, you could add any field under `volumeAttributes`, smb csi driver won't block that.

Of course, but that would not work together with dynamic provisioning through a StorageClass :disappointed:

**Comment by andyzhangx** [comment]
@nixpanic you could pass the new parameter in `CreateVolume` func, while how would you get the credential(or secret name) in `CreateVolume` func?

https://github.com/kubernetes-csi/csi-driver-smb/blob/37d69ccf15d6479f54a8fd9a017c474b86626266/pkg/smb/controllerserver.go#L60-L113
