### ISSUE TITLE
[feature request] CSI SMB Volume Expansion

### ISSUE THREAD

**Issue by san360** [kubernetes-csi/csi-driver-smb#347]
**Tried to expand allocated PVC by editing capacity**:

**Update the PVC and underlying PV**:

**Create a PVC via YAML and redeploy the PVC after updating the capacity**:

**Environment**:
- CSI Driver version: 1.20
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g. from /etc/os-release): Linux, Ubuntu

**Comment by andyzhangx** [comment]
it's not supported yet, implement a dummy volume expansion may solve this issue. This SMB driver actually does not manage volume capacity actually, does a dummy volume expansion work for you?

**Comment by winromulus** [comment]
@andyzhangx what do you mean by a dummy expansion and how would that be achieved?

**Comment by andyzhangx** [comment]
> @andyzhangx what do you mean by a dummy expansion and how would that be achieved?

@andyzhangx this driver could not expand the real volume size, if you input a larger volume size, this driver would just return success, that's called dummy expansion, not sure whether it's reasonable for such behavior.

**Comment by joymon** [comment]
Does this mean if I give 100 Gi capacity in PV and 10Gi PVC storage, I can store more than that if the underlying SMB server has storage?
Below is the way we are giving the storage size.
    storage: 100Gi

Is this setting required to use the driver or just leave it empty to have all the storage on SMB server be used?

**Comment by andyzhangx** [comment]
> Does this mean if I give 100 Gi capacity in PV and 10Gi PVC storage, I can store more than that if the underlying SMB server has storage? Below is the way we are giving the storage size. storage: 100Gi
> 
> Is this setting required to use the driver or just leave it empty to have all the storage on SMB server be used?

@joymon the pvc capacity does not enforce the actual data size, it's only for pv/pvc matching.

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-csi/csi-driver-smb/pull/881
