### ISSUE TITLE
PVC quota

### ISSUE THREAD

**Issue by san360** [kubernetes-csi/csi-driver-smb#348]
**Created a PVC with 2 GB and was able to create files in the mounted volume of 5GB**:

**Unable to use storage more than 2 GB**:

**Exec into Pod with mounted volume and create binary files more than 2 GB**:

**Environment**:
- CSI Driver version: 1.20
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g. from /etc/os-release): Linux Ubuntu

**Comment by andyzhangx** [comment]
it's not supported since `CreateVolume` just creates a new directory under smb server
