### ISSUE TITLE
[feature request] Volume Snapshot Support

### ISSUE THREAD

**Issue by kferrone** [kubernetes-csi/csi-driver-smb#356]
**Is your feature request related to a problem?/Why is this needed**
No snapshots. 

**Describe the solution you'd like in detail**
Integrate with the core kubernetes snapshots.
https://kubernetes.io/docs/concepts/storage/volume-snapshots/

**Describe alternatives you've considered**
Valero advertised it can snapshot anything using the CSI driver, feature says coming soon for a very long time. 
Otherwise I need to make a job which can copy the dir to a backup folder and call it a snapshot.

**Comment by kferrone** [comment]
I see, that's a bummer. I have been researching and all I come across is something called `shadow copies`. Bummer, I guess it's not possible.

**Comment by julianortlieb** [comment]
Are here any updates?
