### ISSUE TITLE
SMB driver can't mount a certain mount 

### ISSUE THREAD

**Issue by kettlereve** [kubernetes-csi/csi-driver-smb#358]
Hello,

We are trying to mount a certain share ( that works on an a node level wonderfully )  but we are receiving some errors. 

MountVolume.MountDevice failed for volume "ad-scenario-testing-cb-test-cifs2-pv" : rpc error: code = Internal desc = volume(ad-scenario-testing-cb-test-cifs) mount "//frd-ces..com/frd/" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount" failed with mount failed: exit status 32 Mounting command: mount Mounting arguments: -t cifs -o vers=3.0,file_mode=0777,dir_mode=0777,domain=emea.zf-world.com,<masked> //frd-ces..com/frd/ /var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount Output: mount error(22): Invalid argument Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) 

The same command with the above arguments works nicely on the node level. 

Checking the pod that is present on the node we can see: 

Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
I0929 13:06:49.656406       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0929 13:06:49.656482       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["vers=3.0","file_mode=0777","dir_mode=0777"]}},"access_mode":{"mode":5}},"volume_context":{"source":"//frd-ces..com/frd/"},"volume_id":"ad-scenario-testing-cb-test-cifs"}
I0929 13:06:49.656715       1 nodeserver.go:180] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount) volumeID(ad-scenario-testing-cb-test-cifs) context(map[source://frd-ces..com/frd/]) mountflags([vers=3.0 file_mode=0777 dir_mode=0777]) mountOptions([vers=3.0 file_mode=0777 dir_mode=0777 ])
I0929 13:06:49.656764       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o vers=3.0,file_mode=0777,dir_mode=0777, <masked> //frd-ces..com/frd/ /var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount)
E0929 13:06:49.673384       1 mount_linux.go:179] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o vers=3.0,file_mode=0777,dir_mode=0777,<masked> //frd-ces..com/frd/ /var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount
Output: mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

E0929 13:06:49.673437       1 utils.go:123] GRPC error: rpc error: code = Internal desc = volume(ad-scenario-testing-cb-test-cifs) mount "//frd-ces..com/frd/" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/ad-scenario-testing-cb-test-cifs2-pv/globalmount" failed with mount failed: exit status 32

On Node level in the dmesg the following error occur ( when the pod tries to mount, as I said manually it works nicely ).
[754076.775291] CIFS: Attempting to mount  //frd-ces..com/frd/ 
[754076.783621] CIFS: Unknown mount option "tWK"

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"ffd68360997854d442e2ad2f40b099f5198b6471", GitTreeState:"clean", BuildDate:"2020-11-18T13:35:49Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+4c3480d", GitCommit:"4c3480dcd4299c3b3e9a75e28d643177600e7d72", GitTreeState:"clean", BuildDate:"2021-07-09T00:02:08Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

This is a customer used cluster so any help would be greatly appreciated.

**Comment by andyzhangx** [comment]
why there is `Unknown mount option "tWK"` error?

**Comment by kettlereve** [comment]
Hello Andy,

I have no idea, I've googled it a bunch of times and tried to find anything related to it but nothing comes up. I have no data on that message.

**Comment by kettlereve** [comment]
Anyone has any ideas on this? I've tried debugging it but nothing really sheds any light on it. 

Thank you

**Comment by kettlereve** [comment]
Hello Andy,

Just fyi I found out what the problem is. 

The RNG password had special characters in it, as in: + - , .               at some point the password looked like  adasdas,asdadas    <-- look at the comma.  I think the comma delimits that a new parameter is added . The new parameter would be: asdadas     

So that message TWK is because we had in the password  ",TWK,"    

In the end the solution is: 

Special characters such as $, \, *, =, and ! will be interpreted by your shell and require escaping. In most shells, the easiest way to escape the password is to surround it with single quotes ('). For example, if your actual password is S!B\*d$zDsb=, you should execute the command this way:

**Comment by kettlereve** [comment]
It does not work :) need to change the password and remove the " , "
