### ISSUE TITLE
Windows node GRPC error: rpc error: code = Internal desc = failed to stat file 

### ISSUE THREAD

**Issue by kobi-toptal** [kubernetes-csi/csi-driver-smb#360]
On windows server 2019 csi-smb-node-win periodically logs the following errors:
```
smb E1008 12:13:23.617441 4860 utils.go:123] GRPC error: rpc error: code = Internal desc = failed to stat file 
c:\var\lib\kubelet\pods\41c110a6-e29f-481f-90c5-c7841628f0bd\volumes\kubernetes.io~csi\pvc-768e288f-595f-4c4d-83bf-
e55f00e81c00\mount: CreateFile c:\var\lib\kubelet\pods\41c110a6-e29f-481f-90c5c7841628f0bd\volumes\kubernetes.io~csi\pvc-
768e288f-595f-4c4d-83bf-e55f00e81c00\mount: Access is denied.
```

**What happened**:
SMB share is mounted properly and storage I/O works. Also PV/PVC removal work fine. But above error is logged periodically.

**What you expected to happen**:
The specified directory in log output is created at container deployment step, this log ambiguous. No information in docs if it is critical or how to fix it.

**How to reproduce it**:
On windows server 2019 host install csi-proxy v0.2.2 or above, deploy  csi driver v1.2.0

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v1.2.0
- Kubernetes version (use `kubectl version`): v1.21.2
- OS (e.g. from /etc/os-release): windows server 2019
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could you provide more complete logs? provide more detailed logs would help, thanks.
From the logs, it looks like pod(`41c110a6-e29f-481f-90c5c7841628f0bd`) cannot access `pvc-
768e288f-595f-4c4d-83bf-e55f00e81c00`

**Comment by andyzhangx** [comment]
errro returned here, we may use `os.Lstat` instead of `os.Stat` for this driver
https://github.com/kubernetes-csi/csi-driver-smb/blob/d298cb856d8c9c213f95f5a49991df0e93b01779/pkg/smb/nodeserver.go#L259-L264

```
// Stat returns a FileInfo describing the named file.
// If there is an error, it will be of type *PathError.
func Stat(name string) (FileInfo, error) {
	testlog.Stat(name)
	return statNolog(name)
}

// Lstat returns a FileInfo describing the named file.
// If the file is a symbolic link, the returned FileInfo
// describes the symbolic link. Lstat makes no attempt to follow the link.
// If there is an error, it will be of type *PathError.
func Lstat(name string) (FileInfo, error) {
	testlog.Stat(name)
	return lstatNolog(name)
}
```

**Comment by kobi-toptal** [comment]
error is returned from csi-driver-smb/pkg/smb/nodeserver.go, i was not able to trace back what calls it and how critical is it, can i ignore it in production?

**Comment by andyzhangx** [comment]
@kobi-toptal I think you could ignore the error, and I also worked out a PR to fix this issue.

**Comment by andyzhangx** [comment]
could you try latest version `mcr.microsoft.com/k8s/csi/smb-csi:latest` to verify? thanks.
