### ISSUE TITLE
Error getting server version

### ISSUE THREAD

**Issue by vchorny** [kubernetes-csi/csi-driver-smb#373]
logs from failed pod container
kubectl logs csi-smb-controller-xxxxxxxxx -c csi-provisioner --previous

I1102 11:20:34.679700       1 feature_gate.go:243] feature gates: &{map[]}
I1102 11:20:34.679819       1 csi-provisioner.go:138] Version: v2.2.2
I1102 11:20:34.679842       1 csi-provisioner.go:161] Building kube configs for running in cluster...
F1102 11:20:34.772992       1 csi-provisioner.go:186] Error getting server version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: connect: connection refused
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0000e8000, 0xb9, 0x1b0)
        /workspace/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x29af7c0, 0xc000000003, 0x0, 0x0, 0xc00027b9d0, 0x21e59ce, 0x12, 0xba, 0x0)
        /workspace/vendor/k8s.io/klog/v2/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x29af7c0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1be7f6b, 0x20, 0xc000288330, 0x1, ...)
        /workspace/vendor/k8s.io/klog/v2/klog.go:751 +0x191
k8s.io/klog/v2.Fatalf(...)
        /workspace/vendor/k8s.io/klog/v2/klog.go:1509
main.main()
        /workspace/cmd/csi-provisioner/csi-provisioner.go:186 +0xa94

goroutine 5 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x29af7c0)
        /workspace/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /workspace/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

**Comment by andyzhangx** [comment]
that's expected when api-server could not be reached from your csi driver controller

**Comment by vchorny** [comment]
Hi,
Can this error be wrapped by proper error message that explain what happens, like in explanation below.

Thanks

**Comment by andyzhangx** [comment]
I think you could file an issue in https://github.com/kubernetes-csi/external-provisioner
