### ISSUE TITLE
Domain is not properly parametrized

### ISSUE THREAD

**Issue by gabriel-stan** [kubernetes-csi/csi-driver-smb#39]
**What happened:**
Mount options are not correctly set up when **domain** is added in the secrets, causing a mount error and the container fails to start. Also, credentials are exposed in the Kubernetes event log.

**What you expected to happen:**
Volume mounting and container starting.

**How to reproduce it:**
add **domain** to the secrets according to https://github.com/kubernetes-csi/csi-driver-smb/blob/v0.1.0/deploy/example/e2e_usage.md:
`kubectl create secret generic smbcreds --from-literal username=testuser --from-literal password="testpassword" --from-literal domain=testdomain` 

On pod creation, pod is stuck in **Init:0/1** state.
Output of `kubectl describe`

```
Warning  FailedMount  1s    kubelet, aks-nodepool-XXXXXX  MountVolume.MountDevice failed for volume "pv-smb" : rpc error: code = Internal desc = volume(unique-volumeid) mount "//XXXXXX/test" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,username=testuser,password=testpassword,vers=3.0,testdomain //XXXXXX/test /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount
Output: mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

Note how `testdomain` is just added at the end without the proper `domain=` parameter

**Anything else we need to know?:**

Possible fix:

I suppose the issue is here: https://github.com/kubernetes-csi/csi-driver-smb/blob/1afa2fa57f9756bb36be3c3463b5492087875ac4/pkg/smb/nodeserver.go#L179
and it's missing the string formatting. Solution would be something like
```
	if domain != "" {
		options := []string{fmt.Sprintf("domain=%s", domain)}
		mountOptions = append(mountOptions, options)
	}
```
I am not aware if there are other implications or other modifications & more testing needed, otherwise I would have created a PR.

Also note that the same setup works properly with a local machine user instead of a domain user, thus ommiting the `domain` parameter.

Environment:

* CSI Driver version: v1.0.1 release and master @ 1afa2fa57f9756bb36be3c3463b5492087875ac4
* Kubernetes version (use kubectl version): 1.15
* OS (e.g. from /etc/os-release):
* Kernel (e.g. uname -a):
* Install tools:
* Others:

EDIT:

Using Linux container.

**Comment by andyzhangx** [comment]
this issue is fixed by https://github.com/kubernetes-csi/csi-driver-smb/pull/41
and password logging issue is fixed by https://github.com/kubernetes-csi/csi-driver-smb/pull/40

**Comment by gabriel-stan** [comment]
thanks for the quick reaction! will use with the next release :1st_place_medal:
