### ISSUE TITLE
csi-smb-controller-xxxxxxxxxx-yyyy works on worker nodes

### ISSUE THREAD

**Issue by ch0mik** [kubernetes-csi/csi-driver-smb#390]
please change the the deployment that the csi-smb-controller-xxxxxxxxxx-yyyy plase only on master nodes

with Regards
Pawel

**Comment by andyzhangx** [comment]
currently can csi-smb-controller run on both master and agent nodes, and there is `controller.nodeSelector` and `controller.affinity` to control which node it could run:

https://github.com/kubernetes-csi/csi-driver-smb/blob/bbf67af1dbdab1204ccdc735946e833df3738a3a/charts/latest/csi-driver-smb/values.yaml#L64-L72

**Comment by ch0mik** [comment]
Thanks Andy!

IMO its should be out-of-the-box in next version - the controllers should only work with masters.

Regards
Pawel

**Comment by andyzhangx** [comment]
> Thanks Andy!
> 
> IMO its should be out-of-the-box in next version - the controllers should only work with masters.
> 
> Regards Pawel

@ch0mik why the controllers should only work with masters, the smb driver controller also needs mount remote file share, so as long as the connection with remove smb file share is ok, it should work no matter controller is on master or agent node.

**Comment by ch0mik** [comment]
thanks!
