### ISSUE TITLE
Supported SMB Versions ?

### ISSUE THREAD

**Issue by erSitzt** [kubernetes-csi/csi-driver-smb#393]
Hi,

what are the currently supported smb versions ?
I didnt find any info...

**Comment by andyzhangx** [comment]
it's smb 2.1, 3.0, 3.1

**Comment by mcaupybugs** [comment]
Any update to the SMB version supported ?

**Comment by andyzhangx** [comment]
the version support depends on the kernel version on the node, does not depend on this csi driver. as long as the version is supported by the node, the csi driver would also work with that version.
