### ISSUE TITLE
Does not support armv7

### ISSUE THREAD

**Issue by fidesachates** [kubernetes-csi/csi-driver-smb#405]
**What happened**:
Followed the README and used the install script for master and expected it to work on my kubernetes cluster that's running on pi's. 

**What you expected to happen**:
For the controller csi pods to come up without issues. 

**How to reproduce it**:
Run `curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/deploy/install-driver.sh | bash -s master --` on a cluster that's on pi's

**Anything else we need to know?**:
It seems csi-provisioner is the image that's having trouble being pulled because 2.2.2 doesn't support armv7

**Environment**:
- CSI Driver version: master
- Kubernetes version (use `kubectl version`): 1.21
- OS (e.g. from /etc/os-release): Raspbian GNU/Linux 10 (buster)
- Kernel (e.g. `uname -a`):Linux 5.4.51-v7l+ armv7l GNU/Linuxd
- Install tools: kubectl
- Others:

Can we get some documentation to denote this? [Related issue.](https://github.com/kubernetes-csi/external-provisioner/issues/new)

**Comment by andyzhangx** [comment]
even controller is not applicable now, you could still use static provisioning(PV/PVC way), could you try that: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#option2-pvpvc-usage
