### ISSUE TITLE
CIFS mount failing with spaces in network path

### ISSUE THREAD

**Issue by venbcbs** [kubernetes-csi/csi-driver-smb#416]
Hello Team,

CIFS Share mounting on to a pod is failing while the CIFS Network Path is having spaces in it.

We had this issue in Openshift 3.11 as well. Pods could not mount the CIFS network path with Spaces in it. 
In Openshift 3.11 we were able to fix this by adding the double codes around network path and other attributes in the flex driver file. But in 4.x, CIFS is enabled by the daemonset. We are not sure here how to fix this. I have checked the Daemonset manifest file but could not find a proper key value pair to add the double codes. So, please let us know how to fix this. How to make the pods mount the CIFS share whose network path has spaces in it. 

Docs used to install the CIFS capability:

Openshift 3.11-  https://cloud.redhat.com/blog/mounting-cifs-shares-in-openshift
Openshift 4.x- https://cloud.redhat.com/blog/cifs-and-openshift-using-the-container-storage-interface-1

Here is how we fixed the openshift 3.11 issue by adding the double codes:

    NETWORK_PATH=$(parse_json "networkPath" "$JSON")

       if [ ! -n "$NETWORK_PATH" ]; then
       errorExit "Network path Is not Found"
    fi

    MOUNT_OPTIONS=$(parse_json "mountOptions" "$JSON")
    READ_WRITE_MODE=$(parse_json "kubernetes.io/readwrite" "$JSON")
    USERNAME=$(parse_json "kubernetes.io/secret/username" "$JSON" | base64 -d)
    PASSWORD=$(parse_json "kubernetes.io/secret/password" "$JSON" | base64 -d)
    DOMAIN=$(parse_json "kubernetes.io/secret/domain" "$JSON"| base64 -d)

**Comment by andyzhangx** [comment]
would you just add space in `source` field, I think it should work with this driver:
https://github.com/kubernetes-csi/csi-driver-smb/blob/4da71f982a8cadfedc9267bb409bea2a291cb1fe/deploy/example/storageclass-smb.yaml#L7-L9
