### ISSUE TITLE
NewSmbGlobalMapping failed when using containerd

### ISSUE THREAD

**Issue by liyanhui1228** [kubernetes-csi/csi-driver-smb#432]
**What happened**: SMB volume mount failed for statefulset pod when using containerd, pod cannot startup.

**What you expected to happen**: volume mount should be successful.

**How to reproduce it**: Follow https://github.com/kubernetes-csi/csi-driver-smb/tree/master/deploy/example/windows with containerd as the container runtime on windows nodes.

It worked fine when using docker, just not working when using containerd.

**Anything else we need to know?**:

The error from the pending busybox pod:

```
Warning  FailedMount       4m1s               kubelet            Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[kube-api-access-z4lsv persistent-storage]: timed out waiting for the condition
  Warning  FailedMount       106s               kubelet            Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage kube-api-access-z4lsv]: timed out waiting for the condition
  Warning  FailedMount       80s (x10 over 6m)  kubelet            MountVolume.MountDevice failed for volume "pvc-d98555d5-d4a3-4bf4-8e30-bb0e90756126" : rpc error: code = Internal desc = volume(smb-server.default.svc.cluster.local/share#pvc-d98555d5-d4a3-4bf4-8e30-bb0e90756126#) mount "//smb-server.default.svc.cluster.local/share/pvc-d98555d5-d4a3-4bf4-8e30-bb0e90756126" on "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-d98555d5-d4a3-4bf4-8e30-bb0e90756126\\globalmount" failed with smb mapping failed with error: rpc error: code = Unknown desc = NewSmbGlobalMapping failed. output: "New-SmbGlobalMapping : The user name or password is incorrect. \r\nAt line:1 char:190\r\n+ ... ser, $PWord;New-SmbGlobalMapping -RemotePath $Env:smbremotepath -Cred ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : AuthenticationError: (MSFT_SmbGlobalMapping:ROOT/Microsoft/...mbGlobalMapping) [New-SmbG \r\n   lobalMapping], CimException\r\n    + FullyQualifiedErrorId : Windows System Error 1326,New-SmbGlobalMapping\r\n \r\n", err: exit status 1
```

**Environment**:
- CSI Driver version: csi-provisioner:v2.2.2-gke.0, csi-node-driver-registrar:v2.3.0, smb-csi:latest
- Kubernetes version (use `kubectl version`): 1.22.6
- OS (e.g. from /etc/os-release): Windows Server 2019 LTSC Datacenter
- Kernel (e.g. `uname -a`): 10.0.17763.2114
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
this driver should work on windows containerd, we have a `pull-csi-driver-smb-e2e-windows-containerd` test on Azure:  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-smb/431/pull-csi-driver-smb-e2e-windows-containerd/1503991874367524864

The error is `The user name or password is incorrect`, could you check on your side?

**Comment by krzysztof-magosa** [comment]
@liyanhui1228 did you resolve it somehow? We hit same bug, provided credentials are 100% correct, we've verified them.
