### ISSUE TITLE
Force close on open smb-fileLock-handles and sessions

### ISSUE THREAD

**Issue by Zetanova** [kubernetes-csi/csi-driver-smb#49]
**Is your feature request related to a problem? Please describe.**
long period of locked file-handles and folders over a SMB share,
making a normal relocation of an k8s-pod painfull.

**Describe the solution you'd like in detail**
Forcefully close the last SMB connections to unlock the file-handles on the SMB-Server

**Additional context**
I used the flex-smb-driver and the main issue was not that most of the unix-server-apps 
did not support it well, like mongodb and sqlserver or where just slow like some java-apps
It was simply the long open file-handle-locks on part of the mounts.
It already could be locked *.pid file that prevented to restart of a pod for more then 30min.   

More then once was a manual force close required with:
`Get-SmbOpenFile  && Close-SmbOpenFile` or `Get-SmbSession && Close-SmbSession`

**Comment by andyzhangx** [comment]
@Zetanova sorry, I am not sure about the requirement, `Get-SmbOpenFile` is a powershell cmdlet, are you using this driver on Windows? And we have unmount on `NodeStageVolume`, do you mean we should add a flag to force close smb mount? what's the identical command on Linux?
https://github.com/kubernetes-csi/csi-driver-smb/blob/1a825f4aa4b1ab3a6b03db9800c59a2f05b1660e/pkg/smb/nodeserver.go#L217-L230

**Comment by Zetanova** [comment]
ks can kill the pod on OOM or Reschedule 
and after the file-share 'cifs' connection will still be open for the server.
A regular `umount /mnt/volumes/mymountpath` does not release the file-locks
and the server will do it after an timeout of ~30min or so.

**Comment by andyzhangx** [comment]
@Zetanova `Close-SmbOpenFile` is a server side operation, while this driver does not have a controller, it only operates on client side. Also not sure what's the identical command of `Get-SmbOpenFile && Close-SmbOpenFile or Get-SmbSession && Close-SmbSession` on Linux.

**Comment by Zetanova** [comment]
@andyzhangx I mentioned only the `Close-SmbOpenFile` pwsh-commands to underline 
that i only could resolve the issue server side. 

The stale file-lock handles are not even then main issue
The main issue is that the StageVolume succeed, but some files or folders could still be locked 
and can lead to very bad behavior of the Pod.
It would be better that StageVolume would fail, when Stale-FileLocks are oben on the share

**Comment by boddumanohar** [comment]
@andyzhangx @Zetanova I am see these logs in `csi-provisioner` container of `csi-smb-controller` pod. 

```
I1003 08:04:16.248235       1 leaderelection.go:350] lock is held by csi-smb-controller-8476694d7b-rnm2w and has not yet expired
I1003 08:04:16.248260       1 leaderelection.go:246] failed to acquire lease kube-system/smb-csi-k8s-io
I1003 08:04:26.060044       1 leaderelection.go:350] lock is held by csi-smb-controller-8476694d7b-rnm2w and has not yet expired
I1003 08:04:26.060080       1 leaderelection.go:246] failed to acquire lease kube-system/smb-csi-k8s-io
I1003 08:04:35.446131       1 leaderelection.go:350] lock is held by csi-smb-controller-8476694d7b-rnm2w and has not yet expired
I1003 08:04:35.446168       1 leaderelection.go:246] failed to acquire lease kube-system/smb-csi-k8s-io
I1003 08:04:41.548062       1 leaderelection.go:350] lock is held by csi-smb-controller-8476694d7b-rnm2w and has not yet expired
I1003 08:04:41.548099       1 leaderelection.go:246] failed to acquire lease kube-system/smb-csi-k8s-io
I1003 08:04:49.123951       1 leaderelection.go:350] lock is held by csi-smb-controller-8476694d7b-rnm2w and has not yet expired
I1003 08:04:49.123991       1 leaderelection.go:246] failed to acquire lease kube-system/smb-csi-k8s-io
```

Do we know why we see these logs? is the above issue related to these logs?

**Comment by Zetanova** [comment]
@Zetanova If the smb client terminates uncontrolled, the smb server will hold the session open and all its file-locks  till the timeout. 
The standard timeout is very high (view minutes)

**Comment by Zetanova** [comment]
@andyzhangx One of the problems is that kubernetes restarts/kills the pods faster then the smb-timeout

 I know/found only two solution to fix the situation of a "smb file-lock spiral"
* Scale the deployment down to 0 and wait until the smb-timeout happend until u scale it up again (around 15minutes).
* Scale down the deployment to 0, connect to the SMB-server and force-close the still open smb-sessions. Then scale it up again.

**Comment by Zetanova** [comment]
@andyzhangx   I would have an idea for a workaround to at least not get into an lock death spiral.

Just create a hidden-file or move the data into a subfolder and create a file in the root
This file can be locked be the node-controller.
If it fails then the NodeStageVolume request fails.

This would resolve the lock death spiral
The lock death spiral happens when a pod locks more then one file on the volume
Like a db-file and a pid-file

**Comment by Zetanova** [comment]
@andyzhangx Is the feature/issue resolved? 
If not I can make a demo container that will trigger the file-lock pod restart spiral

**Comment by andyzhangx** [comment]
> @andyzhangx Is the feature/issue resolved? If not I can make a demo container that will trigger the file-lock pod restart spiral

@Zetanova No, it's not resolved, do you have any idea how to fix it?

**Comment by Zetanova** [comment]
@andyzhangx  this idea would be one easy solution https://github.com/kubernetes-csi/csi-driver-smb/issues/49#issuecomment-770919688 

Option1:
to hide a file depends on the OS under linux 
the mount process could try to create and **lock** a file '.csi-lock'
If it fails to lock the file the mount should fail.
After the lock-timeout of the fileserver,  the '.csi-lock' will get unlocked by the fileserver
and and the next mount retry will succeed.
this would prevent the 'file-lock pod restart spiral'. 
Of course the pod would be offline for 5-15min but then be able to start,
else a lot of services would go into a never ending restart loop. Like `mssql`

Option2:
From the controller to PWSH/SSH into the fileserver and force unlock all locked files of the volume before mounting
Maybe there is some kind of command to do it directly over SMB, 
but I could not find one.

**Comment by Zetanova** [comment]
@andyzhangx Any plans to include this `.csi-lock` file feature? 

It could be implemented over a sidecar and init-container too.
If your diver will not support it, I could make a general one sidecar container for this feature.

I am still on one on-premise deployment on the legacy smb out-of-process driver and need to upgrade.

**Comment by andyzhangx** [comment]
> @andyzhangx Any plans to include this `.csi-lock` file feature?
> 
> It could be implemented over a sidecar and init-container too. If your diver will not support it, I could make a general one sidecar container for this feature.
> 
> I am still on one on-premise deployment on the legacy smb out-of-process driver and need to upgrade.

@Zetanova do you know whether `unmount -f volume-mount-path` would solve this issue, I am going to use force unmount soon since it's already supported in mount-utils: https://github.com/kubernetes/mount-utils/blob/v0.26.0/mount_linux.go#L384

**Comment by Zetanova** [comment]
@andyzhangx The unmount from a online node is not really the issue.  
There are basically two issues in the case of node failure:
1) The replacing pod on a different node **CAN** mount the volume and start the pod.
If files got locked then they are still locked until the old smb session times out. 
Because the replacing pod assumes that it has read/write rights, it can lead to bad behavior with some software,
2) If the pod requires two files to be locked to operate, it leads to a never ending circular death-lock
The replacing pod always can only lock 1 of 2 files and crashes. The situation that all smb sessions timing out never happen. I manual scale down to zero and waiting 10-15min after need to be done to resolve this issue.

A easy option to resolve this issue would be to let the csi-node-driver create a hidden `.csi-lock` file and try to lock it. 
If this fails try to create a `.csi-unlock`, wait+retry then fail,  
If the `.csi-lock` file lock is successful try to delete the `.csi-unlock` file and return mount-successful. 

The `.csi-unlock` file would allow a 3th party-script somewhere (server) to force close the old SMB-session from the offline node.
Without this 3th party-script a ~15min downtime of the POD would most likely happen. But no death-lock or strange runtime behavior
