### ISSUE TITLE
Can this driver connect to pre-existing SMB servers

### ISSUE THREAD

**Issue by bab5470** [kubernetes-csi/csi-driver-smb#501]
My impression is that this driver creates an SMB server and then can create subsequent filesystems and shares. I'd like to know if its possible for it to connect to a pre-existing share. 

We have pre-existing shares on a windows file server that we need to connect to from our pods. Is that possible from this CSI driver? 

If so are there any examples? I deployed the helm chart and it created a bunch of pods. I see a storage class in the repo but it looks like that might not be for connecting to pre-existing servers. 

Thanks,
Brad

**Comment by albertkohl-monotek** [comment]
@bab5470 did you ever get cis-dirver-smb to work with exisiting shares / data? i'm not totally following the examples on how to do that.
