### ISSUE TITLE
support passwords containing comma character

### ISSUE THREAD

**Issue by amather** [kubernetes-csi/csi-driver-smb#507]
**Is your feature request related to a problem?/Why is this needed**
Currently, at least on Linux, the CSI driver supplies the password as parameter to `mount` as part of other mount options. since these mount options are separated by comma, a password with comma doesn't work. 

from the man page:

```
password=arg
    specifies the CIFS password. If this option is not given then the environment variable PASSWD is used. 
    If the password is not specified directly or indirectly via an argument to mount, mount.cifs will prompt 
    for a password, unless the guest option is specified.

    Note that a password which contains the delimiter character (i.e. a comma ',') will fail to be parsed  
    correctly on the command line. However, the same password defined in the PASSWD environment variable 
    or via a credentials file (see below) or entered at the password prompt will be read correctly. 
```

Also, this caused issues in the past:
https://github.com/kubernetes-csi/csi-driver-smb/issues/358
https://github.com/kubernetes-csi/csi-driver-smb/issues/248

**Describe the solution you'd like in detail**
As the man page states, the password should either be provided via `PASSWD` env var or via credentials file.

**Describe alternatives you've considered**
Using a different password is our only option at the moment.

**Additional context**
We've had to ask the customer to change the password, because we use k8s and passwords with commas don't work there.....not good :(

**Comment by andyzhangx** [comment]
what about this solution: if password contains special char, then use `PASSWD` env var
