### ISSUE TITLE
v1.8.0 of smbplugin image is unavailable

### ISSUE THREAD

**Issue by LDL-GH** [kubernetes-csi/csi-driver-smb#514]
We tried upgrading our helm chart to the 1.8.0 release.
However we are unable to pull version v1.8.0 of the smbplugin image.
Below output of a manual pull on a server (and a pull of 1.7.0 showing expected behaviour):

[Tue Jul 05 09:09:19] user@server01 ~
 $ podman pull registry.k8s.io/sig-storage/smbplugin:v1.8.0
Trying to pull registry.k8s.io/sig-storage/smbplugin:v1.8.0...
  manifest unknown: Failed to fetch "v1.8.0" from request "/v2/sig-storage/smbplugin/manifests/v1.8.0".
Error: error pulling image "registry.k8s.io/sig-storage/smbplugin:v1.8.0": unable to pull registry.k8s.io/sig-storage/smbplugin:v1.8.0: unable to pull image: Error initializing source docker://registry.k8s.io/sig-storage/smbplugin:v1.8.0: Error reading manifest v1.8.0 in registry.k8s.io/sig-storage/smbplugin: manifest unknown: Failed to fetch "v1.8.0" from request "/v2/sig-storage/smbplugin/manifests/v1.8.0".

[Tue Jul 05 09:09:25] user@server01 ~
 $ podman pull registry.k8s.io/sig-storage/smbplugin:v1.7.0
Trying to pull registry.k8s.io/sig-storage/smbplugin:v1.7.0...
Getting image source signatures
Copying blob 1887edd64625 done
Copying blob 078d377bc761 done
Copying blob 1db67fb972b5 done
Copying config af3512c3c3 done
Writing manifest to image destination
Storing signatures
af3512c3c3f0a2e6a3fa7728963e1ce30e3a1083eae29883475c5a1b9d258d95

Can you take a look at this please?

**Comment by andyzhangx** [comment]
it depends on this PR: https://github.com/kubernetes/k8s.io/pull/3923, once that PR merged, it would be available.

**Comment by andyzhangx** [comment]
`registry.k8s.io/sig-storage/smbplugin:v1.8.0` is ready now
