### ISSUE TITLE
PV/PVC Randomly getting deleted

### ISSUE THREAD

**Issue by Stijn-Timmer** [kubernetes-csi/csi-driver-smb#515]
PV and PVC keeps getting deleted randomly?
```
I0705 08:59:38.386967       1 utils.go:83] GRPC response: {}
I0705 09:16:10.755083       1 utils.go:76] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0705 09:16:10.755126       1 utils.go:77] GRPC request: {"target_path":"/var/lib/kubelet/pods/f048f7a1-024e-4640-9510-e19c1c46de04/volumes/kubernetes.io~csi/pv-gesprekken/mount","volume_id":"pv-gesprekken"}
I0705 09:16:10.755198       1 nodeserver.go:100] NodeUnpublishVolume: unmounting volume pv-gesprekken on /var/lib/kubelet/pods/f048f7a1-024e-4640-9510-e19c1c46de04/volumes/kubernetes.io~csi/pv-gesprekken/mount
I0705 09:16:10.755212       1 mount_linux.go:294] Unmounting /var/lib/kubelet/pods/f048f7a1-024e-4640-9510-e19c1c46de04/volumes/kubernetes.io~csi/pv-gesprekken/mount
W0705 09:16:10.773782       1 mount_helper_common.go:133] Warning: "/var/lib/kubelet/pods/f048f7a1-024e-4640-9510-e19c1c46de04/volumes/kubernetes.io~csi/pv-gesprekken/mount" is not a mountpoint, deleting
```

**What happened**:
Pods randomly crash because the pv/pvc disappear without any error logs.
This did not happen before.
**What you expected to happen**:
The smb-driver not deleting pv/pvc randomly
**How to reproduce it**:
For me its applying the yaml waiting 15~ minutes, and watch the pods crash because the volumes are gone after set time

**Anything else we need to know?**:
Used the latest helm chart

**Environment**:
- CSI Driver version: csi-driver-smb:1.9.0
- Kubernetes version (use `kubectl version`): v1.21.12+k3s1
- OS (e.g. from /etc/os-release): Centos 7 
- Kernel (e.g. `uname -a`): 3.10.0-1160.62.1.el7.x86_64
- Install tools: helm
- Others: Using rancher and fleet to manage

**Comment by andyzhangx** [comment]
the smb-driver won't delete pv or pvc, it does not have such code, you may check kube-controller-manager to check why it happened.
