### ISSUE TITLE
Mount as non-root not working

### ISSUE THREAD

**Issue by Boenan** [kubernetes-csi/csi-driver-smb#532]
Hello,

I have specified user_id and group_id in mount points for the storageclass and PV object, which correspond to the user and group used in my container application.

```
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
```

Inside CSI driver pod we se the right uid and gid and also what is inside the smb storage folder:

```
ls -l /var/snap/microk8s/common/var/lib/kubelet/pods/podID/volumes/kubernetes.io~csi/pv-smb/mount
total 0
-rwxrwxrwx 1 1000 1001 0 Aug 19 13:29 findme.txt
```

However in my application container the PV is mounted as root for user and group. I presume that I can't see any files because of the wrong permissions.

```
$ id
uid=1000(gtu) gid=1001(gtg) groups=1001(gtg)

$ mount
/dev/mapper/ubuntu--vg-ubuntu--lv on /tmp/smb type ext4 (rw,relatime)

$ ls -l /tmp/
drwxr-xr-x 2 root root 4096 Aug 22 10:05 smb

$ ls -l /tmp/smb
total 0
```

I already configured securityContext with runAsUser, runAsGroup, fsGroup and it works for my other volume mounts, such as configMap objects.

Is this a problem related to SMB driver?

**Comment by andyzhangx** [comment]
your volume is mounted on `/tmp/smb` which is on local disk:
```
$ mount
/dev/mapper/ubuntu--vg-ubuntu--lv on /tmp/smb type ext4 (rw,relatime)
```

How is it related to this driver?

**Comment by Boenan** [comment]
I don't understand why the mount point should matter. The mount is connected to the PVC for SMB. 

It's the permissions on the mount path that is the problem. Why would it mount as root:root when its clearly stated that is should mount as 1000:1001 as shown in the csi-driver pod.

As an example, here is the mount for my configmap, which is the result I want:

```
$mount
/dev/mapper/ubuntu--vg-ubuntu--lv on /setup/gt_docker_config.ini type ext4 (ro,relatime)

$ ls -l /setup/
-rw-r--r-- 1 root gtg     396 Aug 22 12:19 gt_docker_config.ini
```

My understanding is that I can't change the user permission from root to non-root of a mount but the group follows the securityContext specified in the container configuration.

**Comment by andyzhangx** [comment]
this driver won't respect fsgrouppolicy: https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy since smb mount permission is determined at the moment when it's mounted, it cannot be changed after mount (smb driver is not Unix compatible)

**Comment by Boenan** [comment]
So how does this driver support containers running as non-root? As the mount is correct inside the csi-smb-node pod. How can I replicate this for my application pod?

**Comment by andyzhangx** [comment]
> So how does this driver support containers running as non-root? As the mount is correct inside the csi-smb-node pod. How can I replicate this for my application pod?

as long as permission is set correct, non-root pod could access those contents in smb server?

**Comment by Boenan** [comment]
The only thing I can find about the permission is under mountOptions for the StorageClass and PV. 

```
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
```

uid and gid are applied for the mount in the csi-smb-node pod.

```
$ ls -l /var/snap/microk8s/common/var/lib/kubelet/pods/podID/volumes/kubernetes.io~csi/pv-smb
drwxrwxrwx 2 1000 1001 0 Aug 19 13:36 mount

$ ls -l /var/snap/microk8s/common/var/lib/kubelet/pods/podID/volumes/kubernetes.io~csi/pv-smb/mount
-rwxrwxrwx 1 1000 1001 0 Aug 19 13:29 findme.txt
```

But the mount in my application pod mounts as root:root.

```
$ ls -l /tmp
drwxr-xr-x 2 root root 4096 Aug 22 12:19 smb

ls -l /tmp/smb
total 0
```

StorageClass, PV and PVC follows the [examples](https://github.com/kubernetes-csi/csi-driver-smb/tree/master/deploy/example) in github. The only thing I have changed is uid and gid.

Volume and mounts for my pod.

```
volumeMounts:
  - name: smb-persistent-storage
    mountPath:  /tmp/smb/
volumes:
  - name: smb-persistent-storage
    persistentVolumeClaim:
      claimName: pvc-smb
```

Is there something I'm missing?

**Comment by andyzhangx** [comment]
what's the output `mount | grep cifs` in your application? I think the cifs does not mount successfully by the driver.

**Comment by Boenan** [comment]
There is no output...

Is there an other way of debugging this issue?

**Comment by andyzhangx** [comment]
pls provide driver logs on the node: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by Boenan** [comment]
I noticed that the csi-controller pod is stuck in pending state. Its probably because one csi-pod-node is not getting deployed, one of our node is down. I presume the csi-controller is essential.

**Comment by Boenan** [comment]
@andyzhangx 

**Note:** I'm running version v.1.8.0

Every smb node and controller pods are up and running.

```
kubectl get po -o wide -n kube-system | grep csi-smb
csi-smb-node-4tqhb                           3/3     Running   0             9m1s   <IP>   kube1   <none>           <none>
csi-smb-node-8m8x7                           3/3     Running   0             9m1s   <IP>   kube2   <none>           <none>
csi-smb-node-2jgsr                           3/3     Running   0             9m1s   <IP>   kube3   <none>           <none>
csi-smb-controller-7c688577cb-hrj9g          3/3     Running   0             9m1s   <IP>   kube3   <none>           <none>
```

csi-smb-node logs:

```
$ k logs -n kube-system csi-smb-node-4tqhb
Defaulted container "liveness-probe" out of: liveness-probe, node-driver-registrar, smb
I0826 13:09:34.568624       1 main.go:149] calling CSI driver to discover driver name
I0826 13:09:34.571272       1 main.go:155] CSI driver name: "smb.csi.k8s.io"
I0826 13:09:34.571282       1 main.go:183] ServeMux listening at "0.0.0.0:29643"

$ k logs -n kube-system csi-smb-node-8m8x7
Defaulted container "liveness-probe" out of: liveness-probe, node-driver-registrar, smb
I0826 13:09:34.631190       1 main.go:149] calling CSI driver to discover driver name
I0826 13:09:34.633584       1 main.go:155] CSI driver name: "smb.csi.k8s.io"
I0826 13:09:34.633593       1 main.go:183] ServeMux listening at "0.0.0.0:29643"

$ k logs -n kube-system csi-smb-node-2jgsr
Defaulted container "liveness-probe" out of: liveness-probe, node-driver-registrar, smb
I0826 13:09:34.550782       1 main.go:149] calling CSI driver to discover driver name
I0826 13:09:34.552828       1 main.go:155] CSI driver name: "smb.csi.k8s.io"
I0826 13:09:34.552838       1 main.go:183] ServeMux listening at "0.0.0.0:29643"
```

Logs for csi-smb-controller pod:

```
k logs -n kube-system csi-smb-controller-7c688577cb-hrj9g
Defaulted container "csi-provisioner" out of: csi-provisioner, liveness-probe, smb
I0826 13:09:37.055803       1 feature_gate.go:245] feature gates: &{map[]}
I0826 13:09:37.055854       1 csi-provisioner.go:150] Version: v3.2.0
I0826 13:09:37.055858       1 csi-provisioner.go:173] Building kube configs for running in cluster...
I0826 13:09:38.057141       1 common.go:111] Probing CSI driver for readiness
I0826 13:09:38.059973       1 csi-provisioner.go:217] Detected CSI driver smb.csi.k8s.io
I0826 13:09:38.060845       1 csi-provisioner.go:289] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0826 13:09:38.061123       1 controller.go:732] Using saving PVs to API server in background
I0826 13:09:38.061309       1 leaderelection.go:248] attempting to acquire leader lease kube-system/smb-csi-k8s-io...
I0826 13:09:38.101994       1 leaderelection.go:258] successfully acquired lease kube-system/smb-csi-k8s-io
I0826 13:09:38.102059       1 leader_election.go:178] became leader, starting
I0826 13:09:38.202679       1 controller.go:811] Starting provisioner controller smb.csi.k8s.io_csi-smb-controller-7c688577cb-hrj9g_6ff70cb2-9c92-4a00-b849-f3accbb17ae8!
I0826 13:09:38.202801       1 volume_store.go:97] Starting save volume queue
I0826 13:09:38.304956       1 controller.go:860] Started provisioner controller smb.csi.k8s.io_csi-smb-controller-7c688577cb-hrj9g_6ff70cb2-9c92-4a00-b849-f3accbb17ae8!
```

Inside csi-smb-node 4tqhb pod we see the SMB mount, globalmount and mount... containing one findme.txt file with the right permissions for group and user.

```
ls -l /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount
total 0
-rwxrwxrwx 1 1000 1001 0 Aug 19 13:29 findme.txt

$ ls -l /var/snap/microk8s/common/var/lib/kubelet/pods/<PODID>/volumes/kubernetes.io~csi/pv-smb/mount
total 0
-rwxrwxrwx 1 1000 1001 0 Aug 19 13:29 findme.txt
```

Inside our application pod that mounts PVC, at /tmp/smb we see the wrong user/group permission and no file:

```
$ ls -l /tmp/
drwxr-xr-x 2 root root 4096 Aug 26 13:12 smb

$ ls -l /tmp/smb
total 0
```

**Comment by andyzhangx** [comment]
pls provide `-c smb` smb container logs(e.g. `kubectl logs csi-smb-node-xxx -c smb -n kube-system`), if smb mount succeeded, there is smb file system displayed by running `df` command, e.g. 
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#2-create-a-statefulset-with-smb-volume-mount

In your case, it looks like the pv is mounted to the local disk.

**Comment by Boenan** [comment]
Looking at other issue tickets regarding microk8s, which is what we use, I fixed the issue by adding custom kubelet path: `/var/snap/microk8s/common/var/lib/kubelet`
