### ISSUE TITLE
Move integration test in travis to test-infra

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#54]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

set up a few CI tests in test-infra, e.g.
 - pull-smb-csi-driver-unit 
 - pull-smb-csi-driver-verify
 - pull-smb-csi-driver-windows-build
 - pull-smb-csi-driver-integration
 - pull-smb-csi-driver-sanity

could put into 
https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-csi

and refer to https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/azurefile-csi-driver

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
Now only integration test is not moved to test-infra(disabled now) since integration test must run in a VM while all CI tests in test-infra run inside container, could refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/test/integration/integration_test.go

**Comment by boddumanohar** [comment]
I think the tests listed above already in test-infra: 

`pull-smb-csi-driver-unit` --> https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/csi-driver-smb/csi-driver-smb-config.yaml#L26

`pull-smb-csi-driver-verify` --> https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/csi-driver-smb/csi-driver-smb-config.yaml#L3

`pull-smb-csi-driver-windows-build` --> https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/csi-driver-smb/csi-driver-smb-config.yaml#L97

`pull-smb-csi-driver-integration` --> https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/csi-driver-smb/csi-driver-smb-config.yaml#L73

`pull-smb-csi-driver-sanity` --> https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/csi-driver-smb/csi-driver-smb-config.yaml#L49

So the only thing that has to be moved is Integration testing. 

Can you please provide more details on the integration testing. 

Thanks,
Manohar.

**Comment by andyzhangx** [comment]
maybe we could move integration test to github workflow:
https://github.com/kubernetes-csi/csi-driver-smb/tree/master/test/integration
