### ISSUE TITLE
connectivity issue between K8S POD and SMB Volumes

### ISSUE THREAD

**Issue by bandhavya98** [kubernetes-csi/csi-driver-smb#540]
[csi-controller-logs.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/9586030/csi-controller-logs.txt)
[csi-node-logs.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/9586031/csi-node-logs.txt)
[mount-file-exists.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/9586032/mount-file-exists.txt)
[new-mount-error.txt](https://github.com/kubernetes-csi/csi-driver-smb/files/9586033/new-mount-error.txt)
In our current AKS cluster which is running with version 1.22.6 and kernel version 5.4.0 ,we are using CSI SMB driver volumes. The distributed file system which is configured  on the Azure VM is used as the SMB driver volumes.
The issue is, we are facing the connectivity issue on the pod level where the SMB file systems are mounted . In some case , the SMB volumes are become inaccessible and sometime the mount volume itself is auto unmounting even though the pod is running state. when we try to create a new pod by scale out /in , the pods frequently stuck in container creating state .

**Comment by andyzhangx** [comment]
duplicated to https://github.com/kubernetes-csi/csi-driver-smb/issues/542
