### ISSUE TITLE
mount failed: exit status 32

### ISSUE THREAD

**Issue by kgnanaprakasam** [kubernetes-csi/csi-driver-smb#548]
**What happened**: when we launch statefulset.yaml [statefulset](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/statefulset.yaml), Pod is not launching. PVC is in a pending state.

PVC Creation error logs
===========================

52s         Normal    Provisioning           persistentvolumeclaim/persistent-storage-statefulset-smb-0   External provisioner is provisioning volume for claim "kube-system/persistent-storage-statefulset-smb-0"
60s         Normal    ExternalProvisioning   persistentvolumeclaim/persistent-storage-statefulset-smb-0   waiting for a volume to be created, either by external provisioner "smb.csi.k8s.io" or manually created by system administrator
52s         Warning   ProvisioningFailed     persistentvolumeclaim/persistent-storage-statefulset-smb-0   failed to provision volume with StorageClass "shsmb": rpc error: code = DeadlineExceeded desc = context deadline exceeded
52s         Warning   ProvisioningFailed     persistentvolumeclaim/persistent-storage-statefulset-smb-0   failed to provision volume with StorageClass "shsmb": rpc error: code = Internal desc = failed to mount smb server: rpc error: code = Aborted desc = An operation with the given Volume ID test.example.com/Shannon#pvc-5cf4e615-aa33-4aaa-8c5a-de0f036d5a22# already exists

csi-smb-controller - Pod logs
==============================

I1020 23:20:35.031737       1 utils.go:76] GRPC call: /csi.v1.Controller/CreateVolume
I1020 23:20:35.031789       1 utils.go:77] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-6790f9fd-609e-4677-90bd-5fe0b0225264","parameters":{"csi.storage.k8s.io/pv/name":"pvc-6790f9fd-609e-4677-90bd-5fe0b0225264","csi.storage.k8s.io/pvc/name":"persistent-storage-statefulset-smb-0","csi.storage.k8s.io/pvc/namespace":"kube-system","source":"//test.example.com/Shannon"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777"]}},"access_mode":{"mode":5}}]}
I1020 23:20:35.032386       1 controllerserver.go:255] internally mounting //test.example.com/Shannon at /tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264
I1020 23:20:35.032539       1 nodeserver.go:201] NodeStageVolume: targetPath(/tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264) volumeID(test.example.com/Shannon#pvc-6790f9fd-609e-4677-90bd-5fe0b0225264#) context(map[source://test.example.com/Shannon]) mountflags([dir_mode=0777 file_mode=0777]) mountOptions([dir_mode=0777 file_mode=0777])
I1020 23:20:35.033064       1 mount_linux.go:183] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,<masked> //test.example.com/Shannon /tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264)
I1020 23:20:40.258438       1 utils.go:76] GRPC call: /csi.v1.Controller/CreateVolume
I1020 23:20:40.258640       1 utils.go:77] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-251c29c5-0005-42a7-b2c0-9f31cbc37cc6","parameters":{"csi.storage.k8s.io/pv/name":"pvc-251c29c5-0005-42a7-b2c0-9f31cbc37cc6","csi.storage.k8s.io/pvc/name":"persistent-storage-statefulset-smb-0","csi.storage.k8s.io/pvc/namespace":"kube-system","source":"//test.example.com/Shannon"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777"]}},"access_mode":{"mode":5}}]}
I1020 23:20:40.259723       1 controllerserver.go:255] internally mounting //test.example.com/Shannon at /tmp/pvc-251c29c5-0005-42a7-b2c0-9f31cbc37cc6
I1020 23:20:40.259940       1 nodeserver.go:201] NodeStageVolume: targetPath(/tmp/pvc-251c29c5-0005-42a7-b2c0-9f31cbc37cc6) volumeID(test.example.com/Shannon#pvc-251c29c5-0005-42a7-b2c0-9f31cbc37cc6#) context(map[source://test.example.com/Shannon]) mountflags([dir_mode=0777 file_mode=0777]) mountOptions([dir_mode=0777 file_mode=0777])
I1020 23:20:40.260559       1 mount_linux.go:183] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,<masked> //test.example.com/Shannon /tmp/pvc-251c29c5-0005-42a7-b2c0-9f31cbc37cc6)
E1020 23:20:45.429413       1 mount_linux.go:195] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,<masked> //test.example.com/Shannon /tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

E1020 23:20:45.429535       1 utils.go:81] GRPC error: rpc error: code = Internal desc = failed to mount smb server: rpc error: code = Internal desc = volume(test.example.com/Shannon#pvc-6790f9fd-609e-4677-90bd-5fe0b0225264#) mount "//test.example.com/Shannon" on "/tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,<masked> //test.example.com/Shannon /tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

dmesg output
============

[Thu Oct 20 23:20:15 2022] CIFS: Attempting to mount //test.example.com/Shannon
[Thu Oct 20 23:20:26 2022] CIFS: VFS: Error connecting to socket. Aborting operation.
[Thu Oct 20 23:20:26 2022] CIFS: VFS: cifs_mount failed w/return code = -2
#
 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v1.9.0
- Kubernetes version (use `kubectl version`): OpenShift 4.10
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
Have you tried mounting manually on the agent node? and why there is a comma after `file_mode=0777`

```
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777, //test.example.com/Shannon /tmp/pvc-6790f9fd-609e-4677-90bd-5fe0b0225264
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
```

 - correct logging is like this:
```
mount_linux.go:183] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,<masked> //smb-server.default.svc.cluster.local/share /tmp/pvc-a3fa3586-2701-471c-ad15-9b6474ce510d)
```

**Comment by kgnanaprakasam** [comment]
It looks like,<masked> after not being captured in Github. I have tried mounting on the csi-smb-controller pod and getting the same error.

#
# mount -v -t cifs //test.example.com/Samba /tmp/test -o vers=3.0,username=Test,password=xyz,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
mount.cifs kernel mount options: ip=10.98.23.12,unc=\\test.example.com\Samba,vers=3.0,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30,user=Test,pass=********
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
#

**Comment by kgnanaprakasam** [comment]
masked value after comma is not being captured on Github

**Comment by kgnanaprakasam** [comment]
I am able to manually in Kubernetes node and it's not working inside the pods

**Comment by kgnanaprakasam** [comment]
If we are running the mount manually without providing a password in the command line, we are getting the below error "Failed to execute systemd-ask-password: No such file or directory"

# mount.cifs -vvv //x.x.x.x/Test /tmp/test  -o user=Test
Failed to execute systemd-ask-password: No such file or directory
Password for Test@//x.x.x.x/Test: 
mount.cifs kernel mount options: ip=x.x.x.x,unc=\\x.x.x.x\Test,user=Test,pass=********
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

**Comment by andyzhangx** [comment]
you could exec into the pod , e.g. `kubecl exec -it -n kube-system -c smb smb-xxx -- sh` and then do cifs mount manually

**Comment by kgnanaprakasam** [comment]
All I see below pods.I don't see any driver pods 

NAME                                  READY   STATUS              RESTARTS   AGE
csi-smb-controller-6bb7bcb4bd-r957x   3/3     Running             0          4h42m
csi-smb-node-7hr6b                    3/3     Running             0          4h41m
csi-smb-node-8vd6b                    3/3     Running             0          4h41m
csi-smb-node-9qtnm                    3/3     Running             0          4h41m
csi-smb-node-bkhps                    3/3     Running             0          4h41m
csi-smb-node-f64h7                    3/3     Running             0          4h41m
csi-smb-node-jftzl                    3/3     Running             0          4h42m
csi-smb-node-kw2rr                    3/3     Running             0          4h41m
csi-smb-node-ng8wb                    3/3     Running             0          4h41m
csi-smb-node-tbx5h                    3/3     Running             0          4h41m
csi-smb-node-vgcp2                    3/3     Running             0          4h41m
csi-smb-node-x8hzr                    3/3     Running             0          4h41m
statefulset-smb-0                     0/1     ContainerCreating   0          174m

**Comment by kgnanaprakasam** [comment]
I tried to manually mount on all of these pods and no luck. I am getting the same error. None of the pods name start with smb-xxx

**Comment by kgnanaprakasam** [comment]
I am not able to manually mount it on the Controller pod

[xxx@node01 ~]$ oc exec -it -n kube-system -c smb csi-smb-controller-6bb7bcb4bd-r957x -- sh
# mount -v -t cifs //test.example.com/Samba /tmp/test -o vers=3.0,username=Test,password=xxxxxxxx,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
mount.cifs kernel mount options: ip=x.x.x.x,unc=\\test.example.com\Samba,vers=3.0,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30,user=Test,pass=********
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
# exit
command terminated with exit code 32



It's working fine on driver pods

[xxx@node01 ~]$ oc exec -it -n kube-system -c smb csi-smb-node-7hr6b -- sh
# mount -v -t cifs //test.example.com/Samba /tmp/test -o vers=3.0,username=Test,password=xxxxxxxx,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30
mount.cifs kernel mount options: ip=x.x.x.x,unc=\\test.example.com\Samba,vers=3.0,dir_mode=0777,file_mode=0777,cache=strict,actimeo=30,user=Test,pass=********
# df -h /tmp/test
Filesystem                      Size  Used Avail Use% Mounted on
//test.example.com/Samba   20G  175M   20G   1% /tmp/test
#

**Comment by andyzhangx** [comment]
try set `hostNetwork: true` in controller deployment:
https://github.com/kubernetes-csi/csi-driver-smb/blob/596ca8d4e11c63a3d24ec1a5922b7dcecc6b9466/deploy/csi-smb-node.yaml#L20-L21

**Comment by kgnanaprakasam** [comment]
I tried adding hostNetwork: true in controller deployment. Still getting same error when mounting manually.

I am getting below messages in dmesg


[Fri Oct 21 15:19:48 2022] CIFS: Attempting to mount //test.example.com/Samba
[Fri Oct 21 15:19:58 2022] CIFS: VFS: Error connecting to socket. Aborting operation.
[Fri Oct 21 15:19:58 2022] CIFS: VFS: cifs_mount failed w/return code = -2

**Comment by kgnanaprakasam** [comment]
Issue caused due to Firewall
