### ISSUE TITLE
Password/Volume changes are ignored

### ISSUE THREAD

**Issue by steveizzle** [kubernetes-csi/csi-driver-smb#551]
**What happened**:

We created PVs and PVCs without StorageClasses. I can not say if the following also happens on StorageClasses. 

It occurs to me like volume mount options and changes in the password are not correctly taken over from the node. 
On a windows node there was a password change and we modified the secret. On a new node the volume gets correctly mounted, but on existing nodes (where the mount was successful before with the old password) the mount fails with an error: 

`Error: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\5c629d36-54eb-4c94-bb2c-2827af0a8e23\volumes\kubernetes.io~csi\smb-abc-xyz\mount:c:/Projekte': invalid mount config for type "bind": CreateFile c:\var\lib\kubelet\pods\5c629d36-54eb-4c94-bb2c-2827af0a8e23\volumes\kubernetes.io~csi\smb-abc-xyz\mount: Access is denied.`

Its also a little strange that i can not see an error in the DS on the node itself. The above error i only get on the pod.

The DS simply says sth like: 

`I1117 11:09:50.721973   13556 safe_mounter_windows.go:230] IsLikelyNotMountPoint: c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 11:09:50.721973   13556 safe_mounter_windows.go:287] Exists path: c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 11:09:50.722505   13556 safe_mounter_windows.go:287] Exists path: c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 11:09:50.723038   13556 smb_common_windows.go:74] Removing path: c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 11:09:50.723038   13556 safe_mounter_windows.go:199] Remove directory: c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 11:09:50.723038   13556 safe_mounter_windows.go:175] Mount: old name: \var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz\globalmount. new name: c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 11:09:55.396721   13556 nodeserver.go:85] NodePublishVolume: mount \var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-fnfs010-projekte\globalmount at c:\var\lib\kubelet\pods\d268354d-85fb-4d4c-ba3d-97404357d426\volumes\kubernetes.io~csi\smb-abc-xyz\mount volumeID(smb-abc-xyz) successfully
I1117 11:09:55.396721   13556 utils.go:83] GRPC response: {}`

I also observed this behavior on Linux nodes for example when mount options are changed. It seems like when the mount was previously mounted successfully it is not able to remove the old mount and use the new mount options. In Linux it could help to unmount the share from the node itself, but in windows i cant event find the mount with common ps commands.

Did you encounter this behavior before, are there some caveats i didnt see in the docs?

**What you expected to happen**:

Password changes or volume mount options are propagated correctly to the node

**How to reproduce it**:

Change passwords in secrets or change mount options

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: registry.k8s.io/sig-storage/csi-provisioner:v3.2.0 
- Kubernetes version (use `kubectl version`): 1.22
- OS (e.g. from /etc/os-release): windows and linux
- Install tools: helm csi-driver-smb-v1.9.0

**Comment by andyzhangx** [comment]
`Access is denied` error means original password is incorrect.

**Comment by steveizzle** [comment]
Yes you are right:

```
PS C:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz> dir | ?{$_.LinkType} | select FullName,LinkType,Target

FullName                                                                         LinkType     Target
--------                                                                         --------     ------
C:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz\globalmount SymbolicLink {UNC\path\Projekte\}


PS C:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz> cd globalmount
PS C:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz\globalmount> dir
dir : The specified network password is not correct.
At line:1 char:1
+ dir
+ ~~~
    + CategoryInfo          : ReadError: (C:\var\lib\kube...kte\globalmount:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand

```

But what can i do to enforce the usage of the new password on an existing node?

**Comment by andyzhangx** [comment]
@steveizzle if you are using https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.9.0, I think you could delete all the pods that are using this volume on the node, make this volume is mounted again on the node. This feature(https://github.com/kubernetes-csi/csi-driver-smb/pull/505) in v1.9.0 would remove the mounted dir on Windows node.

**Comment by andyzhangx** [comment]
if you are using older version, you should run `Remove-SmbGlobalMapping xxx` command to remove mounted dir on the windows node manually.

**Comment by steveizzle** [comment]
ok i could remove it, but somehow now it doesnt get recreated. But you say in newer versions this is no problem anymore?

**Comment by steveizzle** [comment]
It seems like we are already using v1.9.0. This is what i get when deleting all pods (DS): 

```
I1117 14:02:21.687198   18396 utils.go:76] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I1117 14:02:21.687198   18396 utils.go:77] GRPC request: {"target_path":"c:\\var\\lib\\kubelet\\pods\\9381c99a-91e4-4d87-9bae-0858f71f8c98\\volumes\\kubernetes.io~csi\\smb-abc-xyz\\mount","volume_id":"smb-abc-xyz"}
I1117 14:02:21.687198   18396 nodeserver.go:100] NodeUnpublishVolume: unmounting volume smb-abc-xyz on c:\var\lib\kubelet\pods\9381c99a-91e4-4d87-9bae-0858f71f8c98\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:02:21.687198   18396 safe_mounter_windows.go:199] Remove directory: c:\var\lib\kubelet\pods\9381c99a-91e4-4d87-9bae-0858f71f8c98\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:02:21.688224   18396 nodeserver.go:105] NodeUnpublishVolume: unmount volume smb-abc-xyz on c:\var\lib\kubelet\pods\9381c99a-91e4-4d87-9bae-0858f71f8c98\volumes\kubernetes.io~csi\smb-abc-xyz\mount successfully
I1117 14:02:21.688224   18396 utils.go:83] GRPC response: {}
```

After recreation i get (DS): 

```
I1117 14:04:47.386685   18396 utils.go:76] GRPC call: /csi.v1.Node/NodePublishVolume
I1117 14:04:47.386685   18396 utils.go:77] GRPC request: {"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\smb-abc-xyz\\globalmount","target_path":"c:\\var\\lib\\kubelet\\pods\\6e166084-b5b9-49fb-a972-6b007201a942\\volumes\\kubernetes.io~csi\\smb-abc-xyz\\mount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["gid=1001","file_mode=0700","uid=1001","dir_mode=0777","vers=3.0"]}},"access_mode":{"mode":5}},"volume_context":{"csi.storage.k8s.io/ephemeral":"false","csi.storage.k8s.io/pod.name":"secret-test-pod-5","csi.storage.k8s.io/pod.namespace":"body-hpc-gen2","csi.storage.k8s.io/pod.uid":"6e166084-b5b9-49fb-a972-6b007201a942","csi.storage.k8s.io/serviceAccount.name":"default","source":"//fnfs010.auto.contiwan.com/Projekte"},"volume_id":"smb-abc-xyz"}
I1117 14:04:47.386685   18396 safe_mounter_windows.go:230] IsLikelyNotMountPoint: c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:04:47.386685   18396 safe_mounter_windows.go:287] Exists path: c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:04:47.387223   18396 safe_mounter_windows.go:287] Exists path: c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:04:47.387744   18396 smb_common_windows.go:74] Removing path: c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:04:47.387744   18396 safe_mounter_windows.go:199] Remove directory: c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:04:47.387744   18396 nodeserver.go:78] NodePublishVolume: mounting \var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz\globalmount at c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount with mountOptions: [bind] volumeID(smb-abc-xyz)
I1117 14:04:47.388279   18396 safe_mounter_windows.go:175] Mount: old name: \var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz\globalmount. new name: c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount
I1117 14:04:47.492805   18396 nodeserver.go:85] NodePublishVolume: mount \var\lib\kubelet\plugins\kubernetes.io\csi\pv\smb-abc-xyz\globalmount at c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount volumeID(smb-abc-xyz) successfully
I1117 14:04:47.492805   18396 utils.go:83] GRPC response: {}
```

But on my describe pods it still looks like this: 

`Error: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount:c:/Projekte': invalid mount config for type "bind": CreateFile c:\var\lib\kubelet\pods\6e166084-b5b9-49fb-a972-6b007201a942\volumes\kubernetes.io~csi\smb-abc-xyz\mount: Access is denied.`


Calling `Remove-SmbGlobalMapping xxx` and repeating everything unfortunately also didnt help (I dont get it anymore with Get-SmbGlobalMapping )

There still seems to be an issue in the newest version

**Comment by andyzhangx** [comment]
if `Get-SmbGlobalMapping` returns with empty, that means there is no valid mounts currently. And `Access is denied` error means your username or password in secret is invalid.

**Comment by steveizzle** [comment]
Ok, but on a new node it is working properly with the same secret, so we got definitely a correct password. that's why I think we still got an issue.

**Comment by andyzhangx** [comment]
> Ok, but on a new node it is working properly with the same secret, so we got definitely a correct password. that's why I think we still got an issue.

@steveizzle retry restart current node or restart kubelet, I think secret is not refreshed on that node.
