### ISSUE TITLE
Change permissions in PVC

### ISSUE THREAD

**Issue by hobyte** [kubernetes-csi/csi-driver-smb#555]
I have created a storageclass like the one given in the [tutorial](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#1-create-a-storage-class). But some applications need different file permissions then 0777. How can I change the permission for the PVCs to fit my applications needs?

I tried changing them with `chmod` in the [nonroot statefulset](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/statefulset-nonroot.yaml), but It won't work.
```
I have no name!@statefulset-smb-nonroot-0:/$ ls -l /mnt/smb/
total 10
-rwxrwxrwx 1 1001 1001 16820 Nov 24 22:50 outfile
I have no name!@statefulset-smb-nonroot-0:/$ chmod 0700 /mnt/smb/outfile 
chmod: changing permissions of '/mnt/smb/outfile': Operation not permitted
I have no name!@statefulset-smb-nonroot-0:/$ sudo chmod 0700 /mnt/smb/outfile 
bash: sudo: command not found
```

**Comment by andyzhangx** [comment]
this is smb mount, you could specify mount options, e.g. 

https://github.com/kubernetes-csi/csi-driver-smb/blob/0449f51cc7233f6fc42d2464aecbcafa427e59e5/deploy/example/storageclass-smb.yaml#L17-L19

**Comment by hobyte** [comment]
I have, but those are for every PVC. Can I set different permissions per PVC?

**Comment by andyzhangx** [comment]
> I have, but those are for every PVC. Can I set different permissions per PVC?

@hobyte you could set different permissions(mountOptions) per PV instead of PVC.
