### ISSUE TITLE
Specify kernel parameters for controller pod

### ISSUE THREAD

**Issue by jim-bo** [kubernetes-csi/csi-driver-smb#558]
**Is your feature request related to a problem?/Why is this needed**
I am trying to use this plugin to mount Windows share on a local development k8s cluster (specifically docker-desktop). The share I am trying to mount only supports vers=2.0, however when trying to mount the share in a pod I get the error 22 message. When I try to mount the share directly inside the CIFS controller pod it doesn't work as well (same command works on a parallel linux machine).

When I view dmesg I get the following error
```[478984.798170] vers=2.0 mount not permitted when legacy dialects disabled```

Docker Desktop doesn't seem to have a clear path to set kernel parameters for the underlying VM. 

**Describe the solution you'd like in detail**

I was wondering if it would be possible to expose a parameter to set a specific kernel param in the controller pods "CIFS_ALLOW_INSECURE_LEGACY"

**Describe alternatives you've considered**
I've found several un-addressed issues/feature requests for Docker/Mac/Win around specifying kernel parameters but they haven't been taken up.

**Comment by andyzhangx** [comment]
@jim-bo do you have detailed example about how to set `CIFS_ALLOW_INSECURE_LEGACY`?
