### ISSUE TITLE
use new test-infra config

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#56]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

https://github.com/kubernetes/test-infra/pull/18223#discussion_r452354732

We actually have a script that generates pull and CI jobs for all the kubernetes-csi repos.

It involves ".prow.sh" with "UNIT", which already does build, verify, and unit tests. Do you want to use that instead?

test-infra/config/jobs/kubernetes-csi/gen-jobs.sh

Line 390 in c212d67

         - ./.prow.sh 
Unfortunately the CI part is a bit hardcoded to the hostpath driver, so we would need to do some additional work to make it work for other drivers too

**Describe alternatives you've considered**

**Additional context**

cc @Sakuralbj

**Comment by boddumanohar** [comment]
I think @Sakuralbj  has already done some initial work on this. And I can also seem those test run for every PR( https://prow.k8s.io/?repo=kubernetes-csi%2Fcsi-driver-smb) 

Can you please describe the next milestones of this issue.
