### ISSUE TITLE
csi-driver-smb on Windows fails to follow DFS namespace links

### ISSUE THREAD

**Issue by braveness23** [kubernetes-csi/csi-driver-smb#561]
Given the limitation that csi-driver-smb can only mount one SMB share it is essential that the user be given the opportunity to leverage DFS to aggregate disparate SMB network locations into one namespace.  csi-driver-smb on WIndows containers currently fails to navigate DFS namespaces.

When using csi-driver-smb, linux containers can fully access the entire namespace including navigating into DFS target directories.  

**What happened**:
When using csi-driver-smb on a Windows container attempting to access a directory that is a DFS link fails with the following error:

```
Get-ChildItem : The network location cannot be reached. For information about network troubleshooting, see Windows Help.
At line:1 char:1
+ Get-ChildItem -Recurse
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\mnt\smb\Target-1:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemComman
```

**What you expected to happen**:
csi-driver-smb allows access to files and folders within a DFS Namespace

**How to reproduce it**:

Use csi-driver-smb to mount a UNC path that is a DFS Namespace share.  Attempt to access any part of the directory structure that is a DFS Namespace target link

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v1.9.0
- Kubernetes version (use `kubectl version`): v1.25.2-gke.1700
- OS (e.g. from /etc/os-release): the container OS is Windows Core 2019 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
update notes from @braveness23 for tracking:
New-SmbGlobalMapping has a bug (that I have reported using the [Feedback Hub](https://aka.ms/AAj03f7)) where mapped DFS shares do not correctly navigate DFS target links.  From my testing I have determined that New-SmbMapping does not have this issue.

Will loop windows team to take a look.

**Comment by andyzhangx** [comment]
update from windows team:
DFS share is not supported in that cmdlet, it's a known issue and the fix is not in the roadmap yet.
