### ISSUE TITLE
SMB Pod Doesn't Recover After SMB Share Failover

### ISSUE THREAD

**Issue by jeyre05** [kubernetes-csi/csi-driver-smb#563]
Hi

We have a Kubernetes (version 1.21) EKS cluster (running Amazon Linux Version 2). We are using the 1.8.0 version of the csi-smb driver to map a share from a container to an AWS Windows FSX share.

The issue we have is when that FSX share goes down for maintenance (of which we have no controller, other than providing a weekly slot) It's redundant, so the FSX share fails over and then back to the preferred node after patching. However the smb pod, or the container with the mapped storage never recover. We have to manually restart the container, for it to map the smb share again.

The smb container shows this in the log every 2 minutes even though the FSX share is back up - 

GRPC error: rpc error: code = Internal desc = failed to stat file /var/lib/kubelet/pods/090ed878-bddd-4889-b076-965e59718ce7/volumes/kubernetes.io~csi/example-pv/mount: lstat /var/lib/kubelet/pods/090ed878-bddd-4889-b076-965e59718ce7/volumes/kubernetes.io~csi/example-backups-pv/mount: host is down

If you exec into the container with the mapped storage, it takes a while to ls on the mounted directory, but eventually also comes back with host down. As mentioned, a restart of the container with the mapped storage (not the smb pod) resolves the issue.

We have two environments and I can't seem to replicate the issue in our near prod environment. On comparing the csi-smb deployments between the two, there are some differences. The were done with the same 1.8.0 chart, but at different times, so some of the default values must have changed. 

On the environment that doesn't get an issue when FSX is failed over, I noticed that the parameter --enable-get-volume-stats=false, whereas the environment having the issue is set to --enable-get-volume-stats=true, so presume this is my issue based on the actual error. I can't seem to find much info on that parameter, so just wanted to get your thoughts. Would you expect that to be able to 'stat' the file once the AWS FSX share came backup? It it just checking the status of of the underlying volume or doing other functions? I'm going to try changing that value to 'true' by editing the daemonset deployment yaml in the near prod environment and  then see if the issue replicates there.

Many thanks

**Comment by andyzhangx** [comment]
it should be duplicated to this issue: https://github.com/kubernetes-csi/csi-driver-smb/issues/164, not sure how to fix this since smb driver does not support remount

**Comment by andyzhangx** [comment]
I think the point is when smb share failover, whether the original `mount -c cifs ...` mount would recover after failover, current answer is No, not sure what driver could do to avoid such issue.

**Comment by andyzhangx** [comment]
@jeyre05 btw, do you know after smb share failover, does the smb share IP change? Azure File share also has [failover feature](https://learn.microsoft.com/en-us/azure/storage/common/storage-disaster-recovery-guidance#understand-the-account-failover-process), and after failover, the smb share IP does not change, that could promise the original smb mount does work:

**Comment by cfredericksen** [comment]
@jeyre05 
@SenithDilitha 
I added the following liveness probe to my deployment and it works when I reboot the FileServer. I created an empty file in my mount and the pod will restart if it cant read the file. 
```
livenessProbe:
  exec:
    command:
    - cat
    - /mnt/vwpp01fs0001/ftpfiles/healthcheck.txt
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 2
```

**Comment by SenithDilitha** [comment]
I got it solved. The issue was with the mounted directory of the file server. There were a lot of files inside it. when mounting a volume, it reads each and every file. It cannot complete reading all the files before the deployment timeout.

**Comment by andyzhangx** [comment]
> I got it solved. The issue was with the mounted directory of the file server. There were a lot of files inside it. when mounting a volume, it reads each and every file. It cannot complete reading all the files before the deployment timeout.

@SenithDilitha why mounting a smb volume would read each and every file? that's strange behevior.
