### ISSUE TITLE
Health check fails during the deployment after mounting volumes using csi-smb-driver

### ISSUE THREAD

**Issue by SenithDilitha** [kubernetes-csi/csi-driver-smb#567]
I used the 2nd option to use csi-driver-smb using persistent volumes and persistent volume claims as described in the link - [here](https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md#option2-pvpvc-usage)

I have used health checks (liveness and readiness probes) for deployments. After using PV/PVC bound with SMB share the health checks fail and give the error "Connection refused". Therefore, the deployment fails

But When I ignore the health checks and deploy the services, the health check endpoints are working correctly. I need to use health check endpoints for deployments in order to maintain zero downtime. How can I solve this?

**Comment by andyzhangx** [comment]
@SenithDilitha what do you mean by `health checks fail`?  is the smb mount working or not?

**Comment by SenithDilitha** [comment]
smb mount works, health check probes ( liveness and readiness probes)  fails.
pod configurations: 
![image](https://user-images.githubusercontent.com/48232719/210210513-5deca8fe-5651-4dc3-b8c2-6d7394b6998b.png)
![image](https://user-images.githubusercontent.com/48232719/210210660-4ea0480c-f76b-45f2-9b5e-9be13c75d797.png)

volumes: 
![image](https://user-images.githubusercontent.com/48232719/210210723-0e425499-e577-4911-b1ef-2f1f3db30086.png)

PVC:
![image](https://user-images.githubusercontent.com/48232719/210210968-e9bce505-32b9-48c7-a733-7af7998a2465.png)

PV:
![Screenshot 2023-01-02 142800](https://user-images.githubusercontent.com/48232719/210211000-9c5f001c-8917-4d37-943a-435678203f67.png)

Error:
Liveness probe failed: Get "http://xx.xx.xx.xxx:5000/liveness": dial tcp 10.135.29.196:5000: connect: connection refused

**Comment by andyzhangx** [comment]
then I think that's your application issue

**Comment by andyzhangx** [comment]
> @andyzhangx let me elaborate. Health check probes in the application checks the '/hc' and '/liveness' endpoints of my application.
> 
> ```
>   1. If I configure only health check probes (no smb volume mounts), I can deploy it successfully.
>   2. If I configure only smb volume mounts (no health check probes), I can deploy it successfully. After the deployment, I 
>       checked the '/liveness' and '/hc' endpoints manually. Both are healthy. But they are not checked during the deployment 
>       since I have not configured the probes.
>   3. When I configure both together (health check probes and smb volume mounts), deployment pipeline timeouts. The pod 
>       description says that the '/liveness' endpoint is unhealthy. It's a 'connection refused' error.
> ```
> 
> Because of the point mentioned in number 2 above, it's not an error in the application. Somehow health check probes fail during the deployment. I cannot identify the reason.

@SenithDilitha could you follow this guide to check whether the underlying smb mount is valid?
https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by cfredericksen** [comment]
@SenithDilitha 
I added the following liveness probe to my deployment and it works when I reboot the FileServer. I created an empty file in my mount and the pod will restart if it cant read the file. 
```
livenessProbe:
  exec:
    command:
    - cat
    - /mnt/vwpp01fs0001/ftpfiles/healthcheck.txt
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 2
```
