### ISSUE TITLE
archiveOnDelete support possible?

### ISSUE THREAD

**Issue by ktivdv** [kubernetes-csi/csi-driver-smb#571]
Hello, it would be excellent if this CSI support archiveOnDelete, as does the nfs-subdir-provisioner. When PVCs are deleted, the subdir gets renamed to Archived-($originalSubdirName) instead of actually being deleted. I tried adding the parameter to the CSI-SMB storage class (archiveOnDelete: true) but then PVCs do not get bound upon creation. Would it be possible to add this feature? thanks!

**Comment by bauerjs1** [comment]
Is it already possible to prevent the provisioner from deleting the `StorageClass.parameters.subDir` during volume deletion? (Especially if the subDir existed in advance)

This would be especially useful for creating storage classes that narrow the volume data down to existing sub-paths within the net drive.

Maybe some parameter such as `subDirRetentionPolicy: Retain/Archive/Delete` might be useful?

nfs-subdir-provisionioner (mentionen in the OP) handles this with two parameters `onDelete` and `archiveOnDelete`, which is a little less intuitive, imho.

Cheers!

**Comment by sureshgoli25** [comment]
Hi, We are looking forward this feature to adopt for larger scale SMB shares.

**Comment by andyzhangx** [comment]
sure, I will take a look
