### ISSUE TITLE
Support for Azure File network storage 

### ISSUE THREAD

**Issue by jrbe228** [kubernetes-csi/csi-driver-smb#580]
smb-server-networkdisk.yaml shows an example of using the default storage class (AzureDisk in AKS) . 
This is a nice upgrade over hostPath storage approach in smb-server.yaml. Files persist through cluster stop/start or node reallocation unlike with hostPath storage. 

An even better option would be using AzureFile storage due to 5TB storage capacity. 
https://stackoverflow.com/questions/41126309/azure-blob-vs-file-vs-disk-storage. 

Attempting to use AzureFile for the StorageClass resulted in "Error 0x80070032: The request is not supported" when deleting files. This error occurred from both Windows and Linux clients.

**Comment by andyzhangx** [comment]
if you are setting up a smb server on Azure File, why not use azure file as `source` directly?

**Comment by jrbe228** [comment]
True, I could mount Azure Files directly to containers. I'm hoping to future-proof our cluster. Is there any risk from Azure Files and its SMB protocol continuing to evolve as a service? For example, is it possible compatibility could break with legacy containers, where some future Azure Files source could not mount directly to old Win/Linux containers? In that case, I would prefer to rely on the SMB CSI. I can always retrieve legacy versions of the SMB CSI which I know are mountable. Then I have choices for any storageClassName which is functional. Any of AzureDisk, hostPath, or potentially AzureFile.

**Comment by andyzhangx** [comment]
@jrbe228 azure file service always provide following way to mount smb share, so you could set `source: //accountname.file.core.windows.net/filesharename` in smb csi driver storage class:

```
mount -v -t cifs //accountname.file.core.windows.net/filesharename /tmp/test -o  username=accountname,password=accountkey
```

It's ok to always use smb csi driver since it would always works with azure file share, but it's not necessary to set up another smb server based on azure file smb service, that's quite strange way. `smb-server-networkdisk.yaml` is just an example to set up smb server on azure disk.

**Comment by jrbe228** [comment]
Ok thank you, I understand now. There is no need for an SMB server container in AKS when storing data on Azure Files. Using the SMB feature from Azure Files directly in the PV's `source` is simpler. In theory some future version of Azure Files could break compatibility with some specific SMB protocol `mount options: vers=X.0` in pv-smb-csi.yaml, but this is very unlikely. Feel free to close or delete the issue.
