### ISSUE TITLE
registry.k8s.io/sig-storage/smbplugin:v1.10.0 not found: manifest unknown

### ISSUE THREAD

**Issue by mateuszdrab** [kubernetes-csi/csi-driver-smb#586]
**What happened**:
Today's v1.10 update is failing to deploy, the image is not found in the repository.

`Error response from daemon: manifest for registry.k8s.io/sig-storage/smbplugin:v1.10.0 not found: manifest unknown: Failed to fetch "v1.10.0`

**What you expected to happen**:
Error free image pull

**How to reproduce it**:
`docker pull registry.k8s.io/sig-storage/smbplugin:v1.10.0`

The error was noticed on my K8s deployment first, so I tried a manual docker pull as indicated above to no avail.

**Comment by andyzhangx** [comment]
it's related to this PR(https://github.com/kubernetes/k8s.io/pull/4805) for publishing new images.

**Comment by mateuszdrab** [comment]
Thanks @andyzhangx 
Hopefully that process can be a bit more streamlined since this could cause outages for some users

**Comment by kylezimmerman** [comment]
Is there a workaround available? I am running a home cluster and had a power outage today and now most of my cluster can't come up because of this issue.

**Comment by andyzhangx** [comment]
> Is there a workaround available? I am running a home cluster and had a power outage today and now most of my cluster can't come up because of this issue.

@kylezimmerman you could install v1.9.0 version

**Comment by andyzhangx** [comment]
`docker pull registry.k8s.io/sig-storage/smbplugin:v1.10.0` is published, sorry for the delay, I will make the image publish process faster next time.

**Comment by xerxist** [comment]
Same issue again when upgrading to 1.11

**Comment by andyzhangx** [comment]
> Same issue again when upgrading to 1.11

@xerxist depends on https://github.com/kubernetes/k8s.io/pull/5338 merge

**Comment by andyzhangx** [comment]
registry.k8s.io/sig-storage/smbplugin:v1.11.0 is ready now after the above PR merged.
