### ISSUE TITLE
Windows Nodes - kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name smb.csi.k8s.io not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by burkhat** [kubernetes-csi/csi-driver-smb#594]
**What happened**:
Tried to mount a SMB volume into a Windows Container and got following error message;
`MountVolume.MountDevice failed for volume "pv" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name smb.csi.k8s.io not found in the list of registered CSI drivers`

**What you expected to happen**:
That the mount will be excecuted without any problem.

**How to reproduce it**:

This problem occurs only if we have following error message in the node-driver-registrar container:
But the error occurs only sometimes we cannot reproduce it at the moment.

```
I0222 13:51:36.967863   13656 main.go:166] Version: v2.5.1
I0222 13:51:36.976263   13656 main.go:167] Running node-driver-registrar in mode=registration
I0222 13:51:36.976329   13656 main.go:191] Attempting to open a gRPC connection with: "unix://C:\\\\csi\\\\csi.sock"
I0222 13:51:40.243011   13656 main.go:198] Calling CSI driver to discover driver name
I0222 13:51:40.263343   13656 main.go:208] CSI driver name: "smb.csi.k8s.io"
I0222 13:51:40.264405   13656 node_register.go:53] Starting Registration Server at: /registration/smb.csi.k8s.io-reg.sock
I0222 13:51:40.265484   13656 node_register.go:62] Registration Server started at: /registration/smb.csi.k8s.io-reg.sock
I0222 13:51:40.267045   13656 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I0222 13:51:40.562986   13656 main.go:102] Received GetInfo call: &InfoRequest{}
I0222 13:51:40.564534   13656 main.go:109] "Kubelet registration probe created" path="C:\\var\\lib\\kubelet\\plugins\\smb.csi.k8s.io\\registration"
I0222 13:51:40.585000   13656 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
E0307 14:17:53.239283   13656 connection.go:132] Lost connection to unix://C:\\csi\\csi.sock.
```

**Anything else we need to know?**:
After a POD restart or Node reboot the issue is fixed.

**Environment**:

- CSI Driver version: v1.9.0
- Kubernetes version (use `kubectl version`): Kubernetes Version: v1.24.6+5658434; Openshift Server Version: 4.11.25
- OS (e.g. from /etc/os-release): Windows Server 2022 - Version 21H2 (OS Build 20348.1487)
- Install tools: CSI-Proxy - Version: v1.11.2-15-g4f8b909
- Others:

**Comment by andyzhangx** [comment]
@burkhat what is your windows vm cpu core num and memory size?
node-driver-registrar would sometimes fail if Windows node has limited cpu, memory resources, we suggest using 4 cores, 17GB memory at least for windows node.

**Comment by burkhat** [comment]
@andyzhangx Thanks for your reploy our windows nodes have following resources 44 cores and 512GB memory.
Sometimes we have a huge CPU load up to 100% on the windows nodes because of GitLab build pipelines, could this be a problem?

**Comment by andyzhangx** [comment]
> @andyzhangx Thanks for your reply. Our windows nodes have following resources 44 cores and 512GB memory. Sometimes we have a huge CPU load up to 100% on the windows nodes because of GitLab build pipelines, could this be a problem?

@burkhat yes, that could be the issue. You could also get kubelet log on that node to get more details.

**Comment by burkhat** [comment]
@andyzhangx I've uploade the kubelet log from this node. [kubelet.zip](https://github.com/kubernetes-csi/csi-driver-smb/files/10989632/kubelet.zip)
So I should prevent the node from being 100% utilized
