### ISSUE TITLE
csi-smb-node's dns policy should be ClusterFirstWithHostNet

### ISSUE THREAD

**Issue by davidandreoletti** [kubernetes-csi/csi-driver-smb#600]
**What happened**:

Default **csi-smb-node** dnsPolicy ("Default") is IMHO ill suited as a default linux dns policy because:
- With "Default" the pod uses the [host's dns policy (ie the VM or physical host OS dns policy)](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy). A slightly better k8s dns policy should be "ClusterFirst".
- Additionally, the **csi-smb-node** pod is configured to use `hostNetwork:true`. In this case, k8s doc recommends "[ClusterFirstWithHostNet](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy)".

With the default Helm chart (v1.10+) values.yaml, "Default" is used. In this case, the **csi-smb-node** pod could not mount samba share from another pod on a different namespace. It failed with "mount failed: address is not resolved". 

**What you expected to happen**:

1. `linux.dnsPolicy` default value changed to "ClusterFirstWithHostNet" 
2. `controller.dnsPolicy` default value changed to "ClusterFirst" (optional?)
3. **csi-smb-node**' can now reach the samba pod.

**How to reproduce it**:

Change values.yaml's linux.dnsPolicy to ClusterFirstWithHostNet

**Anything else we need to know?**:

My samba pod was also configured to use `hostNetwork:true`

**Environment**:
- CSI Driver version: Chart v1.10.0+ from https://github.com/kubernetes-csi/csi-driver-smb/commit/7debaf03ad4f3f61f04a1067953f8a3d57779c4e
- Kubernetes version (use `kubectl version`): k8s 1.23.17
- OS (e.g. from /etc/os-release): ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15
- Install tools: N/A
- Others: N/A

**Comment by andyzhangx** [comment]
if your smb server is using k8s service address, e.g. `*.default.svc.cluster.local`, then `ClusterFirstWithHostNet` is more suitable, while in most production cases, smb server is a real domain name instead of k8s service address, in that case, `Default` is more suitable IMO.

**Comment by davidandreoletti** [comment]
The points about samba hosted on a real domain (ie a non k8s service address) and samba on hosted on a k8s domain are not mutually exclusive for the purpose of resolving the domain name. 

The current "Default" is IMHO too restrictive (ie only resolves non k8s service address[1]) while the new proposed default "ClusterFirst" [2][3] catches a larger spectrum of use cases: non k8s hosted samba and k8s hosted samba servers. 

Perhaps by "most production cases" you not only take into account current deployment but also the higher dns resolution cost associated with "ClusterFirst". If so, would you mind clarifying the rationale for the current "Default" in  helm's values.yaml for future readers please ?

[1] Unless the host dns is manually configured to forward cluster domain request back into the k8s cluster.
[2] The initially proposed "ClusterFirstWithHostNet" is actually is special case for pods with `hostNetwork` enabled like in my current samba setup

**Comment by andyzhangx** [comment]
thanks, I have worked out a PR to fix this issue: https://github.com/kubernetes-csi/csi-driver-smb/pull/604
