### ISSUE TITLE
External cifs mount failed

### ISSUE THREAD

**Issue by lratkajec** [kubernetes-csi/csi-driver-smb#629]
**What happened**:
After adding PV with smb share to pod, Pod won't start with error from pod events and csi-smb-node pod: 

code = Internal desc = Could not mount target "/var/lib/kubelet/pods/5d57b1dc-b645-4f8d-9529-d19045b04560/volumes/kubernetes.io~csi/cifs-fsdoc1/mount": wrong number of fields (expected 6, got 10)

**What you expected to happen**:
Pods spun up with no issue mounting SMB Volume

**How to reproduce it**:
Mount any smb share with csi driver and static provisioning of PV-s

**Environment**:

- CSI Driver version: V 1.11
- Kubernetes version (use `kubectl version`): v1.25.8+37a9a08
- OS (e.g. from /etc/os-release): Red Hat Enterprise Linux CoreOS release 4.12
- Kernel (e.g. `uname -a`): 4.18.0-372.53.1.el8_6.x86_64 linux
- Install tools: kubectl local install script
- Others: Openshift 4.12

**Comment by lratkajec** [comment]
Hi, here are the logs:
[csi-smb-node.log](https://github.com/kubernetes-csi/csi-driver-smb/files/11721555/csi-smb-node.log)
[cifs-mount.log](https://github.com/kubernetes-csi/csi-driver-smb/files/11721556/cifs-mount.log)
[csi-smb-node-description.log](https://github.com/kubernetes-csi/csi-driver-smb/files/11721558/csi-smb-node-description.log)

**Comment by andyzhangx** [comment]
I think it's caused by the space in source address, could you try a different address without space?

```
"source":"//fsdoc/MBU Public/Visa i MasterCard mandati/Mandati
```

**Comment by lratkajec** [comment]
We have sucessfully mounted a share without spacing, but we cant get those with space working, and those are the most important. We tried a combination of escapes, like  "\ ",   "\40", "\x20" but we are always back to the original error. I think these escapes are the right ones, because when you miss an escape, you get a different error and also the logs show the correct path and a success message, for example:

```
I0612 12:38:27.519793 1 utils.go:77] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/smb.csi.k8s.io/cbdd02101449c2b6fb35b266ba54261abec6282fc051ae8d58d1a0f9cfee5985/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","uid=4017","gid=4017"],"volume_mount_group":"1001150000"}},"access_mode":{"mode":5}},"volume_context":{"source":"//fsdoc/MBU Public/Visa i MasterCard mandati/Mandati"},"volume_id":"cifs-mandati"}

1098I0612 12:38:27.520021 1 nodeserver.go:206] NodeStageVolume: targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/smb.csi.k8s.io/cbdd02101449c2b6fb35b266ba54261abec6282fc051ae8d58d1a0f9cfee5985/globalmount) volumeID(cifs-mandati) context(map[source://fsdoc/MBU Public/Visa i MasterCard mandati/Mandati]) mountflags([dir_mode=0777 file_mode=0777 uid=4017 gid=4017]) mountOptions([dir_mode=0777 file_mode=0777 uid=4017 gid=4017])

1099I0612 12:38:27.522702 1 mount_linux.go:220] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,uid=4017,gid=4017,<masked> //fsdoc/MBU Public/Visa i MasterCard mandati/Mandati /var/lib/kubelet/plugins/kubernetes.io/csi/smb.csi.k8s.io/cbdd02101449c2b6fb35b266ba54261abec6282fc051ae8d58d1a0f9cfee5985/globalmount)

1100I0612 12:38:27.540730 1 nodeserver.go:238] volume(cifs-mandati) mount "//fsdoc/MBU Public/Visa i MasterCard mandati/Mandati" on "/var/lib/kubelet/plugins/kubernetes.io/csi/smb.csi.k8s.io/cbdd02101449c2b6fb35b266ba54261abec6282fc051ae8d58d1a0f9cfee5985/globalmount" succeeded
```

**Comment by andyzhangx** [comment]
it failed here with the mount info: https://github.com/kubernetes/kubernetes/blob/18d05b646d09b2971dc5400bc288062b0414e8cf/staging/src/k8s.io/mount-utils/mount_helper_unix.go#L109

**Comment by zwurv** [comment]
Hi, has this been dealt with?
I'm concerned as this is the codebase/version that will be used for OpenShift 4.12 installs, which causes all cifs mounts with spaces or spaces and escapes to fail.
Is anyone willing to produce a newer release if a PR with the fix was put in?

Thank you!

**Comment by venesh0709** [comment]
@zwurv gcr.io/k8s-staging-sig-storage/smbplugin:canary is not working for me with spaces.  Did you try anything else along with this?

**Comment by venesh0709** [comment]
ocpv4.12.25
K8s v1.25.11
@zwurv

**Comment by zwurv** [comment]
@venesh0709 
We upgraded to OCP 4.12 from 4.10 and ended up downgrading back to 4.10 afterwards because of this specific problem.
We never overcame this yet and need to upgrade again for 4.12 soon, sounds like this canary build in staging sig storage won't work, I thought it was that. 

Sounds like it's really a change in Kubernetes 1.25 from 1.23 (OCP 4.10).
Please let me know if you figure this out, we're struggling with this too.

**Comment by venesh0709** [comment]
@zwurv Hey, May I know how did you downgrade the OCP cluster to previous version?

We are running on AWS.

Did you try the escape character?

**Comment by zwurv** [comment]
@venesh0709 Hi, we always use Ansible for the creation/destruction of the cluster, in our case we used that script, destroyed the cluster and rebuilt, and finally used build & release pipelines to redeploy our apps. There's no downgrading of OpenShift.
We tried the escape character and that didn't work.
I'm uncertain if the issue is just this character (which we never used prior to this and use this staging v1.13 docker image).

I'm wondering if this problem is mixed with PodSecurityPolicy deprecation.
https://connect.redhat.com/en/blog/important-openshift-changes-pod-security-standards

**Comment by venesh0709** [comment]
@zwurv  It seems like all the roads are blocked. RedHat do not support CIFS. So, they might have taken out something from 4.12(Removed APIs) which directly affected CIFS with spaces functionality. Red Hat would not even knew about CIFS failure as they never would have CIFS. What are your plans as of now?

**Comment by zwurv** [comment]
> 

Hi @venesh0709, I believe support was removed as of OpenShift 4.11. One of my team members is working on a resolution and once he finds it I'll ask his permission to post here so you can be informed. This will likely be solved within the next week, although I don't know what sort of resolution we'll have.

**Comment by zwurv** [comment]
hi @venesh0709, looks like a colleague of mine found a way around this.
If you've got cifs mounts with paths with spaces in them, create a symlink without spaces on the windows server that points to the path with the spaces, and use that new symlink path without spaces in your pv. This seems to work, we gave it a quick test.

Let us know if this works :)

**Comment by venesh0709** [comment]
@zwurv We have tried that and mounting was successful but unfortunately we did not same files in symlink(without spaces) and path with spaces. However, we are glad that it is working for you.
