### ISSUE TITLE
Kerberos tickets are not refreshed when after updating smbcreds secret

### ISSUE THREAD

**Issue by sega19** [kubernetes-csi/csi-driver-smb#640]
Looks like KRB5_1000 files is only created during NodeStageVolume, which is only run the first time a pod (on a particular worker node) uses the PV/PVC.
If I push a new ticket into the smbcreds Kubernetes secret, it is not used unless all pods are destroyed.

**Comment by andyzhangx** [comment]
could you help? thanks.
@yerenkow @edward2a

**Comment by andyzhangx** [comment]
that's expected since the kerberos ticket is only used during NodeStageVolume when you remount the pv.
