### ISSUE TITLE
Is it possible to mount Windows subfolders that contain special characters in the folder name?

### ISSUE THREAD

**Issue by em47390** [kubernetes-csi/csi-driver-smb#669]
As title, we have successfully mounted Windows folders in K8s pods, but failed to open/browse it if the folder contains several subfloders that named with special characters. Wondering the csi-driver-smb tool support special character folder path or not? If yes, may I know how to configure it? thanks!

**Comment by andyzhangx** [comment]
are you mounting smb folder on Linux? if mounted successfully, what's the output of `ls -lt xx` on the node?
