### ISSUE TITLE
Mounts no longer work with kernel update

### ISSUE THREAD

**Issue by savisaar2** [kubernetes-csi/csi-driver-smb#699]
**What happened**:
Kubernetes mounts no longer work after updating the node. Error: cifs no longer supported by the system.

**What you expected to happen**:
Successful mounting of the share.

**How to reproduce it**:
Install and mount share using Ubuntu 23.04, update to 23.10, and attempt to mount.

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: no output from command.
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): Linux K3s-worker-01 6.5.0-13-generic #13-Ubuntu SMP PREEMPT_DYNAMIC Fri Nov  3 12:16:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
pls check whether there are new kernel version released, the latter version should have installed cifs driver again.
