### ISSUE TITLE
password should not be exposed in logs

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#7]
**What happened**:
password should not be exposed in logs:
```
 nodeserver.go:120] NodeStageVolume called with request {arbitrary-volumeid map[] /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount mount:<mount_flags:"dir_mode=0777" mount_flags:"file_mode=0777" mount_flags:"vers=3.0" > access_mode:<mode:MULTI_NODE_MULTI_WRITER >  map[password:..dYGisUKDE3axDL6x1KyEj9j9PrUp0Yd7U/WbZ0Ip1uluWQr8FSkFgQhIO6fhaCGKd+aJSCrnTgR3m99OMQ== username:f8471372a68594910913ed4] map[source://f8471372a68594910913ed4.file.core.windows.net/kubernetes-dynamic-pvc-687cfca7-4880-4dbc-9daa-be4bc39b8eaa] {} [] 0}
I0510 03:32:33.846897       1 nodeserver.go:169] targetPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount) volumeID(arbitrary-volumeid) context(map[source://xxx.file.core.windows.net/kubernetes-dynamic-pvc-687cfca7-4880-4dbc-9daa-be4bc39b8eaa]) mountflags([dir_mode=0777 file_mode=0777 vers=3.0]) mountOptions([dir_mode=0777 file_mode=0777 username=f8471372a68594910913ed4,password=...YGisUKDE3axDL6x1KyEj9j9PrUp0Yd7U/WbZ0Ip1uluWQr8FSkFgQhIO6fhaCGKd+aJSCrnTgR3m99OMQ== vers=3.0])
```

https://github.com/csi-driver/csi-driver-smb/blob/bcd8d774b631d8a6281ed7184a357183c84fff29/deploy/example/logs/csi-smb-node.log#L39

similar to fix: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/64

related code:
https://github.com/csi-driver/csi-driver-smb/blob/bcd8d774b631d8a6281ed7184a357183c84fff29/pkg/csi-common/utils.go#L112

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by animeshk08** [comment]
Hi @andyzhangx Can I work on this issue?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx Can I work on this issue?

sure
/assign @animeshk08

**Comment by andyzhangx** [comment]
are you a student  applying for this linux community bridge now?  @animeshk08
https://people.communitybridge.org/project/2d438b9a-c539-46d0-9eed-c6ee4404c88a
if so, add my slack: andyzhang @kubernetes
