### ISSUE TITLE
need new dockerfile.windows for windows 2022 server

### ISSUE THREAD

**Issue by thdrnsdk** [kubernetes-csi/csi-driver-smb#728]
**Is your feature request related to a problem?/Why is this needed**

in the repo's 

livenessprobe
smbplugin
node-driver-registrar

 dockerfile.windows
there is base, addon image is windwos images "1809"

Images created in this way do not seem to work on Windows 2022 servers due to version compatibility issues.

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
the 1809 specified in Dockerfile.Windows file is the default base image, and `servercore:ltsc2022` is specified in prow.sh, so this driver already supports 2022 image.

https://github.com/kubernetes-csi/csi-driver-smb/blob/1aaea30ac994ae4e498844644e2961920f54ae94/release-tools/prow.sh#L81

**Comment by andyzhangx** [comment]
I have also verified that this image `registry.k8s.io/sig-storage/smbplugin:v1.13.0` is running well on `Windows Server 2022 Datacenter` node
