### ISSUE TITLE
which Samba container image does this project use?

### ISSUE THREAD

**Issue by obnoxxx** [kubernetes-csi/csi-driver-smb#735]
I would like to understand where to find the Samba container image referenced here: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/smb-provisioner/smb-server.yaml#L35

I could not figure it out from the yaml myself.

Interested in both image registry  location and Containerfile definition.

**Comment by andyzhangx** [comment]
this image is defined from https://github.com/dperson/samba, and it's only for testing purpose.

**Comment by obnoxxx** [comment]
@andyzhangx  wrote:

> this image is derived from https://github.com/dperson/samba, and it's only for testing purpose.

Thanks for the response!


I would like to mention here, that together with @phlogistonjohn and a few others, I am maintaining a  github org for Samba in kuberbetes, https://github.com/samba-in-kubernetes which hosts projects for a samba container and operator amng others:
* https://github.com/samba-in-kubernetes/samba-container
* https://github.com/samba-in-kubernetes/samba-operator
*

**Comment by obnoxxx** [comment]
@andyzhangx  wrote:
> this image is derived from https://github.com/dperson/samba, and it's only for testing purpose.

ok, sp you're saying the container this csi driver uses is derived from the above image. But where can I see that derivation (dockerfile etc) and where are builds hosted?

**Comment by andyzhangx** [comment]
> @andyzhangx wrote:
> 
> > this image is derived from https://github.com/dperson/samba, and it's only for testing purpose.
> 
> ok, sp you're saying the container this csi driver uses is derived from the above image. But where can I see that derivation (dockerfile etc) and where are builds hosted?

@obnoxxx I just run `docker tag dperson/samba andyzhangx/samba:win-fix` to get a fixed image version. anyway, do you have a working container image version, I could try switch to a new one if that works, thanks.

**Comment by obnoxxx** [comment]
> > @andyzhangx wrote:
> > > this image is derived from https://github.com/dperson/samba, and it's only for testing purpose.
> > 
> > 
> > ok, sp you're saying the container this csi driver uses is derived from the above image. But where can I see that derivation (dockerfile etc) and where are builds hosted?
> 
> @obnoxxx I just run `docker tag dperson/samba andyzhangx/samba:win-fix` to get a fixed image version.


Thanks, that answers my question!


 anyway, do you have a working container image version,

yes, The images produced frpm https://github.com/samba-in-kubernetes/samba-container should work.

Pre-built images are available at https://quay.io/organization/samba.org.

Note that we have nightly variants that use nightly builds from the  upstream samba master branch as well as stable variants that use the stable Samba packages  from the container's base image distribution. various flavors of the image have different entry points and different configuration mrvhanisms. For setting up an SMB file server, the :Samba Server" glavor is the most appropriate: https://github.com/samba-in-kubernetes/samba-container#samba-server 

downloadable from here: https://quay.io/repository/samba.org/samba-server?tab=tags

You are more than welcome to try one of those images for your purposes and please don't hesitate to reach out if you have any questions. We'll be happy to help. 





 I could try switch to a new one if that works, thanks.
