### ISSUE TITLE
Please publish to OCI

### ISSUE THREAD

**Issue by PrivatePuffin** [kubernetes-csi/csi-driver-smb#758]
**Is your feature request related to a problem?/Why is this needed**
OCI is slowly becoming the go-to standard for helm charts.
Having http based charts in-between (over)complicates dependency management.

**Describe the solution you'd like in detail**
Publish to OCI, for example: GHCR is a viable option

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
@Ornias1993 what do you mean `http based charts`? current helm chart install is referencing https address, e.g.
```
helm repo add csi-driver-smb https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
helm install csi-driver-smb csi-driver-smb/csi-driver-smb --namespace kube-system --version v1.14.0
```

**Comment by Ornias1993** [comment]
> @Ornias1993 what do you mean `http based charts`? current helm chart install is referencing https address, e.g.
> 
> ```
> helm repo add csi-driver-smb https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
> helm install csi-driver-smb csi-driver-smb/csi-driver-smb --namespace kube-system --version v1.14.0
> ```

What I mean with http based charts, is every chart system with repo's that are not OCI based.
Https is secure http after-all.

I think that's quite obvious though... As there are only three helm repo options: http(s), file and OCI
