### ISSUE TITLE
runOnControlPlane/runOnMaster: true make the controller unschedulable

### ISSUE THREAD

**Issue by janfrederik** [kubernetes-csi/csi-driver-smb#861]
**What happened**:
Setting controller.runOnControlPlane: true makes the controller unschedulable.  
The same applies to controller.runOnMaster.

This is the same problem as https://github.com/kubernetes-csi/csi-driver-nfs/issues/787.

**What you expected to happen**:
The controller to get scheduled

**How to reproduce it**:
- k3s 1.30
- install csi-driver-smb v1.16.0 with following values.yaml

```yaml
controller:
  runOnControlPlane: true
```

**Environment**:

- CSI Driver version: 1.16.0
- Kubernetes version (use `kubectl version`): v1.30.6+k3s1
- OS (e.g. from /etc/os-release): openSUSE MicroOS 20241104
- Kernel (e.g. `uname -a`): 6.11.5-2-default

**Comment by janfrederik** [comment]
I see the control plane nodes have label `node-role.kubernetes.io/control-plane=true`.  
The node-selector is `node-role.kubernetes.io/control-plane: ""`

These doesn't match by the way kubernetes matches labels to selectors. See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors.

We probably want a simple node-selector of type "exists", without specifying a value: `node-role.kubernetes.io/control-plane`.

For reference: official doc on the control-plane label: https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-control-plane.

**Comment by andyzhangx** [comment]
there are other k8s clusters that the master node has label `node-role.kubernetes.io/control-plane=` with (empty value), so this one `controller.runOnControlPlane` cannot match the two conditions, if we fix one, then another breaks, and we already have tolerations defined here 

```  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"


https://github.com/kubernetes-csi/csi-driver-nfs/blob/18fdc4a39eb451c7f361effb79cd6a7dc5b4d601/charts/latest/csi-driver-nfs/values.yaml#L62-L76

**Comment by janfrederik** [comment]
Wouldn't we simple remove `controller.runOnControlPlane` and `controller.runOnMaster` from values.yaml because
- it is broken anyway;
- the use of the labels `node-role.kubernetes.io/control-plane` and `node-role.kubernetes.io/master` is not exactly the same in all k8s cluster implementation (according to @andyzhangx above);
- values.yaml already provides already controller.nodeSelector and controller.affinity for specifying node affinity;
- it is impossible to blindly merge user provided `affinity` clauses with automatically generated `affinity` clauses, respecting the users intended and/or logic.

Instead, we can add some examples to the doc or as comments in values.yaml on how to use `nodeSelector` or `affinity` for the cases of runOnControlPlane and runOnMaster.

**Comment by scipsycho** [comment]
Either that or we should mention it in the docs that it may not work for some implementations.

**Comment by andyzhangx** [comment]
I have fixed this issue by using 

```yaml
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
```

**Comment by janfrederik** [comment]
@andyzhangx Thank you! 

Note that exactly the same problem exists with runOnMaster. So it is probably a good idea to add the same fix for that one.

**Comment by janfrederik** [comment]
I think it is useful to mention in the docs and as a comment in the values.yaml that runOnControlPlane=true only has an effect if the user doesn't have an affinity-block in their values.yaml.

**Comment by janfrederik** [comment]
@andyzhangx Super, thanks!
