### ISSUE TITLE
secret change

### ISSUE THREAD

**Issue by mysiki** [kubernetes-csi/csi-driver-smb#877]
hey all, 

I have a question about https://github.com/kubernetes-csi/csi-driver-smb, I use it on AWS EKS windows node to mount AWS FSX (it's work well).

To mount pv/pvc I use k8s secret in SC (as documented). For security reason and because of password expiration I want to renew the password regularly (like every saturday).

Question : It's a problem to renew the secret content (without changing the secret name) ? Does the csi take care about it, aka, take care of new password without manual action ?

Question bonus : I don't really got the point about windows CSI proxy usage, my setup work without it, what is the goal of this component ? should be deployed ? (I read the technical doc about it but don't understand if I need it ...)

br,

**Comment by andyzhangx** [comment]
>  It's a problem to renew the secret content (without changing the secret name) ? Does the csi take care about it, aka, take care of new password without manual action ?

CSI driver only uses the secret during mount, so if secret is updated, you need to delete pod to make sure remount happen manually.

> I don't really got the point about windows CSI proxy usage, my setup work without it, what is the goal of this component ? should be deployed ? (I read the technical doc about it but don't understand if I need it ...)

windows CSI proxy is for mounting smb volume on Windows node, https://github.com/kubernetes-csi/csi-proxy

**Comment by mysiki** [comment]
Clear, thanks you. 

> windows CSI proxy is for mounting smb volume on Windows node

I didn't got this point... I use Windows node with windows container and this CSI work without csi-proxy ... Or csi-proxy is not related to container but to really mount into the node and use local storage on the container ?

**Comment by andyzhangx** [comment]
I think you could get the csi driver logs on the node to check how csi-proxy works with this csi driver, all the smb mounts on Windows are using csi-proxy:
https://github.com/kubernetes-csi/csi-driver-smb/blob/c5f0687e3a538ee8f5bc46f255c358296c714b32/pkg/mounter/safe_mounter_windows.go#L71-L72

**Comment by mysiki** [comment]
ok thanks, I will check that.
