### ISSUE TITLE
add e2e test 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-smb#9]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Would work on this after migration to 
https://github.com/kubernetes-csi/csi-driver-smb

refer to following link to set up a containerized samba in CI environment:
https://github.com/dperson/samba

**Describe alternatives you've considered**

 - step 1. suppose you are already on a k8s cluster, run `make e2e-test` on this cluster, could refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/test/e2e
(need install driver manually before run make e2e-test)
 - step 2. use test-infra to set up a k8s cluster(probably azure k8s cluster) and then build csi driver, install csi driver by helm chart installation. Let's work on step 1 first.

**Additional context**

**Comment by andyzhangx** [comment]
step 1. suppose you are already on a k8s cluster, run `make e2e-test` on this cluster, could refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/test/e2e

@animeshk08 do you have time to take a look? thanks.

**Comment by andyzhangx** [comment]
step 2. use test-infra to set up a k8s cluster(probably azure k8s cluster) and then build csi driver, install csi driver by helm chart installation. Let's work on step 1 first.

**Comment by animeshk08** [comment]
Sure. Thanks!

**Comment by andyzhangx** [comment]
> Sure. Thanks!

follow this guide to set up a samba server on k8s cluster, and we already supports dynamic provisioning: https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md

**Comment by andyzhangx** [comment]
@animeshk08 for step 2. if we could run CSI driver on minikube, that would be quite easier and stable to set up test pipeline, could you check whether we could run CSI driver on minikube: https://kubernetes.io/docs/setup/learning-environment/minikube/, thanks.

**Comment by animeshk08** [comment]
Sure! I will check. Thanks.
